INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = tweak_weibo

tweak_weibo_FILES = Tweak.x
tweak_weibo_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
