//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BUTrackerProxy;

@interface BUTracker : NSObject
{
    BUTrackerProxy *_trackerProxy;
}

+ (id)sharedTracker;
@property(retain, nonatomic) BUTrackerProxy *trackerProxy; // @synthesize trackerProxy=_trackerProxy;
- (void).cxx_destruct;
- (void)eventData:(id)arg1;

@end

