//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class BUAdSlot, BUMaterialMeta, NSString, UIButton, UITapGestureRecognizer;
@protocol BUBUVideoBottomMaskClickDelegate;

@interface BUVideoBottomMask : UIView <UIGestureRecognizerDelegate>
{
    id <BUBUVideoBottomMaskClickDelegate> _delegate;
    BUMaterialMeta *_materialMeta;
    BUAdSlot *_slot;
    UITapGestureRecognizer *_tapGesture;
    UITapGestureRecognizer *_subviewsTapGesture;
    UIButton *_downloadButton;
}

@property(retain, nonatomic) UIButton *downloadButton; // @synthesize downloadButton=_downloadButton;
@property(retain, nonatomic) UITapGestureRecognizer *subviewsTapGesture; // @synthesize subviewsTapGesture=_subviewsTapGesture;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) BUAdSlot *slot; // @synthesize slot=_slot;
@property(retain, nonatomic) BUMaterialMeta *materialMeta; // @synthesize materialMeta=_materialMeta;
@property(nonatomic) __weak id <BUBUVideoBottomMaskClickDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)c_xyDict;
- (void)subViewsTapped:(id)arg1;
- (void)maskTapped:(id)arg1;
- (void)addGesture;
- (void)buildUpView;
- (void)layoutSubviews;
- (id)initWithMaterialMeta:(id)arg1 slot:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

