//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GDTLocalFileUtil : NSObject
{
}

+ (void)saveDataToLocalFile:(id)arg1 fileName:(id)arg2;
+ (void)checkAndCreateFolder:(id)arg1;
+ (id)loadDataFromLocalFile:(id)arg1;
+ (id)rootFolder;

@end

