//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTUnifiedNativeAdDelegate-Protocol.h"
#import "GDTUnifiedNativeAdNetworkAdapterProtocol-Protocol.h"

@class GDTUnifiedNativeAdImp, GDTUnifiedNativeAdMediator, NSArray, NSString;

@interface GDTUnifiedNativeAdAdapter : NSObject <GDTUnifiedNativeAdNetworkAdapterProtocol, GDTUnifiedNativeAdDelegate>
{
    long long maxVideoDuration;
    GDTUnifiedNativeAdMediator *_connector;
    GDTUnifiedNativeAdImp *_unifiedNativeAdImp;
    NSArray *_dataObjectArray;
}

+ (id)adapterVersion;
@property(retain, nonatomic) NSArray *dataObjectArray; // @synthesize dataObjectArray=_dataObjectArray;
@property(retain, nonatomic) GDTUnifiedNativeAdImp *unifiedNativeAdImp; // @synthesize unifiedNativeAdImp=_unifiedNativeAdImp;
@property(nonatomic) __weak GDTUnifiedNativeAdMediator *connector; // @synthesize connector=_connector;
@property(nonatomic) long long maxVideoDuration; // @synthesize maxVideoDuration;
- (void).cxx_destruct;
- (void)gdt_unifiedNativeAdLoaded:(id)arg1 error:(id)arg2;
- (long long)priority;
- (long long)eCPM;
- (void)loadAdWithCount:(long long)arg1;
- (id)initWithAdNetworkConnector:(id)arg1 posId:(id)arg2 extStr:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

