//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTMNetworkConfigModel, GDTUnifiedNativeAdModel, GDTVideoConfig, NSArray, NSNumber, NSString;
@protocol GDTUnifiedNativeAdDataObjectAdapterProtocol><GDTMediaViewAdapterProtocol;

@interface GDTUnifiedNativeAdDataObject : NSObject
{
}

@property(retain, nonatomic) GDTVideoConfig *videoConfig;
@property(readonly, nonatomic) NSString *callToAction;
@property(readonly, nonatomic) NSString *eCPMLevel;
@property(readonly, nonatomic) long long eCPM;
@property(readonly, nonatomic) long long imageHeight;
@property(readonly, nonatomic) long long imageWidth;
- (_Bool)equalsAdData:(id)arg1;
@property(readonly, nonatomic) _Bool isThreeImgsAd;
@property(readonly, nonatomic) _Bool isVideoAd;
@property(readonly, nonatomic) _Bool isAppAd;
@property(readonly, nonatomic) NSNumber *appPrice;
@property(readonly, nonatomic) double appRating;
@property(readonly, copy, nonatomic) NSArray *mediaUrlList;
@property(readonly, copy, nonatomic) NSString *iconUrl;
@property(readonly, copy, nonatomic) NSString *imageUrl;
@property(readonly, copy, nonatomic) NSString *desc;
@property(readonly, copy, nonatomic) NSString *title;
- (id)model;
@property(nonatomic) _Bool isExposured;
@property(retain, nonatomic) GDTUnifiedNativeAdModel *adModel; // @dynamic adModel;
- (_Bool)isMediationData;
- (long long)finalPriority;
@property(retain, nonatomic) id <GDTUnifiedNativeAdDataObjectAdapterProtocol><GDTMediaViewAdapterProtocol> dataObjectAdapter;
@property(retain, nonatomic) GDTMNetworkConfigModel *networkConfigModel;
@property(readonly, nonatomic) NSString *placementId;

@end

