//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (XMPay)
- (double)xmp_safeDoubleValueForKey:(id)arg1;
- (long long)xmp_safeIntegerValueForKey:(id)arg1;
- (id)xmp_safeStringValueForKey:(id)arg1;
- (id)xmp_jsonString;
@end

