//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (YYAdd)
+ (id)arrayWithPlistString:(id)arg1;
+ (id)arrayWithPlistData:(id)arg1;
- (void)shuffle;
- (void)reverse;
- (void)insertObjects:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)prependObjects:(id)arg1;
- (void)appendObjects:(id)arg1;
- (void)prependObject:(id)arg1;
- (void)appendObject:(id)arg1;
- (id)popLastObject;
- (id)popFirstObject;
- (void)removeLastObject;
- (void)removeFirstObject;
@end

