//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDLRPCNotification.h"

@class NSNumber, NSString, SDLFileType, SDLRequestType;

@interface SDLOnSystemRequest : SDLRPCNotification
{
}

@property(retain) NSNumber *length;
@property(retain) NSNumber *offset;
@property(retain) SDLFileType *fileType;
@property(retain) NSNumber *timeout;
@property(retain) NSString *url;
@property(retain) SDLRequestType *requestType;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

