//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDLAbstractTransport.h"

@class NSObject, NSString;
@protocol OS_dispatch_queue;

@interface SDLTCPTransport : SDLAbstractTransport
{
    struct __CFSocket *socket;
    _Bool _alreadyDestructed;
    NSObject<OS_dispatch_queue> *_sendQueue;
    NSString *_hostName;
    NSString *_portNumber;
}

@property(retain) NSString *portNumber; // @synthesize portNumber=_portNumber;
@property(retain) NSString *hostName; // @synthesize hostName=_hostName;
- (void).cxx_destruct;
- (void)dealloc;
- (void)dispose;
- (void)disconnect;
- (void)destructObjects;
- (void)sendData:(id)arg1;
- (void)connect;
- (id)init;

@end

