//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSMutableArray;

@interface UMSLNetworkWork : NSOperation
{
    NSMutableArray *_envelopeFilePaths;
}

@property(retain) NSMutableArray *envelopeFilePaths; // @synthesize envelopeFilePaths=_envelopeFilePaths;
- (void).cxx_destruct;
- (id)setupRequest:(id)arg1 withInfo:(id)arg2;
- (_Bool)postDataToServer:(id)arg1 withFile:(id)arg2;
- (_Bool)postDataWithFile:(id)arg1;
- (void)main;

@end

