//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableDictionary;

@interface UMSLEnvelopeBuild : NSObject
{
    NSData *_signature;
    NSData *_guid;
    int _timestamp;
    NSMutableDictionary *_header;
}

- (void).cxx_destruct;
- (id)buildEnvelopeWithHeader:(id)arg1 content:(id)arg2 pathURL:(id)arg3;
- (void)buildSLBaseheader:(id)arg1;
- (id)toEnvelopeWithEntity:(id)arg1 rawLen:(int)arg2 serNum:(int)arg3;
- (void)setSignatureWithData:(id)arg1 entityMD5:(char *)arg2;
- (void)buildGUIDWithData:(unsigned char [32])arg1 entityMD5:(char *)arg2;
- (id)mergeEntityAndIdentity:(char *)arg1;
- (id)init;

@end

