//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "XMMANativeMethodParamProtocol-Protocol.h"

@class NSString, XMMAUIComponentPosition;

@interface XAARCameraInsertParam : NSObject <XMMANativeMethodParamProtocol>
{
    _Bool _hide;
    NSString *_slaveId;
    NSString *_ARCameraId;
    NSString *_viewId;
    NSString *_parentId;
    NSString *_ARKey;
    NSString *_ARType;
    NSString *_flash;
    XMMAUIComponentPosition *_position;
}

@property(retain, nonatomic) XMMAUIComponentPosition *position; // @synthesize position=_position;
@property(copy, nonatomic) NSString *flash; // @synthesize flash=_flash;
@property(copy, nonatomic) NSString *ARType; // @synthesize ARType=_ARType;
@property(copy, nonatomic) NSString *ARKey; // @synthesize ARKey=_ARKey;
@property(nonatomic) _Bool hide; // @synthesize hide=_hide;
@property(copy, nonatomic) NSString *parentId; // @synthesize parentId=_parentId;
@property(copy, nonatomic) NSString *viewId; // @synthesize viewId=_viewId;
@property(copy, nonatomic) NSString *ARCameraId; // @synthesize ARCameraId=_ARCameraId;
@property(copy, nonatomic) NSString *slaveId; // @synthesize slaveId=_slaveId;
- (void).cxx_destruct;
- (_Bool)isValidate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

