//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMSubLevelViewController.h"

#import "XMActivityCellDelegate-Protocol.h"

@class NSMutableArray, NSString, XMServerRequest;

@interface XMActivityListViewController : XMSubLevelViewController <XMActivityCellDelegate>
{
    long long _pageId;
    long long _maxPageId;
    NSMutableArray *listDatas;
    XMServerRequest *listRequest;
}

@property(retain, nonatomic) XMServerRequest *listRequest; // @synthesize listRequest;
@property(retain, nonatomic) NSMutableArray *listDatas; // @synthesize listDatas;
- (void).cxx_destruct;
- (void)clickXMActivityCell:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)onReqestFailed:(id)arg1;
- (void)onRequestFinished:(id)arg1;
- (void)requestFromIndex:(long long)arg1;
- (void)triggerLoadMore;
- (_Bool)isLoadMoreViewNeeded;
- (void)triggerPullToRefresh;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)startDataLoad;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

