//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMCommentBaseCtrl.h"

#import "XMAlbumCommentCellDelegate-Protocol.h"
#import "XMAlbumCommentInputBarDelegate-Protocol.h"

@class NSMutableArray, NSNumber, NSString, XMAlbumComment, XMAlbumCommentInputBar, XMAlbumCommentInputCtrl, XMAlbumCommentUtility;

@interface XMAlbumCommentDetailCtrl : XMCommentBaseCtrl <XMAlbumCommentCellDelegate, XMAlbumCommentInputBarDelegate>
{
    _Bool _isPaid;
    unsigned long long _albumId;
    unsigned long long _commentId;
    CDUnknownBlockType _deleteCommentBlock;
    CDUnknownBlockType _updateCommentBlock;
    CDUnknownBlockType _createCommentDetailBlock;
    long long _totalCount;
    NSMutableArray *_topComments;
    NSMutableArray *_allComments;
    XMAlbumComment *_rootComment;
    XMAlbumCommentInputBar *_inputBar;
    XMAlbumCommentInputCtrl *_commentInputController;
    XMAlbumCommentUtility *_commentUtility;
    NSString *_noDataMessage;
    NSNumber *_xmubt_albumId;
    NSNumber *_xmubt_commentId;
    unsigned long long _commentDetailState;
}

@property(nonatomic) unsigned long long commentDetailState; // @synthesize commentDetailState=_commentDetailState;
@property(retain, nonatomic) NSNumber *xmubt_commentId; // @synthesize xmubt_commentId=_xmubt_commentId;
@property(retain, nonatomic) NSNumber *xmubt_albumId; // @synthesize xmubt_albumId=_xmubt_albumId;
@property(retain, nonatomic) NSString *noDataMessage; // @synthesize noDataMessage=_noDataMessage;
@property(retain, nonatomic) XMAlbumCommentUtility *commentUtility; // @synthesize commentUtility=_commentUtility;
@property(retain, nonatomic) XMAlbumCommentInputCtrl *commentInputController; // @synthesize commentInputController=_commentInputController;
@property(retain, nonatomic) XMAlbumCommentInputBar *inputBar; // @synthesize inputBar=_inputBar;
@property(retain, nonatomic) XMAlbumComment *rootComment; // @synthesize rootComment=_rootComment;
@property(retain, nonatomic) NSMutableArray *allComments; // @synthesize allComments=_allComments;
@property(retain, nonatomic) NSMutableArray *topComments; // @synthesize topComments=_topComments;
@property(nonatomic) long long totalCount; // @synthesize totalCount=_totalCount;
@property(copy, nonatomic) CDUnknownBlockType createCommentDetailBlock; // @synthesize createCommentDetailBlock=_createCommentDetailBlock;
@property(copy, nonatomic) CDUnknownBlockType updateCommentBlock; // @synthesize updateCommentBlock=_updateCommentBlock;
@property(copy, nonatomic) CDUnknownBlockType deleteCommentBlock; // @synthesize deleteCommentBlock=_deleteCommentBlock;
@property(nonatomic) _Bool isPaid; // @synthesize isPaid=_isPaid;
@property(nonatomic) unsigned long long commentId; // @synthesize commentId=_commentId;
@property(nonatomic) unsigned long long albumId; // @synthesize albumId=_albumId;
- (void).cxx_destruct;
- (_Bool)shouldShowEmptyView;
- (void)updateEmptyViewAndNoNetView;
- (void)viewDidLayoutSubviews;
- (void)inputCtrlPlaceHolderForReply;
- (id)sectionHeaderView:(id)arg1;
- (void)addRightButton;
- (void)updateCommentCount;
- (void)clickRightBarButton:(id)arg1;
- (id)footerView;
- (void)didRequestMoreData:(_Bool)arg1;
- (void)requestMoreData:(_Bool)arg1 showLoadingHud:(_Bool)arg2;
- (void)deleteCommentLocally:(id)arg1;
- (void)updateCommentLocally:(id)arg1;
- (void)requestDelete:(id)arg1;
- (void)requestLike:(id)arg1;
- (void)updateCommentInputView:(id)arg1 scoreAvailable:(_Bool)arg2;
- (void)checkScoreAvailable:(id)arg1;
- (void)createCommentDetailLocally:(id)arg1;
- (void)showCommentInputView:(id)arg1;
- (void)pushToNewReport:(id)arg1;
- (void)showCommentActionSheet:(id)arg1;
- (void)commentCellDidShowTalentInfo:(id)arg1;
- (void)commentCellDidTapMoreButton:(id)arg1;
- (void)commentCellDidTapTalentInfo:(id)arg1;
- (void)commentCellDidBeLongPressed:(id)arg1;
- (void)pushToUserProfile:(unsigned long long)arg1 name:(id)arg2;
- (void)commentCellDidTapAlbumCard:(id)arg1;
- (void)didSelecteCellWithLayout:(id)arg1 atIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)commentInputBarDidBeTapped:(id)arg1;
- (void)commentInputBarDidTappedLike:(id)arg1;
- (void)viewDidLoad;
- (void)didInitialize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSMutableArray *sectionArray; // @dynamic sectionArray;
@property(readonly) Class superclass;

@end

