//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XMBase/XMModel.h>

@class NSString;

@interface XMAnchorPromotionIncomeInfo : XMModel
{
    _Bool _showPromotionDialog;
    float _promotionIncome;
    unsigned long long _lastDaySharedNum;
    NSString *_linkUrl;
}

@property(nonatomic) _Bool showPromotionDialog; // @synthesize showPromotionDialog=_showPromotionDialog;
@property(retain, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(nonatomic) float promotionIncome; // @synthesize promotionIncome=_promotionIncome;
@property(nonatomic) unsigned long long lastDaySharedNum; // @synthesize lastDaySharedNum=_lastDaySharedNum;
- (void).cxx_destruct;

@end

