//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface XMChatHudHelper : NSObject
{
}

+ (id)viewForObject:(id)arg1;
+ (_Bool)isShowingLoadingHudInView:(id)arg1;
+ (_Bool)isShowingLoadingHudInInObject:(id)arg1;
+ (void)hideLoadingHudInView:(id)arg1;
+ (void)hideLoadingHudInObject:(id)arg1;
+ (void)showLoadingHudInView:(id)arg1;
+ (void)showLoadingHudInObject:(id)arg1;
+ (void)showToast:(id)arg1 inView:(id)arg2;
+ (void)showToast:(id)arg1 inObject:(id)arg2;
+ (void)showToast:(id)arg1;
+ (void)showErrorHud:(id)arg1 inObject:(id)arg2;
+ (void)showErrorHud:(id)arg1;

@end

