//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "XMCommentPanelSource-Protocol.h"

@class NSString, UIButton;

@interface XMCommentBottomDanmuPanelSource : NSObject <XMCommentPanelSource>
{
    _Bool _canBeSelected;
    id _delegate;
    UIButton *_bottomDanmuButton;
    CDUnknownBlockType _didBeDeselectedBlock;
    CDUnknownBlockType _didBeSelectedBlock;
    CDUnknownBlockType _viewDidTapBlock;
}

@property(nonatomic) _Bool canBeSelected; // @synthesize canBeSelected=_canBeSelected;
@property(copy, nonatomic) CDUnknownBlockType viewDidTapBlock; // @synthesize viewDidTapBlock=_viewDidTapBlock;
@property(copy, nonatomic) CDUnknownBlockType didBeSelectedBlock; // @synthesize didBeSelectedBlock=_didBeSelectedBlock;
@property(copy, nonatomic) CDUnknownBlockType didBeDeselectedBlock; // @synthesize didBeDeselectedBlock=_didBeDeselectedBlock;
@property(retain, nonatomic) UIButton *bottomDanmuButton; // @synthesize bottomDanmuButton=_bottomDanmuButton;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)panelView;
- (void)didBeDeselected;
- (void)didBeSelected;
- (_Bool)canSelected;
- (void)didBeTapped;
- (id)iconButton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

