//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMCommentBaseLayout.h"

@class XMCommentRecordNode;

@interface XMCommentRecordNodeViewLayout : XMCommentBaseLayout
{
    struct CGRect _backgroundImageViewFrame;
    struct CGRect _voiceIconImageViewFrame;
    struct CGRect _timeLabelFrame;
}

@property(nonatomic) struct CGRect timeLabelFrame; // @synthesize timeLabelFrame=_timeLabelFrame;
@property(nonatomic) struct CGRect voiceIconImageViewFrame; // @synthesize voiceIconImageViewFrame=_voiceIconImageViewFrame;
@property(nonatomic) struct CGRect backgroundImageViewFrame; // @synthesize backgroundImageViewFrame=_backgroundImageViewFrame;
- (struct CGSize)layout;
- (_Bool)isExpiredForSize:(struct CGSize)arg1 model:(id)arg2 config:(id)arg3;
- (id)initWithSize:(struct CGSize)arg1 model:(id)arg2 config:(id)arg3;

// Remaining properties
@property(readonly, nonatomic) XMCommentRecordNode *model;

@end

