//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UITableView;
@protocol XMCustomActionSheetDelegate;

@interface XMCustomActionSheet : UIView <UITableViewDataSource, UITableViewDelegate>
{
    long long _style;
    double _screenH;
    double _screenW;
    double _viewHeight;
    UIView *_blurEffectView;
    id <XMCustomActionSheetDelegate> _delegate;
    long long _selectedIndex;
    NSMutableArray *_listItems;
    UITableView *_tableView;
    NSString *_title;
    NSString *_closeTitle;
    UIView *_dimView;
}

@property(retain, nonatomic) UIView *dimView; // @synthesize dimView=_dimView;
@property(copy, nonatomic) NSString *closeTitle; // @synthesize closeTitle=_closeTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *listItems; // @synthesize listItems=_listItems;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) __weak id <XMCustomActionSheetDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onTapDimView;
- (void)onCloseButtonClicked;
- (void)dismissWithIndex:(long long)arg1;
- (void)showInView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)addItem:(id)arg1;
- (void)insertItem:(id)arg1 atIndex:(long long)arg2;
- (void)setupSubViews;
- (id)initWithStyle:(long long)arg1 title:(id)arg2 closeButtonTitle:(id)arg3 listItems:(id)arg4;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

