//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XMBase/XMModel.h>

@class NSString, NSURL;

@interface XMDubShowMSSearchRecommendCellModel : XMModel
{
    _Bool _isNew;
    _Bool _isHot;
    _Bool _isDefault;
    _Bool _isLink;
    long long _titleId;
    NSString *_title;
    NSURL *_linkUrl;
}

+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) NSURL *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(nonatomic) _Bool isLink; // @synthesize isLink=_isLink;
@property(nonatomic) _Bool isDefault; // @synthesize isDefault=_isDefault;
@property(nonatomic) _Bool isHot; // @synthesize isHot=_isHot;
@property(nonatomic) _Bool isNew; // @synthesize isNew=_isNew;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long titleId; // @synthesize titleId=_titleId;
- (void).cxx_destruct;

@end

