//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSRegularExpression, UIButton, UIImageView, UILabel, XMDubShowMaterialSquareSearchModel, XMWebImageView;

@interface XMDubShowMaterialSquareSearchCell : UICollectionViewCell
{
    XMDubShowMaterialSquareSearchModel *_model;
    CDUnknownBlockType _handlePlayButtonAction;
    XMWebImageView *_imgView;
    UILabel *_titleL;
    UILabel *_subTitle;
    UIImageView *_typeImageView;
    UILabel *_lengthLabel;
    UIButton *_playButton;
    UILabel *_tagLabel;
    NSRegularExpression *_regular;
}

@property(retain, nonatomic) NSRegularExpression *regular; // @synthesize regular=_regular;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) UILabel *lengthLabel; // @synthesize lengthLabel=_lengthLabel;
@property(retain, nonatomic) UIImageView *typeImageView; // @synthesize typeImageView=_typeImageView;
@property(retain, nonatomic) UILabel *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) UILabel *titleL; // @synthesize titleL=_titleL;
@property(retain, nonatomic) XMWebImageView *imgView; // @synthesize imgView=_imgView;
@property(copy, nonatomic) CDUnknownBlockType handlePlayButtonAction; // @synthesize handlePlayButtonAction=_handlePlayButtonAction;
@property(retain, nonatomic) XMDubShowMaterialSquareSearchModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)markedAttributedTextWithText:(id)arg1 font:(id)arg2 textColor:(id)arg3;
- (void)p_handlePlayAction;
- (void)setupView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

