//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMBaseViewController.h"

#import "XMFindTabToolViewDelegate-Protocol.h"
#import "XMSegmentTabViewCtrolDelegate-Protocol.h"

@class CAShapeLayer, LOTAnimationView, NSArray, NSMutableArray, NSMutableDictionary, NSString, UIView, UIViewController, XMAccidentTipsView, XMFindFliterItem, XMFindTabThemeModel, XMFindTabToolView, XMHitTestView, XMMPMBannerView, XMNRequest, XMNewUserGiftAlertManager, XMSegmentControl, XMSegmentTabViewController;

@interface XMFindTopViewController : XMBaseViewController <XMSegmentTabViewCtrolDelegate, XMFindTabToolViewDelegate>
{
    _Bool _isFirstEnter;
    UIView *_networRemindView;
    _Bool _showListenRedDot;
    _Bool _isFirstPostStatDataForCurrentCtr;
    _Bool _needToReload;
    _Bool _inReview;
    _Bool _isShowUserGift;
    _Bool _isOnMPM;
    _Bool _lastLocationTab;
    XMNRequest *_tabReq;
    NSString *_listenBadgeValue;
    NSArray *_displayTabModels;
    NSArray *_categoryEditModels;
    XMSegmentTabViewController *_tabController;
    CAShapeLayer *_shapeLayer;
    XMSegmentControl *_segControl;
    XMHitTestView *_headerView;
    XMMPMBannerView *_mpmHeaderView;
    UIView *_maskView;
    XMFindTabToolView *_tooView;
    LOTAnimationView *_catAniView;
    UIView *_gradView;
    UIView *_dropDownAdView;
    NSMutableDictionary *_cacheTabVc;
    double _enterBackgroundTime;
    XMNRequest *_searchRecReq;
    XMNewUserGiftAlertManager *_giftAlertMng;
    XMFindFliterItem *_downloadItem;
    UIView *_listenRedDotView;
    UIViewController *_preVc;
    XMAccidentTipsView *_accTipsView;
    NSMutableArray *_tipsArray;
    NSString *_userGiftPic;
    NSString *_userGiftLink;
    XMFindTabThemeModel *_specialThemeModel;
    NSString *_specialHeaderColor;
    NSString *_specialTabTheme;
}

@property(nonatomic) _Bool lastLocationTab; // @synthesize lastLocationTab=_lastLocationTab;
@property(nonatomic) _Bool isOnMPM; // @synthesize isOnMPM=_isOnMPM;
@property(copy, nonatomic) NSString *specialTabTheme; // @synthesize specialTabTheme=_specialTabTheme;
@property(copy, nonatomic) NSString *specialHeaderColor; // @synthesize specialHeaderColor=_specialHeaderColor;
@property(retain, nonatomic) XMFindTabThemeModel *specialThemeModel; // @synthesize specialThemeModel=_specialThemeModel;
@property(copy, nonatomic) NSString *userGiftLink; // @synthesize userGiftLink=_userGiftLink;
@property(copy, nonatomic) NSString *userGiftPic; // @synthesize userGiftPic=_userGiftPic;
@property(nonatomic) _Bool isShowUserGift; // @synthesize isShowUserGift=_isShowUserGift;
@property(retain, nonatomic) NSMutableArray *tipsArray; // @synthesize tipsArray=_tipsArray;
@property(retain, nonatomic) XMAccidentTipsView *accTipsView; // @synthesize accTipsView=_accTipsView;
@property(nonatomic) __weak UIViewController *preVc; // @synthesize preVc=_preVc;
@property(retain, nonatomic) UIView *listenRedDotView; // @synthesize listenRedDotView=_listenRedDotView;
@property(nonatomic) __weak XMFindFliterItem *downloadItem; // @synthesize downloadItem=_downloadItem;
@property(retain, nonatomic) XMNewUserGiftAlertManager *giftAlertMng; // @synthesize giftAlertMng=_giftAlertMng;
@property(retain, nonatomic) XMNRequest *searchRecReq; // @synthesize searchRecReq=_searchRecReq;
@property(nonatomic) _Bool inReview; // @synthesize inReview=_inReview;
@property(nonatomic) double enterBackgroundTime; // @synthesize enterBackgroundTime=_enterBackgroundTime;
@property(retain, nonatomic) NSMutableDictionary *cacheTabVc; // @synthesize cacheTabVc=_cacheTabVc;
@property(retain, nonatomic) UIView *dropDownAdView; // @synthesize dropDownAdView=_dropDownAdView;
@property(retain, nonatomic) UIView *gradView; // @synthesize gradView=_gradView;
@property(retain, nonatomic) LOTAnimationView *catAniView; // @synthesize catAniView=_catAniView;
@property(retain, nonatomic) XMFindTabToolView *tooView; // @synthesize tooView=_tooView;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) XMMPMBannerView *mpmHeaderView; // @synthesize mpmHeaderView=_mpmHeaderView;
@property(retain, nonatomic) XMHitTestView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) _Bool needToReload; // @synthesize needToReload=_needToReload;
@property(retain, nonatomic) XMSegmentControl *segControl; // @synthesize segControl=_segControl;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(nonatomic) _Bool isFirstPostStatDataForCurrentCtr; // @synthesize isFirstPostStatDataForCurrentCtr=_isFirstPostStatDataForCurrentCtr;
@property(retain, nonatomic) XMSegmentTabViewController *tabController; // @synthesize tabController=_tabController;
@property(retain, nonatomic) NSArray *categoryEditModels; // @synthesize categoryEditModels=_categoryEditModels;
@property(retain, nonatomic) NSArray *displayTabModels; // @synthesize displayTabModels=_displayTabModels;
@property(copy, nonatomic) NSString *listenBadgeValue; // @synthesize listenBadgeValue=_listenBadgeValue;
@property(nonatomic) _Bool showListenRedDot; // @synthesize showListenRedDot=_showListenRedDot;
@property(retain, nonatomic) XMNRequest *tabReq; // @synthesize tabReq=_tabReq;
- (void).cxx_destruct;
- (_Bool)isDarkStyle;
- (void)updateShapeLayerColor;
- (void)traitCollectionDidChange:(id)arg1;
- (void)showKingCardRemind;
- (void)setTopViewWithAlpha:(double)arg1;
- (void)updateHeaderAlphaIfNeeded;
- (void)fetchHotWordsWithCategoryId:(long long)arg1;
- (void)observePageScorllProgress;
- (void)adModuleDidUpdateAdOnVc:(id)arg1 withAdModels:(id)arg2 andPositionName:(id)arg3 andAdType:(long long)arg4;
- (void)updateRecCustomTheme;
- (void)changeColorForStyle:(unsigned long long)arg1 fromLive:(_Bool)arg2 tabTheme:(id)arg3 absorbedColor:(id)arg4;
- (void)changeThemeColorWith:(id)arg1 tabModel:(id)arg2;
- (void)onAVDownloadUnDownloadedListChange;
- (void)showNetworkHelp;
- (id)networRemindView;
- (void)updteTopRemindView;
- (void)onNetworkDidChangedNotification;
- (void)checkNetworkReachability;
- (double)maxOffsetYChangeWhiteStyleWithVC:(id)arg1;
- (id)viewControllerWithTabModel:(id)arg1;
- (void)postStatDataForCurrentCtr:(id)arg1;
- (void)postTransitionToModel:(id)arg1 position:(long long)arg2;
- (void)segmentCtrolScrollToRightEdges;
- (void)segmentCtrol:(id)arg1 transitionAtController:(id)arg2;
- (id)segmentCtrol:(id)arg1 controllerAtIndex:(long long)arg2;
- (id)segmentCtrolTitles:(id)arg1;
- (void)goToSpecifcTab:(id)arg1;
- (void)goToLiveHomeTab;
- (void)onGotRemoteSettings;
- (void)onCityChanged;
- (void)appDidEnterBackground;
- (void)appWillEnterForeground;
- (void)liveDropViewDidClickMyLive:(id)arg1;
- (void)liveDropViewDidClickStartLive:(id)arg1;
- (void)findTabToolViewDidClickMyLiveCenter;
- (void)findTabToolViewDidClickStartLive:(id)arg1;
- (void)findTabToolViewDidClickMic:(id)arg1;
- (void)findTabToolViewDidClickHistory;
- (void)gotoDownload;
- (void)gotoRecord;
- (void)findTabToolViewDidClickAdd:(id)arg1;
- (void)findTabToolViewDidClickMetadataWithModel:(id)arg1 Index:(long long)arg2;
- (void)findTabToolViewDidClickItingWithModel:(id)arg1;
- (void)findTabToolViewDidClickSearch:(id)arg1;
- (void)editButtonDidClick;
- (void)checkToShowSegControlTipsOrNewerGift;
- (void)updateListenRedDot;
- (void)updateUbtWithTab;
- (void)updateSegControlWithDownLoadTabImages:(id)arg1;
- (void)reloadSegmentControl;
- (void)updateTabsAndVCs;
- (id)processDisplayTabModls:(id)arg1;
- (void)p_updateMPMStatus;
- (void)setupHeaderView;
- (void)setupShapeLayer;
- (void)setupSegmentTabVCWithDefaultIndex:(long long)arg1;
- (void)fetchRectentAllTabsLocatedDefault:(_Bool)arg1 needRecTab:(_Bool)arg2 interestCategorys:(id)arg3;
- (id)currentSelectedTabClassName;
- (void)pullToRefresh;
- (void)checkForListenContinue;
- (void)updateBadgeValue:(id)arg1;
- (void)checkForUpdate;
- (void)setupMaskView;
- (void)checkToPlayAnimation;
- (void)p_syncMPMHomeTab;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (_Bool)navigationBarBottomLineHidden;
- (void)dealloc;
- (id)cachedFindTabGroups;
- (id)findTabCacheDirectory;
- (void)parseCategoriesJSON:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)fetchFindTabModelWithCustomTabIDs:(id)arg1 needRecTab:(_Bool)arg2 excludeItemTypes:(id)arg3 includeItemTypes:(id)arg4 interestCategorys:(id)arg5 modifyCompleteHandler:(CDUnknownBlockType)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

