//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel, XMGroupCheckinInfo, XMWebImageView;

@interface XMGroupTalkSignInEntranceView : UIView
{
    XMGroupCheckinInfo *_checkinInfo;
    UIView *_underlyingView;
    XMWebImageView *_headImageView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    UIButton *_nextButton;
}

@property(retain, nonatomic) UIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) XMWebImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) UIView *underlyingView; // @synthesize underlyingView=_underlyingView;
@property(retain, nonatomic) XMGroupCheckinInfo *checkinInfo; // @synthesize checkinInfo=_checkinInfo;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)updateNextButton;
- (void)didInitialize;
- (id)initWithFrame:(struct CGRect)arg1;

@end

