//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, XMLiveChatFansCard;

@interface XMLiveChatUserInfo : NSObject
{
    int _level;
    int _bubbleType;
    int _hangerType;
    unsigned long long _userId;
    NSString *_nickName;
    NSArray *_tagsArray;
    XMLiveChatFansCard *_fansCard;
}

@property(nonatomic) int hangerType; // @synthesize hangerType=_hangerType;
@property(nonatomic) int bubbleType; // @synthesize bubbleType=_bubbleType;
@property(retain, nonatomic) XMLiveChatFansCard *fansCard; // @synthesize fansCard=_fansCard;
@property(nonatomic) int level; // @synthesize level=_level;
@property(copy, nonatomic) NSArray *tagsArray; // @synthesize tagsArray=_tagsArray;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (id)description;

@end

