//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMBaseTabelVC.h"

@class NSArray, NSDictionary, NSURL, UIButton;

@interface XMLivePersonalCenterVC : XMBaseTabelVC
{
    NSArray *_dataArray;
    NSArray *_defaultImgs;
    UIButton *_rightBtn;
    NSURL *_markUrl;
    NSDictionary *_configDic;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *configDic; // @synthesize configDic=_configDic;
@property(retain, nonatomic) NSURL *markUrl; // @synthesize markUrl=_markUrl;
@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) NSArray *defaultImgs; // @synthesize defaultImgs=_defaultImgs;
@property(retain, nonatomic) NSArray *dataArray; // @synthesize dataArray=_dataArray;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)addRightBtn;
- (void)onRightBtnClick;
- (void)didReceiveDailyMarkNotification:(id)arg1;
- (void)updateDataArray:(id)arg1;
- (void)requestData;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

