//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMLiveBaseCustomAlert.h"

@class NSString, UIButton, UILabel, XMWebImageView;

@interface XMLiveEntSeatWidgetAlertView : XMLiveBaseCustomAlert
{
    long long _localTemplateId;
    NSString *_itemTitle;
    NSString *_itemDesc;
    XMWebImageView *_itemImageView;
    UILabel *_itemTitleLabel;
    UILabel *_itemDescLabel;
    UIButton *_actionBtn;
    UIButton *_closeBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) UIButton *actionBtn; // @synthesize actionBtn=_actionBtn;
@property(retain, nonatomic) UILabel *itemDescLabel; // @synthesize itemDescLabel=_itemDescLabel;
@property(retain, nonatomic) UILabel *itemTitleLabel; // @synthesize itemTitleLabel=_itemTitleLabel;
@property(retain, nonatomic) XMWebImageView *itemImageView; // @synthesize itemImageView=_itemImageView;
@property(copy, nonatomic) NSString *itemDesc; // @synthesize itemDesc=_itemDesc;
@property(copy, nonatomic) NSString *itemTitle; // @synthesize itemTitle=_itemTitle;
@property(nonatomic) long long localTemplateId; // @synthesize localTemplateId=_localTemplateId;
- (void)showAlert;
- (void)onClose;
- (void)onAction;
- (void)baseInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

