//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, UILabel, XMWebImageButton, XMWebImageView;

@interface XMLiveNobleHeaderView : UIView
{
    UIColor *_textColor;
    CDUnknownBlockType _selectedBlock;
    UILabel *_secondNobleName;
    XMWebImageButton *_secondNobleBtn;
    XMWebImageView *_secondIcon;
    UILabel *_firstNobleName;
    XMWebImageButton *_firstNobleBtn;
    XMWebImageView *_firstIcon;
    UILabel *_thirdNobleName;
    XMWebImageButton *_thirdNobleBtn;
    XMWebImageView *_thirdIcon;
}

- (void).cxx_destruct;
@property(retain, nonatomic) XMWebImageView *thirdIcon; // @synthesize thirdIcon=_thirdIcon;
@property(retain, nonatomic) XMWebImageButton *thirdNobleBtn; // @synthesize thirdNobleBtn=_thirdNobleBtn;
@property(retain, nonatomic) UILabel *thirdNobleName; // @synthesize thirdNobleName=_thirdNobleName;
@property(retain, nonatomic) XMWebImageView *firstIcon; // @synthesize firstIcon=_firstIcon;
@property(retain, nonatomic) XMWebImageButton *firstNobleBtn; // @synthesize firstNobleBtn=_firstNobleBtn;
@property(retain, nonatomic) UILabel *firstNobleName; // @synthesize firstNobleName=_firstNobleName;
@property(retain, nonatomic) XMWebImageView *secondIcon; // @synthesize secondIcon=_secondIcon;
@property(retain, nonatomic) XMWebImageButton *secondNobleBtn; // @synthesize secondNobleBtn=_secondNobleBtn;
@property(retain, nonatomic) UILabel *secondNobleName; // @synthesize secondNobleName=_secondNobleName;
@property(copy, nonatomic) CDUnknownBlockType selectedBlock; // @synthesize selectedBlock=_selectedBlock;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
- (void)refreshNobleContent:(id)arg1;
- (void)onNobleAvatarDidClick:(id)arg1;
- (void)addSubviewConstrants;
- (void)createSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

