//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XMBase/XMModel.h>

#import "XMTableCellModelProtocol-Protocol.h"

@class NSString;

@interface XMMarkTrackItem : XMModel <XMTableCellModelProtocol>
{
    _Bool _isDeleteMode;
    _Bool _isSelected;
    long long _trackId;
    long long _uid;
    long long _markId;
    long long _markTime;
}

+ (id)xmm_modelCustomPropertyMapper;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(nonatomic) _Bool isDeleteMode; // @synthesize isDeleteMode=_isDeleteMode;
@property(nonatomic) long long markTime; // @synthesize markTime=_markTime;
@property(nonatomic) long long markId; // @synthesize markId=_markId;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
@property(nonatomic) long long trackId; // @synthesize trackId=_trackId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

