//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMSubLevelViewController.h"

#import "XMActionSheetViewDelegate-Protocol.h"
#import "XMProgrameHeaderViewDelegate-Protocol.h"
#import "XMRecordAlbumBuildDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, XMActionSheetView, XMAnchorDeskMissionInfo, XMAnchorValueInfo, XMMeCenterInfo, XMProgrameHeaderView, XMServerPostRequest, XMServerRequest;

@interface XMMeCenterViewController : XMSubLevelViewController <XMActionSheetViewDelegate, XMProgrameHeaderViewDelegate, XMRecordAlbumBuildDelegate>
{
    long long _rewardstate;
    _Bool _isAfterGettingReward;
    _Bool _showCopyRightClaim;
    long long _albumCount;
    XMMeCenterInfo *_centerInfo;
    NSMutableArray *_dataArray;
    long long _pendingViolationCount;
    XMServerRequest *_stateRequest;
    XMActionSheetView *_actionSheet;
    XMProgrameHeaderView *_headView;
    NSMutableArray *_announceMArr;
    NSArray *_anchorManualItems;
    NSArray *_anchorPromotionItems;
    NSArray *_anchorOperationItems;
    XMAnchorDeskMissionInfo *_anchorMissionInfo;
    XMAnchorValueInfo *_anchorValueInfo;
    XMServerPostRequest *_getRewardRequest;
    unsigned long long _uidForUBT;
}

@property(nonatomic) _Bool showCopyRightClaim; // @synthesize showCopyRightClaim=_showCopyRightClaim;
@property(nonatomic) unsigned long long uidForUBT; // @synthesize uidForUBT=_uidForUBT;
@property(nonatomic) _Bool isAfterGettingReward; // @synthesize isAfterGettingReward=_isAfterGettingReward;
@property(retain, nonatomic) XMServerPostRequest *getRewardRequest; // @synthesize getRewardRequest=_getRewardRequest;
@property(retain, nonatomic) XMAnchorValueInfo *anchorValueInfo; // @synthesize anchorValueInfo=_anchorValueInfo;
@property(retain, nonatomic) XMAnchorDeskMissionInfo *anchorMissionInfo; // @synthesize anchorMissionInfo=_anchorMissionInfo;
@property(retain, nonatomic) NSArray *anchorOperationItems; // @synthesize anchorOperationItems=_anchorOperationItems;
@property(retain, nonatomic) NSArray *anchorPromotionItems; // @synthesize anchorPromotionItems=_anchorPromotionItems;
@property(retain, nonatomic) NSArray *anchorManualItems; // @synthesize anchorManualItems=_anchorManualItems;
@property(retain, nonatomic) NSMutableArray *announceMArr; // @synthesize announceMArr=_announceMArr;
@property(retain, nonatomic) XMProgrameHeaderView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) XMActionSheetView *actionSheet; // @synthesize actionSheet=_actionSheet;
@property(retain, nonatomic) XMServerRequest *stateRequest; // @synthesize stateRequest=_stateRequest;
@property(nonatomic) long long pendingViolationCount; // @synthesize pendingViolationCount=_pendingViolationCount;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) XMMeCenterInfo *centerInfo; // @synthesize centerInfo=_centerInfo;
@property(nonatomic) long long albumCount; // @synthesize albumCount=_albumCount;
- (void).cxx_destruct;
- (void)addMyCenterQAModule;
- (void)addMyCenterAlbumModule;
- (void)removeRedDotFromCell:(id)arg1;
- (void)addRedDotWithCell:(id)arg1;
- (void)updateDetailsForCell:(id)arg1;
- (void)gotoMyIncome;
- (void)gotoGanhuoShare;
- (void)openurl:(id)arg1;
- (void)openAnchorPromotionWithDict:(id)arg1;
- (void)openAnchorManualWithDict:(id)arg1;
- (void)headerGotoMessageCenter;
- (void)headerGoToSelfPromotionPage;
- (void)headerGotoAchievementPage;
- (void)headerOpenUserHomePage;
- (void)headerGoToIncomePage;
- (void)headerGoToDataCenterPageWithType:(id)arg1;
- (void)headerGoToSubscriptionPage;
- (void)headerGoToPlayNumPage;
- (void)headerGoToTaskList;
- (void)headerGoToTaskWithInfo:(id)arg1;
- (void)headerGoToVerify;
- (void)actionSheetDismiss:(id)arg1;
- (void)buildAlbumSuccess:(id)arg1;
- (void)gotoBuildAlbum;
- (void)gotoRecord;
- (void)onAdd;
- (void)reloadPage;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)needShowAnchorRankingChangeAlertView:(id)arg1;
- (void)popUpRewardGottenViewWithScore:(long long)arg1;
- (void)getRewardWithInfo:(id)arg1;
- (void)anchorTitleCancel;
- (void)anchorTitleConfirm:(long long)arg1;
- (void)onFailed:(id)arg1;
- (void)onFinished:(id)arg1;
- (void)requestState;
- (void)didReceiveMemoryWarning;
- (void)onLoggedIn;
- (void)customInit4MeCenter;
- (void)triggerPullToRefresh;
- (void)viewDidAppear:(_Bool)arg1;
- (void)operationButtonClicked;
- (void)updateRightGifButton;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

