//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMLiveDraggablePopView.h"

@class UIViewController, XMLiveBGMControlPanel;

@interface XMMicMusicControlView : XMLiveDraggablePopView
{
    long long _liveId;
    UIViewController *_attachCtrl;
    XMLiveBGMControlPanel *_bgmPanel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) XMLiveBGMControlPanel *bgmPanel; // @synthesize bgmPanel=_bgmPanel;
@property(nonatomic) __weak UIViewController *attachCtrl; // @synthesize attachCtrl=_attachCtrl;
@property(nonatomic) long long liveId; // @synthesize liveId=_liveId;
- (id)draggableTitle;
- (void)showWithAnimate:(_Bool)arg1;
- (void)initCustomView;
- (id)initPopFromView:(id)arg1;
- (void)dealloc;

@end

