//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@interface XMMMenuItemLayout : NSObject <NSCopying>
{
    _Bool _imageTopAligned;
    double _l_image;
    double _image_titleArea;
    double _titleArea_tailArea;
    double _tailArea_r;
    double _titleSpace;
    double _tailSpace;
    double _l_line;
    double _line_r;
    double _line_h;
    struct CGSize _maxImageSize;
    struct CGSize _maxTailImageSize;
}

@property(nonatomic) double line_h; // @synthesize line_h=_line_h;
@property(nonatomic) double line_r; // @synthesize line_r=_line_r;
@property(nonatomic) double l_line; // @synthesize l_line=_l_line;
@property(nonatomic) struct CGSize maxTailImageSize; // @synthesize maxTailImageSize=_maxTailImageSize;
@property(nonatomic) struct CGSize maxImageSize; // @synthesize maxImageSize=_maxImageSize;
@property(nonatomic) double tailSpace; // @synthesize tailSpace=_tailSpace;
@property(nonatomic) double titleSpace; // @synthesize titleSpace=_titleSpace;
@property(nonatomic) double tailArea_r; // @synthesize tailArea_r=_tailArea_r;
@property(nonatomic) double titleArea_tailArea; // @synthesize titleArea_tailArea=_titleArea_tailArea;
@property(nonatomic) double image_titleArea; // @synthesize image_titleArea=_image_titleArea;
@property(nonatomic) double l_image; // @synthesize l_image=_l_image;
@property(nonatomic) _Bool imageTopAligned; // @synthesize imageTopAligned=_imageTopAligned;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

