//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface XMMomentVideoNetworkUtils : NSObject
{
    _Bool _videoTaskFinishLock;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shareInstance;
- (void)requestVideoTaskProgress;
- (void)reportVideoTaskFinish:(id)arg1;
- (void)reportMomentVideoStatistic:(id)arg1;
- (id)videoOnlineStatisticDictForMomentVideo:(id)arg1;
- (id)v2Signature:(id)arg1;
- (id)videoOnlineStatisticDictForDubShowVideo:(id)arg1;
- (id)videoOnlineStatisticDictForVideo:(id)arg1;
- (long long)playSourceCodeWithSource:(unsigned long long)arg1;
- (long long)playModeCodeWithSource:(unsigned long long)arg1;
- (void)onPostVideoOnlineStatisticFailedSelector:(id)arg1;
- (void)onPostVideoOnlineStatisticFinishedSelector:(id)arg1;
- (void)reportVideoOnlineStatistic:(id)arg1;
- (void)onPostVideoListenedCountFailedSelector:(id)arg1;
- (void)onPostVideoListenedCountFinishedSelector:(id)arg1;
- (void)postVideoListenedCount:(id)arg1;
- (void)onVideoNonceFailedSelector:(id)arg1;
- (void)onVideoNonceFinishedSelector:(id)arg1;
- (void)reportVideoListenedCount:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

