//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel, XMMShareExtendItem;

@interface XMMShareExtendCell : UICollectionViewCell
{
    XMMShareExtendItem *_item;
    UIImageView *_coverImage;
    UILabel *_titleLabel;
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *coverImage; // @synthesize coverImage=_coverImage;
@property(retain, nonatomic) XMMShareExtendItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)setupUnits;
- (id)initWithFrame:(struct CGRect)arg1;

@end

