//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMChatSlideVC.h"

@class NSArray, NSMutableSet, UIButton, UIImage, XMMFeedAddMenu, XMMHoverButton, XMMomentTopic, XMMomentTopicDetailView, XMSegmentControl, XMTopicDetailsViewController;

@interface XMMTopicPagesVC : XMChatSlideVC
{
    _Bool _showRelatedCommunities;
    _Bool _isWhiteBackButton;
    unsigned long long _topicId;
    unsigned long long _fromCommunityId;
    XMMomentTopic *_topicInfo;
    NSArray *_communityTopicChangeIds;
    XMTopicDetailsViewController *_allVC;
    XMTopicDetailsViewController *_hotVC;
    XMTopicDetailsViewController *_timeVC;
    XMMomentTopicDetailView *_topicDetailView;
    XMMHoverButton *_postButton;
    UIButton *_editButton;
    UIImage *_whiteEditImage;
    UIImage *_blackEditImage;
    XMSegmentControl *_segmentedControl;
    double _lastPos;
    NSMutableSet *_hasRefreshedTopicIdSet;
    XMMFeedAddMenu *_feedAddMenu;
}

@property(retain, nonatomic) XMMFeedAddMenu *feedAddMenu; // @synthesize feedAddMenu=_feedAddMenu;
@property(retain, nonatomic) NSMutableSet *hasRefreshedTopicIdSet; // @synthesize hasRefreshedTopicIdSet=_hasRefreshedTopicIdSet;
@property(nonatomic) double lastPos; // @synthesize lastPos=_lastPos;
@property(nonatomic) _Bool isWhiteBackButton; // @synthesize isWhiteBackButton=_isWhiteBackButton;
@property(retain, nonatomic) XMSegmentControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(retain, nonatomic) UIImage *blackEditImage; // @synthesize blackEditImage=_blackEditImage;
@property(retain, nonatomic) UIImage *whiteEditImage; // @synthesize whiteEditImage=_whiteEditImage;
@property(retain, nonatomic) UIButton *editButton; // @synthesize editButton=_editButton;
@property(retain, nonatomic) XMMHoverButton *postButton; // @synthesize postButton=_postButton;
@property(retain, nonatomic) XMMomentTopicDetailView *topicDetailView; // @synthesize topicDetailView=_topicDetailView;
@property(retain, nonatomic) XMTopicDetailsViewController *timeVC; // @synthesize timeVC=_timeVC;
@property(retain, nonatomic) XMTopicDetailsViewController *hotVC; // @synthesize hotVC=_hotVC;
@property(retain, nonatomic) XMTopicDetailsViewController *allVC; // @synthesize allVC=_allVC;
@property(retain, nonatomic) NSArray *communityTopicChangeIds; // @synthesize communityTopicChangeIds=_communityTopicChangeIds;
@property(retain, nonatomic) XMMomentTopic *topicInfo; // @synthesize topicInfo=_topicInfo;
@property(nonatomic) _Bool showRelatedCommunities; // @synthesize showRelatedCommunities=_showRelatedCommunities;
@property(nonatomic) unsigned long long fromCommunityId; // @synthesize fromCommunityId=_fromCommunityId;
@property(readonly, nonatomic) unsigned long long topicId; // @synthesize topicId=_topicId;
- (void).cxx_destruct;
- (id)newDynamicPushVC;
- (void)publishVideoNonstopCapture:(_Bool)arg1;
- (void)feedAddMenuShootItemAction:(id)arg1;
- (void)feedAddMenuTrackItemAction:(id)arg1;
- (void)feedAddMenuReciteItemAction:(id)arg1;
- (void)feedAddMenuArticleItemAction:(id)arg1;
- (void)feedAddMenuRecordItemAction:(id)arg1;
- (void)feedAddMenuDubShowItemAction:(id)arg1;
- (void)feedAddMenuVideoItemAction:(id)arg1;
- (void)feedAddMenuPicItemAction:(id)arg1;
- (void)prepareFeedAddMenuWithAllowedTypes:(id)arg1;
- (_Bool)isOnlyTrackItemOfStringArray:(id)arg1;
- (void)checkVideoAuthority;
- (void)requestMomentList;
- (void)requestTopicDetail;
- (void)updatePostButtonOffset;
- (id)xmubt_model;
- (void)requestFollow:(_Bool)arg1;
- (void)updateMyNavigationBar:(_Bool)arg1;
- (void)updateSegmentedControlStyle;
- (id)currentController;
- (void)slideView:(id)arg1 isDraggingToPage:(long long)arg2 progress:(double)arg3;
- (void)slideView:(id)arg1 isScrolling:(double)arg2;
- (void)slideView:(id)arg1 didScrollToPage:(long long)arg2;
- (void)slideView:(id)arg1 willScrollToPage:(long long)arg2;
- (void)topicDetailViewDidTapAuthorLabel:(id)arg1;
- (void)topicDetailView:(id)arg1 didTapCommunity:(id)arg2;
- (void)topicDetailViewDidTapRefreshButton:(id)arg1;
- (void)topicDetailViewDidTapFollowButton:(id)arg1;
- (void)topicDetailViewDidTapITingButton:(id)arg1;
- (void)topicDetailViewDidTapExpendButton:(id)arg1;
- (void)receiveDidExitCommuintyNotification:(id)arg1;
- (void)receiveDidJoinCommuintyNotification:(id)arg1;
- (void)receiveStatusSynchronizationNotification:(id)arg1;
- (void)logoutSuccessNotification:(id)arg1;
- (void)loginSuccessNotification:(id)arg1;
- (void)clickRefreshButton;
- (void)clickPostButton:(id)arg1;
- (void)clickEditButton:(id)arg1;
- (void)clickRightButton:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)didInitialize;
- (id)initWithTopicId:(unsigned long long)arg1;

@end

