//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMSubLevelViewController.h"

#import "XMActionSheetViewDelegate-Protocol.h"
#import "XMAlbumUserCellDelegate-Protocol.h"
#import "XMFloatTipViewDelegate-Protocol.h"
#import "XMNoDataTableViewCellDelegate-Protocol.h"
#import "XMRecordAlbumBuildDelegate-Protocol.h"

@class MBProgressHUD, NSMutableArray, NSString, XMActionSheetView, XMServerPostRequest, XMServerRequest;

@interface XMMyAllAlbumViewController : XMSubLevelViewController <XMActionSheetViewDelegate, XMNoDataTableViewCellDelegate, XMAlbumUserCellDelegate, XMRecordAlbumBuildDelegate, XMFloatTipViewDelegate>
{
    long long _albumTotalCount;
    long long _trackTotalCount;
    long long _dubTrackUploadCount;
    _Bool _isShowDubTrack;
    long long _pageId_album;
    long long _maxPageId_album;
    _Bool _isShowKacha;
    long long _kachaTotalCount;
    _Bool _hiddenSound;
    _Bool _hasEverReqResponse;
    _Bool _needToCheck;
    XMServerRequest *albumRequest;
    CDUnknownBlockType _didSelecCell;
    NSMutableArray *_albumList;
    XMActionSheetView *_sheetView;
    long long _selectedRow;
    MBProgressHUD *_myHud;
    XMServerPostRequest *_deleteAlbumRequest;
}

@property(nonatomic) _Bool needToCheck; // @synthesize needToCheck=_needToCheck;
@property(retain, nonatomic) XMServerPostRequest *deleteAlbumRequest; // @synthesize deleteAlbumRequest=_deleteAlbumRequest;
@property(retain, nonatomic) MBProgressHUD *myHud; // @synthesize myHud=_myHud;
@property(nonatomic) long long selectedRow; // @synthesize selectedRow=_selectedRow;
@property(retain, nonatomic) XMActionSheetView *sheetView; // @synthesize sheetView=_sheetView;
@property(nonatomic) _Bool hasEverReqResponse; // @synthesize hasEverReqResponse=_hasEverReqResponse;
@property(retain, nonatomic) NSMutableArray *albumList; // @synthesize albumList=_albumList;
@property(copy, nonatomic) CDUnknownBlockType didSelecCell; // @synthesize didSelecCell=_didSelecCell;
@property(nonatomic) _Bool hiddenSound; // @synthesize hiddenSound=_hiddenSound;
@property(retain, nonatomic) XMServerRequest *albumRequest; // @synthesize albumRequest;
- (void).cxx_destruct;
- (void)gotoDubshowSounds;
- (void)gotoRecordSounds;
- (void)gotoMyVideos;
- (void)reloadHeaderView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)showClickRateTips;
- (void)onAlbumNameDidChangedNotify;
- (void)requestAnchorSkill;
- (void)XMFloatTipViewDidTap:(id)arg1;
- (void)setupAnchorSkillView:(id)arg1 url:(id)arg2;
- (void)shareAlbum:(id)arg1;
- (void)addAlbum:(id)arg1;
- (void)buildAlbumSuccess:(id)arg1;
- (void)gotoBuildAlbum;
- (void)onAdd;
- (void)search:(id)arg1;
- (void)onNoDataActionButtonClicked:(id)arg1;
- (void)optionAction;
- (void)actionSheetDismiss:(id)arg1;
- (void)clickAtRateFromAlbumUserCell:(id)arg1;
- (void)onMoreMenuButtonClicked:(id)arg1;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)requestDeleteAlbumFailed:(id)arg1;
- (void)requestDeleteAlbumFinished:(id)arg1;
- (void)requestDeleteAlbum:(id)arg1;
- (void)deleteWithAlbum:(id)arg1;
- (void)triggerLoadMore;
- (_Bool)isLoadMoreViewNeeded;
- (void)triggerPullToRefresh;
- (void)doneLoadData;
- (void)requestToCheck;
- (void)requestAlbumListFailedSelector:(id)arg1;
- (void)requestAlbumListFinishedSelector:(id)arg1;
- (void)requestKacha;
- (void)requestAlbumsDataForPage:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupNavigationItem;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

