//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMFindFlowWhiteBackTableViewCell.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "XMNewUserRecGuessCardCellDelegate-Protocol.h"

@class NSArray, NSString, UIButton, UICollectionView, UIImageView, UILabel, UIView, XMMoreButton, XMTableCellObject;
@protocol XMNewUserRecGuessCardCellDelegate;

@interface XMNewUserRecGuessCardCell : XMFindFlowWhiteBackTableViewCell <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, XMNewUserRecGuessCardCellDelegate>
{
    struct CGSize _itemSize;
    _Bool _isLoading;
    XMTableCellObject *_cellObject;
    id <XMNewUserRecGuessCardCellDelegate> _delegate;
    NSArray *_items;
    UIView *_backView;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    UIButton *_interestButton;
    UIView *_interestLine;
    XMMoreButton *_moreButton;
    UICollectionView *_collectionView;
    UIButton *_reloadButton;
    double _collectionHeight;
}

+ (double)tableView:(id)arg1 heightForCellObject:(id)arg2;
+ (id)cellObjectWithCellModel:(id)arg1 customDelegate:(id)arg2;
@property(nonatomic) double collectionHeight; // @synthesize collectionHeight=_collectionHeight;
@property(retain, nonatomic) UIButton *reloadButton; // @synthesize reloadButton=_reloadButton;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) XMMoreButton *moreButton; // @synthesize moreButton=_moreButton;
@property(retain, nonatomic) UIView *interestLine; // @synthesize interestLine=_interestLine;
@property(retain, nonatomic) UIButton *interestButton; // @synthesize interestButton=_interestButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) __weak id <XMNewUserRecGuessCardCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) XMTableCellObject *cellObject; // @synthesize cellObject=_cellObject;
- (void).cxx_destruct;
- (void)longPressGuess:(id)arg1 albumCardModel:(id)arg2 recFlowModel:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)reloadCellWithCellObject:(id)arg1 tableViewDelegate:(id)arg2;
- (void)p_updateAnimation;
- (void)p_clickReloadAction:(id)arg1;
- (void)p_clickMoreAction:(id)arg1;
- (void)p_interestButtonTapped:(id)arg1;
- (void)p_setConstraints;
- (void)p_setUI;
- (void)p_initData;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

