//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AEAudioFilePlayer, NSURL;

@interface XMNewAudioPlayer : NSObject
{
    double _currentTime;
    double _pauseTime;
    CDUnknownBlockType _completionBlock;
    CDUnknownBlockType _pauseBlock;
    double _duration;
    NSURL *_url;
    AEAudioFilePlayer *_player;
}

@property(retain, nonatomic) AEAudioFilePlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(copy) CDUnknownBlockType pauseBlock; // @synthesize pauseBlock=_pauseBlock;
@property(copy) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(nonatomic) double pauseTime; // @synthesize pauseTime=_pauseTime;
- (void).cxx_destruct;
- (void)stop;
- (void)pause;
- (_Bool)play;
@property(nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
@property(readonly, nonatomic, getter=isPlaying) _Bool playing;
- (void)createAudioPlayerURL:(id)arg1 error:(id *)arg2;
- (id)initWithContentsOfURL:(id)arg1 error:(id *)arg2;
- (void)dealloc;

@end

