//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XMBase/XMModel.h>

@class NSArray, NSString;

@interface XMPersonalCenterSectionFooterModel : XMModel
{
    NSString *_imgUrl;
    NSString *_linkUrl;
    NSArray *_activities;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain, nonatomic) NSArray *activities; // @synthesize activities=_activities;
@property(retain, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(retain, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
- (void).cxx_destruct;

@end

