//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMSubLevelViewController.h"

#import "XMTableViewDelegateProtocol-Protocol.h"
#import "XMTableViewEditDoneViewDelegate-Protocol.h"
#import "XMTableViewEditSelectViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, XMNRequest, XMPlayListModel, XMTableViewDataSource;

@interface XMPlayListDetailDeleteViewController : XMSubLevelViewController <XMTableViewDelegateProtocol, XMTableViewEditDoneViewDelegate, XMTableViewEditSelectViewDelegate>
{
    CDUnknownBlockType _completeDeleteTracks;
    XMTableViewDataSource *_tableDataSource;
    NSMutableArray *_removeTracks;
    NSArray *_objs;
    NSArray *_listenObjs;
    XMPlayListModel *_model;
    XMNRequest *_playListReq;
}

@property(retain, nonatomic) XMNRequest *playListReq; // @synthesize playListReq=_playListReq;
@property(retain, nonatomic) XMPlayListModel *model; // @synthesize model=_model;
@property(retain, nonatomic) NSArray *listenObjs; // @synthesize listenObjs=_listenObjs;
@property(retain, nonatomic) NSArray *objs; // @synthesize objs=_objs;
@property(retain, nonatomic) NSMutableArray *removeTracks; // @synthesize removeTracks=_removeTracks;
@property(retain, nonatomic) XMTableViewDataSource *tableDataSource; // @synthesize tableDataSource=_tableDataSource;
@property(copy, nonatomic) CDUnknownBlockType completeDeleteTracks; // @synthesize completeDeleteTracks=_completeDeleteTracks;
- (void).cxx_destruct;
- (void)deleteTracksWithTracks:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)tableViewDeletionDone;
- (void)tableViewDeletionCancel;
- (void)tableViewDeletionListenedDidClick:(_Bool)arg1;
- (void)tableViewDeletionSelectAllDidClick:(_Bool)arg1;
- (void)checkDoneEnableAndSelectAll;
- (id)dequeueReusableCellWithCellObject:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableViewDidSelectCellWithCellObject:(id)arg1 tableViewCell:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)editPlaceholder;
- (double)contentBottomOffset;
- (void)reTryFetchData:(id)arg1;
- (void)showError;
- (id)parseObjsWithResponseData:(id)arg1;
- (void)fetchDefautlLaterTracks;
- (void)viewDidLoad;
- (id)initWithDeleteOjbs:(id)arg1 andPlayListModel:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

