//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "XMTableCellModelProtocol-Protocol.h"

@class NSArray, NSString, NSURL;

@interface XMRankItem : NSObject <XMTableCellModelProtocol>
{
    NSString *_contentType;
    NSURL *_coverPath;
    NSString *_title;
    NSString *_detailTitle;
    NSString *_redisKey;
    NSString *_period;
    NSArray *_firstKResults;
    long long _rankingListId;
    NSString *_target;
    long long _subCategoryId;
    NSString *_rankingRule;
    NSString *_sortRuleDesc;
    NSString *_updateAtDesc;
}

@property(copy, nonatomic) NSString *updateAtDesc; // @synthesize updateAtDesc=_updateAtDesc;
@property(copy, nonatomic) NSString *sortRuleDesc; // @synthesize sortRuleDesc=_sortRuleDesc;
@property(copy, nonatomic) NSString *rankingRule; // @synthesize rankingRule=_rankingRule;
@property(nonatomic) long long subCategoryId; // @synthesize subCategoryId=_subCategoryId;
@property(copy, nonatomic) NSString *target; // @synthesize target=_target;
@property(nonatomic) long long rankingListId; // @synthesize rankingListId=_rankingListId;
@property(copy, nonatomic) NSArray *firstKResults; // @synthesize firstKResults=_firstKResults;
@property(copy, nonatomic) NSString *period; // @synthesize period=_period;
@property(copy, nonatomic) NSString *redisKey; // @synthesize redisKey=_redisKey;
@property(copy, nonatomic) NSString *detailTitle; // @synthesize detailTitle=_detailTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSURL *coverPath; // @synthesize coverPath=_coverPath;
@property(copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
- (void).cxx_destruct;
- (void)updateRankItemFromDict:(id)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

