//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface XMRecordBGMusicManager : NSObject
{
    _Bool _useCellularData;
    NSMutableArray *_wifiSoundItemsArray;
    NSMutableArray *_defualtSoundItemsArray;
    NSMutableArray *_downloadNetSounds;
    NSMutableArray *_downloadingArray;
    NSMutableArray *_selectedSounds;
}

+ (id)sharedManager;
@property(nonatomic) _Bool useCellularData; // @synthesize useCellularData=_useCellularData;
@property(retain, nonatomic) NSMutableArray *selectedSounds; // @synthesize selectedSounds=_selectedSounds;
@property(retain, nonatomic) NSMutableArray *downloadingArray; // @synthesize downloadingArray=_downloadingArray;
@property(retain, nonatomic) NSMutableArray *downloadNetSounds; // @synthesize downloadNetSounds=_downloadNetSounds;
@property(retain, nonatomic) NSMutableArray *defualtSoundItemsArray; // @synthesize defualtSoundItemsArray=_defualtSoundItemsArray;
@property(retain, nonatomic) NSMutableArray *wifiSoundItemsArray; // @synthesize wifiSoundItemsArray=_wifiSoundItemsArray;
- (void).cxx_destruct;
- (void)cancelAllDownloadAndRemoveFiles:(_Bool)arg1;
- (void)deleteNetSound:(id)arg1;
- (void)downloadNetSound:(id)arg1 progress:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)downloadNetSound:(id)arg1;
- (void)reportDownload:(id)arg1;
- (void)saveLocalNetSounds;
- (id)loadLocalNetSounds;
- (void)updataWifiSound;
- (_Bool)checkSoundItemExist:(id)arg1;
- (void)deleteSounds:(id)arg1;
- (void)deleteWifiSound:(id)arg1;
- (void)deleteDefualtSound:(id)arg1;
- (id)getDeleteDefualtSounds;
- (id)getAllLocalMusicFromIpod;
- (id)getDefualtSound;
- (id)getWifiDownLoadSound;
- (id)init;
- (void)dealloc;

@end

