//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, UICollectionView, UICollectionViewFlowLayout, UIScrollView, XMRecorderScrollPageDicView, XMTimer;
@protocol XMRecorderScrollViewDelegate;

@interface XMRecorderScrollView : UIView <UIScrollViewDelegate>
{
    _Bool _pagingEnabled;
    _Bool _cyclicSlip;
    _Bool _scrollEnabled;
    _Bool _showPageView;
    _Bool _notBounce;
    _Bool _enabled;
    _Bool _normalAutoAnimationDir;
    _Bool _normalAutoIsAnimation;
    _Bool _useTimer;
    id <XMRecorderScrollViewDelegate> _delegate;
    UIScrollView *_scrollView;
    UICollectionView *_collectionView;
    UICollectionViewFlowLayout *_fy;
    unsigned long long _fixNum;
    XMTimer *_timer;
    unsigned long long _timeSecond;
    XMRecorderScrollPageDicView *_scrollPageView;
}

@property(retain, nonatomic) XMRecorderScrollPageDicView *scrollPageView; // @synthesize scrollPageView=_scrollPageView;
@property(nonatomic) _Bool useTimer; // @synthesize useTimer=_useTimer;
@property(nonatomic) unsigned long long timeSecond; // @synthesize timeSecond=_timeSecond;
@property(nonatomic) _Bool normalAutoIsAnimation; // @synthesize normalAutoIsAnimation=_normalAutoIsAnimation;
@property(nonatomic) _Bool normalAutoAnimationDir; // @synthesize normalAutoAnimationDir=_normalAutoAnimationDir;
@property(retain, nonatomic) XMTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) unsigned long long fixNum; // @synthesize fixNum=_fixNum;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) UICollectionViewFlowLayout *fy; // @synthesize fy=_fy;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <XMRecorderScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool notBounce; // @synthesize notBounce=_notBounce;
@property(nonatomic) _Bool showPageView; // @synthesize showPageView=_showPageView;
@property(nonatomic) _Bool scrollEnabled; // @synthesize scrollEnabled=_scrollEnabled;
@property(nonatomic) _Bool cyclicSlip; // @synthesize cyclicSlip=_cyclicSlip;
@property(nonatomic) _Bool pagingEnabled; // @synthesize pagingEnabled=_pagingEnabled;
- (void).cxx_destruct;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollToIndex:(long long)arg1;
- (void)p_handleAutoAnimation;
- (void)stopAutoAnimation;
- (void)startAutoAnimationWithTimespace:(long long)arg1 normalDirection:(_Bool)arg2 animation:(_Bool)arg3;
- (void)reloadUI;
- (id)fixCollectionViewData:(id)arg1;
- (void)customInit;
- (id)initWithFrame:(struct CGRect)arg1 collectionView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

