//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RWAlertView.h"

@interface XMRWSettingGuideAlert : RWAlertView
{
    CDUnknownBlockType _buttonClickBlock;
    double _calHeight;
}

@property(nonatomic) double calHeight; // @synthesize calHeight=_calHeight;
@property(copy, nonatomic) CDUnknownBlockType buttonClickBlock; // @synthesize buttonClickBlock=_buttonClickBlock;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancelDidClick;
- (void)certainDidClick;
- (double)adjustHeight;
- (void)setupWithHeaderIcon:(id)arg1 setttingIntro:(id)arg2 cancelButtonTitle:(id)arg3 certainButtonTitle:(id)arg4;
- (id)initWithHeaderIcon:(id)arg1 setttingIntro:(id)arg2 cancelButtonTitle:(id)arg3 certainButtonTitle:(id)arg4 tapBlock:(CDUnknownBlockType)arg5;

@end

