//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMBaseViewController.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UIButton, UICollectionView, UILabel;

@interface XMSCHallViewController : XMBaseViewController <UICollectionViewDelegate, UICollectionViewDataSource>
{
    _Bool _hasPullToRefresh;
    _Bool _hasLoadMore;
    _Bool _isLoadMoreViewNeeded;
    UIButton *_backBtn;
    UILabel *_titleLabel;
    UICollectionView *_collectionView;
    NSArray *_dataArray;
    NSMutableArray *_refreshImages;
}

@property(nonatomic) _Bool isLoadMoreViewNeeded; // @synthesize isLoadMoreViewNeeded=_isLoadMoreViewNeeded;
@property(nonatomic) _Bool hasLoadMore; // @synthesize hasLoadMore=_hasLoadMore;
@property(nonatomic) _Bool hasPullToRefresh; // @synthesize hasPullToRefresh=_hasPullToRefresh;
@property(retain, nonatomic) NSMutableArray *refreshImages; // @synthesize refreshImages=_refreshImages;
@property(retain, nonatomic) NSArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)loadCollectionView;
- (void)registerRefreshWithScrollView:(id)arg1;
- (void)loadFinished;
- (void)loadMore;
- (void)pullToRefresh;
- (void)back;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

