//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray, UIColor, UIFont, UILabel, XMNumberContainer;

@interface XMTimeCountDownView : UIView
{
    UILabel *_leadTextLabel;
    XMNumberContainer *_firstContainer;
    XMNumberContainer *_secondContainer;
    XMNumberContainer *_thirdContainer;
    XMNumberContainer *_forthContainer;
    UILabel *_dayUnitLabel;
    UILabel *_hourUnitLabel;
    UILabel *_miniteUnitLabel;
    UILabel *_secondUnitLabel;
    NSMutableArray *_numberArray;
    NSArray *_textArray;
    UIColor *_numberBgColor;
    UIColor *_numberColor;
    UIColor *_textColor;
    UIFont *_textFont;
    UIFont *_numberFont;
    unsigned long long _style;
    struct CGSize _numberSize;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(retain, nonatomic) UIFont *numberFont; // @synthesize numberFont=_numberFont;
@property(retain, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(nonatomic) struct CGSize numberSize; // @synthesize numberSize=_numberSize;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIColor *numberColor; // @synthesize numberColor=_numberColor;
@property(retain, nonatomic) UIColor *numberBgColor; // @synthesize numberBgColor=_numberBgColor;
- (void)findNumFromStr:(id)arg1;
- (void)displayCountDownString:(id)arg1;
- (void)displayCountDownStr:(id)arg1 style:(unsigned long long)arg2;
- (double)countDownHeight;
- (void)layoutSubviews;
- (void)customUIInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

