//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMSubLevelViewController.h"

#import "XMTableViewDelegateProtocol-Protocol.h"
#import "XMTrackBuyNewRichCellDelegate-Protocol.h"
#import "XMVXPageViewSubControllerProtocol-Protocol.h"

@class NSString, XMNewTrackBuyAlbumItem, XMTableViewDataSource;

@interface XMTrackbuyAlbumIntroViewController : XMSubLevelViewController <XMTableViewDelegateProtocol, XMTrackBuyNewRichCellDelegate, XMVXPageViewSubControllerProtocol>
{
    unsigned int _reloadEvent;
    XMNewTrackBuyAlbumItem *_trackBuyAlbumItem;
    CDUnknownBlockType _scrollViewDidScroll;
    XMTableViewDataSource *_tableDataSource;
}

@property(retain, nonatomic) XMTableViewDataSource *tableDataSource; // @synthesize tableDataSource=_tableDataSource;
@property(copy, nonatomic) CDUnknownBlockType scrollViewDidScroll; // @synthesize scrollViewDidScroll=_scrollViewDidScroll;
@property(retain, nonatomic) XMNewTrackBuyAlbumItem *trackBuyAlbumItem; // @synthesize trackBuyAlbumItem=_trackBuyAlbumItem;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (id)vxContentScrollView;
- (void)runBlock:(CDUnknownBlockType)arg1;
- (void)performBlock:(CDUnknownBlockType)arg1;
- (void)newRichCellNeedScrollToCampServiceIntroWithCell:(id)arg1;
- (void)newRichCellClikLink:(id)arg1;
- (void)newRichCellDidFinishLoadHTML:(id)arg1;
- (void)newRichCellDidSelectAtMoreComment;
- (void)newRichCellDidSelectAtTalkGroup;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableViewDidSelectCellWithCellObject:(id)arg1 tableViewCell:(id)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

