//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMBaseAlert.h"

@interface XMUnavailableAlbumAlert : XMBaseAlert
{
    CDUnknownBlockType _unavailableAlbumAlertDidClick;
}

+ (void)showWithDidClick:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) CDUnknownBlockType unavailableAlbumAlertDidClick; // @synthesize unavailableAlbumAlertDidClick=_unavailableAlbumAlertDidClick;
- (void).cxx_destruct;
- (void)closeClick:(id)arg1;
- (void)buttonClick:(id)arg1;
- (void)close;
- (void)initUI;
- (void)dealloc;

@end

