//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "XMUserTracksSubDelegate-Protocol.h"

@class NSMutableArray, NSString, UILabel, UITableView, UIView, XMMoreButton;
@protocol XMUserTracksDelegate, XMUserTracksSubDelegate;

@interface XMUserTracksCell : UITableViewCell <UITableViewDelegate, UITableViewDataSource, XMUserTracksSubDelegate>
{
    _Bool _hasMore;
    id <XMUserTracksDelegate> _delegate;
    id <XMUserTracksSubDelegate> _itemDelegate;
    NSMutableArray *_sounds;
    unsigned long long _tracksTotalCount;
    UIView *_backView;
    UILabel *_titleLabel;
    UILabel *_countLabel;
    XMMoreButton *_moreButton;
    UITableView *_tableView;
}

+ (double)tableView:(id)arg1 heightForCellObject:(id)arg2;
+ (id)cellObjectWithCellModel:(id)arg1 customDelegate:(id)arg2;
+ (double)cellHeightWithSounds:(id)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) XMMoreButton *moreButton; // @synthesize moreButton=_moreButton;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(nonatomic) unsigned long long tracksTotalCount; // @synthesize tracksTotalCount=_tracksTotalCount;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(retain, nonatomic) NSMutableArray *sounds; // @synthesize sounds=_sounds;
@property(nonatomic) __weak id <XMUserTracksSubDelegate> itemDelegate; // @synthesize itemDelegate=_itemDelegate;
@property(nonatomic) __weak id <XMUserTracksDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reloadCellWithCellObject:(id)arg1 tableViewDelegate:(id)arg2;
- (void)userTracksCell:(id)arg1 didClickMore:(id)arg2;
- (void)userTracksCell:(id)arg1 didClickBuy:(id)arg2;
- (void)userTracksCell:(id)arg1 didClickDownload:(id)arg2;
- (void)userTracksCell:(id)arg1 didClickPlay:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)p_moreButtonAction:(id)arg1;
- (void)p_makeConstraints;
- (void)p_setUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

