//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSProxy.h>

@class NSHashTable, Protocol;

@interface XMVCProtocolHub : NSProxy
{
    Protocol *_protocol;
    struct map<std::__1::basic_string<char>, std::__1::tuple<NSMethodSignature *, bool>, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::tuple<NSMethodSignature *, bool>>>> _instance_methods;
    NSHashTable *_outputs;
    struct _opaque_pthread_mutex_t _lock;
}

+ (id)alloc;
+ (id)hubWithProtocol:(id)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)removeOutput:(id)arg1;
- (_Bool)addOutput:(id)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (id)typeDescription;
- (id)description;
- (_Bool)isConforms:(id)arg1;
- (_Bool)isRequiredSel:(SEL)arg1;
- (id)msForSel:(SEL)arg1;
- (_Bool)hasSel:(SEL)arg1;
- (void)loadProtocolMethod;
- (id)initWithProtocol:(id)arg1;
- (void)dealloc;

@end

