//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class XMVCCaptureControl;

@protocol XMVCCaptureControlDelegate <NSObject>
- (void)captureControlDidTapPreview:(XMVCCaptureControl *)arg1;
- (void)captureControlDidTapDelte:(XMVCCaptureControl *)arg1;
- (void)captureControlDidTapFilter:(XMVCCaptureControl *)arg1;
- (void)captureControlDidTapPhoto:(XMVCCaptureControl *)arg1;
- (void)captureControlDidTapCombination:(XMVCCaptureControl *)arg1;
- (void)captureControlDidTapCoProduction:(XMVCCaptureControl *)arg1;
- (void)captureControlDidTapBgmusic:(XMVCCaptureControl *)arg1;
- (void)captureControlDidTapShoot:(XMVCCaptureControl *)arg1;
- (_Bool)captureControlDidTapBeautify:(XMVCCaptureControl *)arg1;
- (_Bool)captureControlDidTapProp:(XMVCCaptureControl *)arg1;
- (void)captureControl:(XMVCCaptureControl *)arg1 rateChange:(unsigned long long)arg2;
- (void)captureControlDeviceChange:(XMVCCaptureControl *)arg1;
- (_Bool)captureControl:(XMVCCaptureControl *)arg1 flashChanged:(_Bool)arg2;
@end

