//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMVLock.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString;

@interface XMVDataItem : XMVLock <NSCopying, NSCoding>
{
    double _createTimeInterval;
    NSString *_relativePath;
    NSString *_absolutePath;
    long long _offset;
    long long _length;
}

@property(readonly, nonatomic) long long length; // @synthesize length=_length;
@property(readonly, nonatomic) long long offset; // @synthesize offset=_offset;
@property(readonly, copy, nonatomic) NSString *absolutePath; // @synthesize absolutePath=_absolutePath;
@property(readonly, copy, nonatomic) NSString *relativePath; // @synthesize relativePath=_relativePath;
@property(readonly, nonatomic) double createTimeInterval; // @synthesize createTimeInterval=_createTimeInterval;
- (void).cxx_destruct;
- (void)setLength:(long long)arg1;
- (void)prepare;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initCopy;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithPath:(id)arg1 offset:(long long)arg2;

@end

