//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface XMWatermarkInfoModel : NSObject
{
    _Bool _isCaf;
    int _displayWidth;
    int _displayHeight;
    float _opacity;
    int _position;
    int _marginX;
    int _marginY;
    float _sceneWidth;
    float _sceneHeight;
    NSString *_imageUrl;
    long long _inPoint;
    long long _outPoint;
}

@property(nonatomic) long long outPoint; // @synthesize outPoint=_outPoint;
@property(nonatomic) long long inPoint; // @synthesize inPoint=_inPoint;
@property(nonatomic) float sceneHeight; // @synthesize sceneHeight=_sceneHeight;
@property(nonatomic) float sceneWidth; // @synthesize sceneWidth=_sceneWidth;
@property(nonatomic) int marginY; // @synthesize marginY=_marginY;
@property(nonatomic) int marginX; // @synthesize marginX=_marginX;
@property(nonatomic) int position; // @synthesize position=_position;
@property(nonatomic) float opacity; // @synthesize opacity=_opacity;
@property(nonatomic) int displayHeight; // @synthesize displayHeight=_displayHeight;
@property(nonatomic) int displayWidth; // @synthesize displayWidth=_displayWidth;
@property(nonatomic) _Bool isCaf; // @synthesize isCaf=_isCaf;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
- (void).cxx_destruct;
- (id)init;

@end

