//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CDZView.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "XMWeKeToolBarTableViewDelegate-Protocol.h"

@class CDZAttributedString, NSMutableArray, NSString, UIButton, XMWeKeLesson, XMWeKeToolBarTableView;
@protocol XMWeKeDiscussViewDelegate;

@interface XMWeKeDiscussView : CDZView <XMWeKeToolBarTableViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    _Bool _needPullLostMessage;
    id <XMWeKeDiscussViewDelegate> _delegate;
    XMWeKeToolBarTableView *_tableView;
    unsigned long long _type;
    long long _role;
    UIButton *_segButton;
    XMWeKeLesson *_lesson;
    NSMutableArray *_dataArray;
    CDUnknownBlockType _toolBarSizeChangeBlock;
    CDZAttributedString *_titleString;
    CDZAttributedString *_selectedTitleString;
    long long _totalCount;
}

@property(nonatomic) long long totalCount; // @synthesize totalCount=_totalCount;
@property(retain, nonatomic) CDZAttributedString *selectedTitleString; // @synthesize selectedTitleString=_selectedTitleString;
@property(retain, nonatomic) CDZAttributedString *titleString; // @synthesize titleString=_titleString;
@property(copy, nonatomic) CDUnknownBlockType toolBarSizeChangeBlock; // @synthesize toolBarSizeChangeBlock=_toolBarSizeChangeBlock;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(nonatomic) _Bool needPullLostMessage; // @synthesize needPullLostMessage=_needPullLostMessage;
@property(retain, nonatomic) XMWeKeLesson *lesson; // @synthesize lesson=_lesson;
@property(nonatomic) __weak UIButton *segButton; // @synthesize segButton=_segButton;
@property(nonatomic) long long role; // @synthesize role=_role;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) XMWeKeToolBarTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <XMWeKeDiscussViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)uniqueDiscussKey:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)cellDidClickMoreButton:(id)arg1;
- (void)cellDidClickStatusButton:(id)arg1;
- (void)cellDidClickHeadButton:(id)arg1;
- (void)webSocket:(id)arg1 deleteComment:(id)arg2;
- (void)webSocket:(id)arg1 receiveComment:(id)arg2;
- (void)webSocketDidDisconnect:(id)arg1 error:(id)arg2;
- (void)toolBarTableViewToolBarSizeIsChanging:(id)arg1;
- (void)toolBarTableViewDidLoadMore:(id)arg1;
- (void)toolBarTableViewDidRefresh:(id)arg1;
- (void)requestComments:(unsigned long long)arg1 anchorMsgId:(unsigned long long)arg2 type:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)loadMoreData:(_Bool)arg1;
- (void)updateEmptyView;
- (void)updateTitle;
- (void)dealloc;
- (void)didInitialize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

