//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZOAuthManager.h"

@interface ZTOAuthManager : ZOAuthManager
{
}

+ (void)ignoreCachingStrategyInPreLoginModule:(id)arg1;
+ (void)clearZOAuthContextAllCache;
+ (id)getInstance;
- (void)ZOAURelease;
- (void)setLoginSuccessPage:(id)arg1;
- (void)customUIWithParams:(id)arg1 topCustomViews:(CDUnknownBlockType)arg2 bottomCustomViews:(CDUnknownBlockType)arg3;
- (void)gmbc:(id)arg1 mobile:(id)arg2 listener:(CDUnknownBlockType)arg3;
- (_Bool)clearCTOauthCache;
- (void)closeCTOauthCachingStrategy:(_Bool)arg1;
- (void)oauth:(double)arg1 resultListener:(CDUnknownBlockType)arg2;
- (void)interruptTheCTLoginFlow:(_Bool)arg1 ifDisapperTheShowingLoginPage:(_Bool)arg2 cancelTheNextAuthorizationPageToPullUp:(_Bool)arg3;
- (void)login:(id)arg1 timeout:(double)arg2 resultListener:(CDUnknownBlockType)arg3;
- (void)loginPre:(double)arg1 resultListener:(CDUnknownBlockType)arg2;
- (void)init:(id)arg1 pubKey:(id)arg2;

@end

