//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CKCameraControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class AVCaptureSession, CKCameraController, CKCaptureConfig, CKCaptureManagerEventAnnouncer, CKRenderView, NSString;
@protocol CKCaptureManagerDelegate, OS_dispatch_queue;

@interface CKCaptureManager : NSObject <CKCameraControllerDelegate, UIGestureRecognizerDelegate>
{
    struct {
        unsigned int isRecording:1;
        unsigned int isSessionStart:1;
        unsigned int isVideoAuthorized:1;
        unsigned int isAudioAuthorized:1;
    } _flags;
    _Bool _microphoneEnabled;
    CKCameraController *_cameraController;
    CKCaptureConfig *_config;
    NSObject<OS_dispatch_queue> *_workQueue;
    unsigned long long _currentState;
    long long _position;
    long long _torchMode;
    id <CKCaptureManagerDelegate> _delegate;
    CKCaptureManagerEventAnnouncer *_announcer;
    long long _sessionRetryCount;
    CDStruct_1b6d18a9 _recordStartTime;
}

@property(nonatomic) long long sessionRetryCount; // @synthesize sessionRetryCount=_sessionRetryCount;
@property(retain, nonatomic) CKCaptureManagerEventAnnouncer *announcer; // @synthesize announcer=_announcer;
@property(nonatomic) CDStruct_1b6d18a9 recordStartTime; // @synthesize recordStartTime=_recordStartTime;
@property(nonatomic) __weak id <CKCaptureManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long torchMode; // @synthesize torchMode=_torchMode;
@property(nonatomic) long long position; // @synthesize position=_position;
@property(nonatomic, getter=isMicrophoneEnabled) _Bool microphoneEnabled; // @synthesize microphoneEnabled=_microphoneEnabled;
@property(nonatomic) unsigned long long currentState; // @synthesize currentState=_currentState;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(retain, nonatomic) CKCaptureConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) CKCameraController *cameraController; // @synthesize cameraController=_cameraController;
- (void).cxx_destruct;
- (void)sessionDidStopRunning:(id)arg1;
- (void)sessionDidStartRunning:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)sessionWasInterrupted:(id)arg1;
- (void)sessionRuntimeError:(id)arg1;
- (void)removeObservers;
- (void)addObservers;
- (void)updateRecordingProgress:(CDStruct_1b6d18a9)arg1;
- (void)updateRecordingStartTime:(CDStruct_1b6d18a9)arg1;
- (void)updateProgressIfNeeded:(CDStruct_1b6d18a9)arg1;
- (_Bool)shouldWrite:(id)arg1;
- (void)didDisplayFrameAtTime:(CDStruct_1b6d18a9)arg1;
- (void)willDisplayFrameAtTime:(CDStruct_1b6d18a9)arg1;
- (void)didProcessWriterFrameAtTime:(CDStruct_1b6d18a9)arg1;
- (void)willProcessWriterFrameAtTime:(CDStruct_1b6d18a9)arg1;
- (void)didProcessRenderFrameAtTime:(CDStruct_1b6d18a9)arg1;
- (void)willProcessRenderFrameAtTime:(CDStruct_1b6d18a9)arg1;
- (void)didDropFrameAtTime:(CDStruct_1b6d18a9)arg1 info:(id)arg2 isVideo:(_Bool)arg3;
- (void)cameraDidOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 isVideo:(_Bool)arg2;
- (void)removeStateListener:(id)arg1;
- (void)addStateListener:(id)arg1;
- (void)focusAtDevicePoint:(struct CGPoint)arg1;
- (void)zoomWithRatio:(double)arg1;
- (void)zoomWithScale:(double)arg1;
- (void)toggleCameraSynchronously:(_Bool)arg1;
- (id)rotationNeededForCapturedImage:(id)arg1 metaData:(id)arg2;
- (void)capturePhotoWithAnimation:(CDUnknownBlockType)arg1 snapshot:(_Bool)arg2 callback:(CDUnknownBlockType)arg3;
- (void)stopVideoCapture:(_Bool)arg1 compeletion:(CDUnknownBlockType)arg2;
- (void)cancelVideoCapture:(CDUnknownBlockType)arg1;
- (void)endVideoCapture:(CDUnknownBlockType)arg1;
- (void)_asyncStartCapture;
- (void)_syncStartCapture;
- (void)startVideoCapture:(_Bool)arg1;
- (void)stopCaptureSession:(CDUnknownBlockType)arg1;
- (void)startCaptureSession:(CDUnknownBlockType)arg1;
- (void)reloadWriterIfNeed;
- (void)reloadWriter;
- (void)requestAccessForMediaType:(id)arg1;
- (_Bool)isRecording;
- (_Bool)isAuthorized;
@property(readonly, nonatomic) _Bool isVideoMirrored;
@property(readonly, nonatomic) CKRenderView *previewView;
- (id)sharedEAGLContext;
@property(readonly, nonatomic) AVCaptureSession *captureSession;
- (void)setupPreview;
- (void)setupCameraController;
- (id)initWithConfig:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

