//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSString;

@protocol CRPackageDownloadListener <NSObject>
- (void)onDownloadFailure:(NSError *)arg1;
- (void)onDownloadSuccess:(NSString *)arg1;
- (void)onDownloadRetry:(long long)arg1;
- (void)onDownloadProgress:(long long)arg1 totalSize:(long long)arg2;
- (void)onDownloadStart;
@end

