//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface CRRuntimeLocalStorage : NSObject
{
    _Bool _initialized;
    NSString *_databasePath;
    struct sqlite3 *_db;
    struct sqlite3_stmt *_stmt_select;
    struct sqlite3_stmt *_stmt_remove;
    struct sqlite3_stmt *_stmt_update;
    struct sqlite3_stmt *_stmt_clear;
    struct sqlite3_stmt *_stmt_key;
    struct sqlite3_stmt *_stmt_count;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)getInstance;
@property(nonatomic) struct sqlite3_stmt *stmt_count; // @synthesize stmt_count=_stmt_count;
@property(nonatomic) struct sqlite3_stmt *stmt_key; // @synthesize stmt_key=_stmt_key;
@property(nonatomic) struct sqlite3_stmt *stmt_clear; // @synthesize stmt_clear=_stmt_clear;
@property(nonatomic) struct sqlite3_stmt *stmt_update; // @synthesize stmt_update=_stmt_update;
@property(nonatomic) struct sqlite3_stmt *stmt_remove; // @synthesize stmt_remove=_stmt_remove;
@property(nonatomic) struct sqlite3_stmt *stmt_select; // @synthesize stmt_select=_stmt_select;
@property(nonatomic) struct sqlite3 *db; // @synthesize db=_db;
@property(nonatomic) _Bool initialized; // @synthesize initialized=_initialized;
@property(copy, nonatomic) NSString *databasePath; // @synthesize databasePath=_databasePath;
- (void).cxx_destruct;
- (unsigned long long)getLength;
- (id)getKeyAtIndex:(int)arg1;
- (void)clear;
- (void)removeItemWithKey:(id)arg1;
- (id)getItemWithKey:(id)arg1;
- (void)setItemWithKey:(id)arg1 value:(id)arg2;
- (void)_localStorageCreateTable;
- (void)free;
- (void)initLocalStorage;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

