//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface MMDownloadFileStat : NSObject
{
    int _messageClass;
    int _type;
    long long _localId;
    long long _chatId;
    long long _messageId;
    long long _size;
    long long _startTime;
    long long _sendReturnTime;
    long long _code;
    NSString *_error;
    NSString *_traceId;
    NSDictionary *_traceRequestParams;
}

+ (id)statWithMessage:(id)arg1;
@property(retain, nonatomic) NSDictionary *traceRequestParams; // @synthesize traceRequestParams=_traceRequestParams;
@property(copy, nonatomic) NSString *traceId; // @synthesize traceId=_traceId;
@property(copy, nonatomic) NSString *error; // @synthesize error=_error;
@property(nonatomic) long long code; // @synthesize code=_code;
@property(nonatomic) long long sendReturnTime; // @synthesize sendReturnTime=_sendReturnTime;
@property(nonatomic) long long startTime; // @synthesize startTime=_startTime;
@property(nonatomic) long long size; // @synthesize size=_size;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) int messageClass; // @synthesize messageClass=_messageClass;
@property(nonatomic) long long messageId; // @synthesize messageId=_messageId;
@property(nonatomic) long long chatId; // @synthesize chatId=_chatId;
@property(nonatomic) long long localId; // @synthesize localId=_localId;
- (void).cxx_destruct;
- (void)postFailureWithError:(id)arg1;
- (void)post;
- (long long)currentMicroseconds;
- (void)sendReturn;
- (void)start;

@end

