//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, NodeLayoutPropertySetter;

@interface NodeDescriptor : NSObject <NSCopying, NSCoding>
{
    NSString *_nodeName;
    NSString *_exportName;
    NSMutableArray *_subDescriptors;
    NodeDescriptor *_superDescriptor;
    NSMutableDictionary *_propertySetters;
    NodeLayoutPropertySetter *_IDPropertySetter;
    NodeLayoutPropertySetter *_bindViewPropertySetter;
}

@property(retain, nonatomic) NodeLayoutPropertySetter *bindViewPropertySetter; // @synthesize bindViewPropertySetter=_bindViewPropertySetter;
@property(retain, nonatomic) NodeLayoutPropertySetter *IDPropertySetter; // @synthesize IDPropertySetter=_IDPropertySetter;
@property(retain, nonatomic) NSMutableDictionary *propertySetters; // @synthesize propertySetters=_propertySetters;
@property(nonatomic) __weak NodeDescriptor *superDescriptor; // @synthesize superDescriptor=_superDescriptor;
@property(retain, nonatomic) NSMutableArray *subDescriptors; // @synthesize subDescriptors=_subDescriptors;
@property(copy, nonatomic) NSString *exportName; // @synthesize exportName=_exportName;
@property(copy, nonatomic) NSString *nodeName; // @synthesize nodeName=_nodeName;
- (void).cxx_destruct;
- (id)node;
- (void)inheritFrom:(id)arg1;
- (_Bool)isImportedNode;
- (_Bool)isExportedNode;
- (void)travelAllSubDescriptors:(CDUnknownBlockType)arg1;
- (void)addSubNodeDescriptor:(id)arg1;
- (void)addPropertySetter:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

