//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString, TBLiveMessageEndEditItemMsg, TBLiveMessageJoinNotifyWithProtobuf, TBLiveMessageShareGoodsListWithProtobuf;

@protocol TBLiveMessageManagerDelegate <NSObject>

@optional
- (void)didReceiveMessageWithCommonTipsMessage:(NSDictionary *)arg1;
- (void)didReceiveMessageWithAnthorResponse:(NSDictionary *)arg1;
- (void)didReceiveMessageWithUserLevelUP:(NSDictionary *)arg1;
- (void)didReceiveMessageWithSyncVideoSlice:(NSDictionary *)arg1;
- (void)didReceiveMessageWithTBTVChangeProgram:(NSDictionary *)arg1;
- (void)didReceiveMessageWithEnterLiveRoom:(NSDictionary *)arg1;
- (void)didReceiveMessageWithActivity:(NSDictionary *)arg1;
- (void)didReceiveMessageWithEndEditItem:(TBLiveMessageEndEditItemMsg *)arg1;
- (void)didReceiveMessageWithJumpH5Url:(NSDictionary *)arg1;
- (void)didReceiveMessageWithH265Switch:(NSDictionary *)arg1;
- (void)didReceiveMessageWithGlobalNotice:(NSDictionary *)arg1;
- (void)didReceiveMessageWithTradeShow:(NSString *)arg1;
- (void)didReceiveMessageWithJiuGongGe:(NSString *)arg1;
- (void)didReceiveMessageWithStartEditItemV2Message:(TBLiveMessageShareGoodsListWithProtobuf *)arg1;
- (void)didReceiveMessageWithAddGoodsListMessage:(TBLiveMessageShareGoodsListWithProtobuf *)arg1;
- (void)commentManagerDidUpdateUserStateMassage:(TBLiveMessageJoinNotifyWithProtobuf *)arg1;
@end

