//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBViewController.h"

#import "SwipeViewDataSource-Protocol.h"
#import "SwipeViewDelegate-Protocol.h"
#import "WBNavigationCommonTitleViewDelegate-Protocol.h"

@class NSString, WBArticleBrowserViewController, WBArticleDoubleSlidePageControlView, WBArticleSlideBRecommendViewController, WBBrowserArticle, WBNavigationCommonTitleView, WBSegmentSwipeView;

@interface WBArticleSlideViewController : WBViewController <SwipeViewDelegate, SwipeViewDataSource, WBNavigationCommonTitleViewDelegate>
{
    WBNavigationCommonTitleView *_followTitleView;
    WBSegmentSwipeView *_segmentSwipeView;
    WBArticleDoubleSlidePageControlView *_slidePageControl;
    WBArticleBrowserViewController *_browserViewController;
    WBArticleSlideBRecommendViewController *_recommendViewController;
    NSString *_objectID;
    NSString *_mid;
    NSString *_url;
    WBBrowserArticle *_browserArticle;
}

@property(retain, nonatomic) WBBrowserArticle *browserArticle; // @synthesize browserArticle=_browserArticle;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
@property(copy, nonatomic) NSString *objectID; // @synthesize objectID=_objectID;
@property(retain, nonatomic) WBArticleSlideBRecommendViewController *recommendViewController; // @synthesize recommendViewController=_recommendViewController;
@property(retain, nonatomic) WBArticleBrowserViewController *browserViewController; // @synthesize browserViewController=_browserViewController;
@property(retain, nonatomic) WBArticleDoubleSlidePageControlView *slidePageControl; // @synthesize slidePageControl=_slidePageControl;
@property(retain, nonatomic) WBSegmentSwipeView *segmentSwipeView; // @synthesize segmentSwipeView=_segmentSwipeView;
@property(retain, nonatomic) WBNavigationCommonTitleView *followTitleView; // @synthesize followTitleView=_followTitleView;
- (void).cxx_destruct;
- (void)moreButtonDidPressed:(id)arg1;
- (void)setOldNavigationRightButton:(id)arg1;
- (void)titleViewClickLeftIcon:(id)arg1;
- (void)titleViewClickTitle:(id)arg1;
- (id)titleViewDataSource;
- (id)titleViewTitle:(id)arg1;
- (id)titleViewRightButton:(id)arg1;
- (id)titleViewLeftIcon:(id)arg1;
- (id)swipeView:(id)arg1 viewForItemAtIndex:(long long)arg2 reusingView:(id)arg3;
- (long long)numberOfItemsInSwipeView:(id)arg1;
- (void)swipeViewCurrentItemIndexDidChange:(id)arg1;
- (void)swipeViewDidScroll:(id)arg1;
- (void)tipViewClick;
- (void)updateNavigationItem:(id)arg1;
- (void)updateNavigationDataSource:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithOpenUrlLink:(id)arg1 inAppParas:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

