//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "PHLivePhotoViewDelegate-Protocol.h"

@class NSIndexPath, NSMutableDictionary, NSString, PHLivePhotoView, UIButton, UIImageView, UILabel, UIView, WBComposeMediaGradientView, WBLivePhotoToggleButton, WBPhotoProgressView;
@protocol WBAssetImagePickerCellDelegate;

@interface WBAssetImagePickerCell : UICollectionViewCell <PHLivePhotoViewDelegate>
{
    NSMutableDictionary *_dict;
    PHLivePhotoView *_livePhotoView;
    WBLivePhotoToggleButton *_livePhotoToggleButton;
    _Bool _isPlayingLivePhoto;
    _Bool _isDurationTooLong;
    _Bool _hiddenToggleButton;
    WBPhotoProgressView *_progressView;
    _Bool _enableToggleButtonCount;
    _Bool _isBusyForLoadingLivePhoto;
    id <WBAssetImagePickerCellDelegate> _cellDelegate;
    NSIndexPath *_indexPath;
    long long _maxAllowVideoDuration;
    id _cellData;
    UIButton *_preLoadMaskView;
    UIView *_noSelectedMaskView;
    UIImageView *_photoView;
    UIButton *_toggleButton;
    WBComposeMediaGradientView *_bottomView;
    UILabel *_timeLabel;
    UIImageView *_videoIcon;
    UIButton *_coverButton;
    UIImageView *_gifIcon;
    UIImageView *_panoramaIcon;
}

@property(nonatomic) _Bool isBusyForLoadingLivePhoto; // @synthesize isBusyForLoadingLivePhoto=_isBusyForLoadingLivePhoto;
@property(retain, nonatomic) UIImageView *panoramaIcon; // @synthesize panoramaIcon=_panoramaIcon;
@property(retain, nonatomic) UIImageView *gifIcon; // @synthesize gifIcon=_gifIcon;
@property(retain, nonatomic) PHLivePhotoView *livePhotoView; // @synthesize livePhotoView=_livePhotoView;
@property(retain, nonatomic) WBLivePhotoToggleButton *livePhotoToggleButton; // @synthesize livePhotoToggleButton=_livePhotoToggleButton;
@property(retain, nonatomic) UIButton *coverButton; // @synthesize coverButton=_coverButton;
@property(retain, nonatomic) UIImageView *videoIcon; // @synthesize videoIcon=_videoIcon;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) WBComposeMediaGradientView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIButton *toggleButton; // @synthesize toggleButton=_toggleButton;
@property(retain, nonatomic) UIImageView *photoView; // @synthesize photoView=_photoView;
@property(retain, nonatomic) UIView *noSelectedMaskView; // @synthesize noSelectedMaskView=_noSelectedMaskView;
@property(retain, nonatomic) UIButton *preLoadMaskView; // @synthesize preLoadMaskView=_preLoadMaskView;
@property(retain, nonatomic) id cellData; // @synthesize cellData=_cellData;
@property(nonatomic) long long maxAllowVideoDuration; // @synthesize maxAllowVideoDuration=_maxAllowVideoDuration;
@property(nonatomic) _Bool enableToggleButtonCount; // @synthesize enableToggleButtonCount=_enableToggleButtonCount;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(nonatomic) __weak id <WBAssetImagePickerCellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
- (void).cxx_destruct;
- (void)livePhotoView:(id)arg1 didEndPlaybackWithStyle:(long long)arg2;
- (void)livePhotoView:(id)arg1 willBeginPlaybackWithStyle:(long long)arg2;
- (void)stopPlayLivePhotoIfNeed;
- (void)playLivePhotoIfNeed;
- (_Bool)isLivePhoto;
- (_Bool)isLivephotoOpened;
- (id)progressView;
- (void)finishDownLoadProgress;
- (void)updateDownLoadingUI;
- (void)updateImageDownLoadProgress:(double)arg1 cellData:(id)arg2;
- (void)tapPreLoadMaskView;
- (void)didClickLivePhotoToggleButton:(id)arg1;
- (void)_coverButtonTapped;
- (void)toggleButtonActionUpdateUI;
- (void)toggleButtonAction;
- (void)doToggleAnimation;
- (void)prepareForReuse;
- (struct CGPoint)accessibilityActivationPoint;
- (id)accessibilityLabel;
- (void)updateToggleButtonStateWithSelected:(_Bool)arg1;
@property(readonly, nonatomic) _Bool toggleButtonEnabled;
- (void)updateImageType:(unsigned long long)arg1;
- (void)setupDictionay:(id)arg1;
- (id)optionDict;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

