//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel, WBContributionAdvertModel;

@interface WBContributionDetailAdvertHeaderView : UIView
{
    CDUnknownBlockType _closeButtonActionBlock;
    UIView *_advertView;
    double _scrollY;
    UIView *_headerView;
    UILabel *_titleTextLabel;
    UILabel *_closeDescLabel;
    UIImageView *_adTagImageView;
    UIButton *_closeButton;
    UIView *_bottomSeperatorView;
    WBContributionAdvertModel *_advertModel;
}

@property(retain, nonatomic) WBContributionAdvertModel *advertModel; // @synthesize advertModel=_advertModel;
@property(retain, nonatomic) UIView *bottomSeperatorView; // @synthesize bottomSeperatorView=_bottomSeperatorView;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIImageView *adTagImageView; // @synthesize adTagImageView=_adTagImageView;
@property(retain, nonatomic) UILabel *closeDescLabel; // @synthesize closeDescLabel=_closeDescLabel;
@property(retain, nonatomic) UILabel *titleTextLabel; // @synthesize titleTextLabel=_titleTextLabel;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) double scrollY; // @synthesize scrollY=_scrollY;
@property(nonatomic) __weak UIView *advertView; // @synthesize advertView=_advertView;
@property(copy, nonatomic) CDUnknownBlockType closeButtonActionBlock; // @synthesize closeButtonActionBlock=_closeButtonActionBlock;
- (void).cxx_destruct;
- (void)closeButtonAction;
- (void)layoutSubviews;
- (void)updateViews;
- (void)updateWithAdvertModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

