//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WeiboCubeUGDixManager-Protocol.h"

@class NSMutableDictionary, NSString;

@interface WBDixManager : NSObject <WeiboCubeUGDixManager>
{
    _Bool _initializedEASDK;
    _Bool _initializedZYDSDK;
    _Bool _initializedUNSDK;
    NSString *_seq;
    NSMutableDictionary *_extraParams;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableDictionary *extraParams; // @synthesize extraParams=_extraParams;
@property(copy, nonatomic) NSString *seq; // @synthesize seq=_seq;
@property(nonatomic) _Bool initializedUNSDK; // @synthesize initializedUNSDK=_initializedUNSDK;
@property(nonatomic) _Bool initializedZYDSDK; // @synthesize initializedZYDSDK=_initializedZYDSDK;
@property(nonatomic) _Bool initializedEASDK; // @synthesize initializedEASDK=_initializedEASDK;
- (void).cxx_destruct;
- (id)getDixParams;
- (void)requestDixWithPhoneNumber:(id)arg1;
- (void)cu_requestDixWithAccesscode:(id)arg1;
- (void)requestDixWithAccesscode:(id)arg1;
- (id)securityNumber;
- (void)saveSecurityNumber:(id)arg1;
- (void)ct_getPreAuthWithScene:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)ct_getLoginTokenWithScene:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)ct_getPrecodeWithScene:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)initEASdk;
- (void)cu_getLoginTokenWithScene:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)cu_getPrecodeWithScene:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)initUNSDK;
- (void)cmcc_getLoginTokenWithScene:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)cmcc_GetPrecodeWithScene:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)initZYDSdk;
- (void)getPreAuthWithScene:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)getLoginTokenWithScene:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)getPrecodeWithScene:(id)arg1 Completion:(CDUnknownBlockType)arg2;
- (long long)networkType;
- (void)sendSMid:(id)arg1 seq:(id)arg2;
- (void)getSmId:(id)arg1;
- (void)messagePushNotification:(id)arg1;
- (void)logMessagePushWithType:(long long)arg1 jsonString:(id)arg2;
- (void)handlerCommand:(id)arg1 ident:(id)arg2;
- (void)startRequestDixInfo;
- (void)requestDixInfoWithCheckTime:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

