//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBActionContext.h"

@class WBFeedGroup, WBFeedListViewModel, WBFeedTimelineViewModel;

@interface WBFeedActionContext : WBActionContext
{
    WBFeedListViewModel *_listVM;
    WBFeedTimelineViewModel *_listViewModel;
    WBFeedGroup *_currentGroup;
}

@property(nonatomic) __weak WBFeedGroup *currentGroup; // @synthesize currentGroup=_currentGroup;
@property(nonatomic) __weak WBFeedTimelineViewModel *listViewModel; // @synthesize listViewModel=_listViewModel;
@property(nonatomic) __weak WBFeedListViewModel *listVM; // @synthesize listVM=_listVM;
- (void).cxx_destruct;

@end

