//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CRWeiboGameListener-Protocol.h"

@class NSString;
@protocol CRWeiboGameHandle;

@interface WBGBaseCommand : NSObject <CRWeiboGameListener>
{
    id <CRWeiboGameHandle> _handle;
}

@property(nonatomic) __weak id <CRWeiboGameHandle> handle; // @synthesize handle=_handle;
- (void).cxx_destruct;
- (void)queryPoint;
- (void)wbpointPay:(id)arg1;
- (void)wbsendComment:(id)arg1;
- (void)wbonShareAppMessage:(id)arg1 params:(id)arg2;
- (id)gameLaunchOptionsInfo:(id)arg1;
- (void)wbgetFollowStatus:(id)arg1;
- (void)wbnavigateToMiniProgram:(id)arg1 params:(id)arg2;
- (void)wbjumpUserPage:(id)arg1;
- (void)wbsetUserCloudStorage:(id)arg1;
- (void)wbgetFriendCloudStorage:(id)arg1;
- (void)wbprivateShareAppMessage:(id)arg1;
- (void)wbshareAppMessage:(id)arg1;
- (void)wbrequest:(id)arg1 params:(id)arg2;
- (void)wbbannerAdDestroy:(id)arg1;
- (void)wbbannerAdHide:(id)arg1;
- (void)wbbannerAdShow:(id)arg1 params:(id)arg2;
- (void)wbcreateBannerAd:(id)arg1;
- (void)wbcreateRewardedVideoAd:(id)arg1;
- (void)wblogin;
- (void)callback:(id)arg1 code:(long long)arg2 info:(id)arg3;
- (id)resultWithData:(id)arg1 result:(long long)arg2;
- (void)universalMethod:(id)arg1 methodName:(id)arg2 argNum:(int)arg3 arg1:(id)arg4 arg2:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

