//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WBTextViewDelegate-Protocol.h"

@class NSString, UIButton, UIImageView, UILabel, WBTextView;

@interface WBGHotCommentReplyView : UIView <WBTextViewDelegate>
{
    UIImageView *_topLine;
    UIView *_bgView;
    UILabel *_topicLbl;
    UIImageView *_sepLine;
    WBTextView *_textView;
    UIButton *_sendBtn;
    NSString *_commentName;
    NSString *_defaultComment;
}

@property(retain, nonatomic) NSString *defaultComment; // @synthesize defaultComment=_defaultComment;
@property(retain, nonatomic) NSString *commentName; // @synthesize commentName=_commentName;
@property(retain, nonatomic) UIButton *sendBtn; // @synthesize sendBtn=_sendBtn;
@property(retain, nonatomic) WBTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIImageView *sepLine; // @synthesize sepLine=_sepLine;
@property(retain, nonatomic) UILabel *topicLbl; // @synthesize topicLbl=_topicLbl;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UIImageView *topLine; // @synthesize topLine=_topLine;
- (void).cxx_destruct;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)hide;
- (void)show;
- (void)setupData;
- (void)layout;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textView:(id)arg1 willChangeHeight:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

