//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray, WBMediaUploadResult;
@protocol WBMediaUploadSessionUploadToken;

@interface WBMediaUploadSessionState : NSObject <NSCoding>
{
    _Bool _allSegmentsAdded;
    id <WBMediaUploadSessionUploadToken> _uploadToken;
    NSArray *_segmentsToBeUploaded;
    NSArray *_segmentsUploaded;
    WBMediaUploadResult *_uploadResult;
}

@property(readonly, nonatomic) WBMediaUploadResult *uploadResult; // @synthesize uploadResult=_uploadResult;
@property(readonly, nonatomic) _Bool allSegmentsAdded; // @synthesize allSegmentsAdded=_allSegmentsAdded;
@property(readonly, copy, nonatomic) NSArray *segmentsUploaded; // @synthesize segmentsUploaded=_segmentsUploaded;
@property(readonly, copy, nonatomic) NSArray *segmentsToBeUploaded; // @synthesize segmentsToBeUploaded=_segmentsToBeUploaded;
@property(readonly, nonatomic) id <WBMediaUploadSessionUploadToken> uploadToken; // @synthesize uploadToken=_uploadToken;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUploadToken:(id)arg1 segmentsToBeUploaded:(id)arg2 segmentsUploaded:(id)arg3 allSegmentsAdded:(_Bool)arg4 uploadResult:(id)arg5;
- (unsigned long long)indexOfSegment:(id)arg1;

@end

