//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBMLPnPAVPositionInfo : NSObject
{
    float _trackDuration;
    float _absTime;
    float _relTime;
}

@property(nonatomic) float relTime; // @synthesize relTime=_relTime;
@property(nonatomic) float absTime; // @synthesize absTime=_absTime;
@property(nonatomic) float trackDuration; // @synthesize trackDuration=_trackDuration;
- (void)setArray:(id)arg1;

@end

