//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WBMLDNSCache : NSObject
{
    NSString *hostName;
}

+ (id)instance;
- (void).cxx_destruct;
- (id)syncFetchIPAddressWithHost:(id)arg1;
- (void)asyncFetchIPAddressWithHost:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)task;
- (void)start;
- (void)remove;
- (id)get_by_name:(id)arg1;
- (void)update_by_name:(id)arg1 withName:(id)arg2;
- (void)startDNSCacheTimer;
- (void)setHost:(id)arg1;
- (id)getHost;

@end

