//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBNLBaseModel.h"

@class NSString, WBNLDiversionToYZBConfigModel;

@interface WBNLDiversionBarrageLayerConfigModel : WBNLBaseModel
{
    NSString *_template_text;
    WBNLDiversionToYZBConfigModel *_to_yizhibo;
}

@property(copy, nonatomic) WBNLDiversionToYZBConfigModel *to_yizhibo; // @synthesize to_yizhibo=_to_yizhibo;
@property(copy, nonatomic) NSString *template_text; // @synthesize template_text=_template_text;
- (void).cxx_destruct;

@end

