//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, WBOPTCacheConfig, WBTDFMDatabaseQueue;

@interface WBOPTDiskCache : NSObject
{
    NSString *_tableName;
    WBOPTCacheConfig *_cacheConfig;
    WBTDFMDatabaseQueue *_dbQueue;
}

+ (_Bool)checkTableName:(id)arg1;
@property(retain, nonatomic) WBTDFMDatabaseQueue *dbQueue; // @synthesize dbQueue=_dbQueue;
@property(retain, nonatomic) WBOPTCacheConfig *cacheConfig; // @synthesize cacheConfig=_cacheConfig;
@property(copy, nonatomic) NSString *tableName; // @synthesize tableName=_tableName;
- (void).cxx_destruct;
- (id)description;
- (id)_dbJoinedKeys:(id)arg1;
- (_Bool)removeItemsToFitCount:(unsigned long long)arg1;
- (_Bool)removeObjectsByKeyArray:(id)arg1;
- (_Bool)removeObjectByKey:(id)arg1;
- (unsigned long long)getCountFromTable;
- (id)getAllItems;
- (id)getObjectByKey:(id)arg1;
- (_Bool)saveObjects:(id)arg1;
- (_Bool)saveObjectWithKey:(id)arg1 object:(id)arg2;
- (void)close;
- (void)dropTable:(id)arg1;
- (void)clearTable:(id)arg1;
- (_Bool)isTableExists:(id)arg1;
- (void)createTable;
- (id)initWithConfig:(id)arg1;

@end

