//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBTableViewController.h"

#import "WBOperationTrackMangerDebugDelegate-Protocol.h"

@class NSMutableArray, NSString, WBFeedThrottle;
@protocol WBOPTDebugConsoleViewControllerDelegate;

@interface WBOPTDebugConsoleViewController : WBTableViewController <WBOperationTrackMangerDebugDelegate>
{
    id <WBOPTDebugConsoleViewControllerDelegate> _delegate;
    NSMutableArray *_dataArrar;
    WBFeedThrottle *_throttle;
}

@property(retain, nonatomic) WBFeedThrottle *throttle; // @synthesize throttle=_throttle;
@property(retain, nonatomic) NSMutableArray *dataArrar; // @synthesize dataArrar=_dataArrar;
@property(nonatomic) __weak id <WBOPTDebugConsoleViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)_callbackForActionType:(long long)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)logWithProperties:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

