//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBPageCardTrendViewModel.h"

@class NSString;

@interface WBPageCardUserTrendViewModel : WBPageCardTrendViewModel
{
    unsigned long long _nameLabelFontSize;
    double _cardCornerRedis;
    NSString *_deleteButtonImageKey;
    NSString *_highlitedDeleteButtonImageKey;
    double _avatarHeight;
    NSString *_cardBackgroundColorHexString;
    struct CGRect _avatarFrame;
}

@property(nonatomic) struct CGRect avatarFrame; // @synthesize avatarFrame=_avatarFrame;
@property(copy, nonatomic) NSString *cardBackgroundColorHexString; // @synthesize cardBackgroundColorHexString=_cardBackgroundColorHexString;
@property(nonatomic) double avatarHeight; // @synthesize avatarHeight=_avatarHeight;
@property(retain, nonatomic) NSString *highlitedDeleteButtonImageKey; // @synthesize highlitedDeleteButtonImageKey=_highlitedDeleteButtonImageKey;
@property(retain, nonatomic) NSString *deleteButtonImageKey; // @synthesize deleteButtonImageKey=_deleteButtonImageKey;
@property(nonatomic) double cardCornerRedis; // @synthesize cardCornerRedis=_cardCornerRedis;
@property(nonatomic) unsigned long long nameLabelFontSize; // @synthesize nameLabelFontSize=_nameLabelFontSize;
- (void).cxx_destruct;
- (struct CGRect)commonButtonFrame;
- (struct CGRect)textViewFrame;
- (struct CGRect)nameLabelFrame;
- (double)deleteButtonRightMargin;
- (double)deleteButtonTopMargin;
- (double)trendPageCardHeight;
- (id)init;

@end

