//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBModelObject.h"

@class NSDictionary, NSString;

@interface WBPageHotUnionEventModel : WBModelObject
{
    NSString *_identifier;
    NSString *_title;
    NSString *_color;
    NSString *_scheme;
    NSDictionary *_actionlog;
}

+ (id)eventArrayWithEventDictArray:(id)arg1;
@property(copy, nonatomic) NSDictionary *actionlog; // @synthesize actionlog=_actionlog;
@property(copy, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(copy, nonatomic) NSString *color; // @synthesize color=_color;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (_Bool)updateWithDictionary:(id)arg1;

@end

