//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSDictionary, WBPreloadObjectDictionaryNew;
@protocol NSCopying;

@interface WBPreloadModel : NSObject <NSCopying>
{
    NSDictionary *_extraParaDic;
    _Bool _retryAfterFailure;
    long long _retryTimes;
    WBPreloadObjectDictionaryNew *_preloadParamObj;
    id <NSCopying> _customInfo;
    NSArray *_preloadVersions;
}

@property(retain, nonatomic) NSArray *preloadVersions; // @synthesize preloadVersions=_preloadVersions;
@property(retain, nonatomic) NSDictionary *extraParaDic; // @synthesize extraParaDic=_extraParaDic;
@property(retain, nonatomic) id <NSCopying> customInfo; // @synthesize customInfo=_customInfo;
@property(retain, nonatomic) WBPreloadObjectDictionaryNew *preloadParamObj; // @synthesize preloadParamObj=_preloadParamObj;
@property(nonatomic) long long retryTimes; // @synthesize retryTimes=_retryTimes;
@property(nonatomic) _Bool retryAfterFailure; // @synthesize retryAfterFailure=_retryAfterFailure;
- (void).cxx_destruct;
- (void)clone:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

