//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBTableViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "WBLoginManagerProtocol-Protocol.h"
#import "WBRecommendUserCardViewDelegate-Protocol.h"
#import "WBRecommentMoreButtonCellDelegate-Protocol.h"
#import "WBRecommentPopFloatViewDelegate-Protocol.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSString, UIBarButtonItem, UIButton, UIImageView, UILabel, UIView, UIWindow, WBBatchFollowEngine, WBInterestFooterView, WBNewRecommendEngine, WBProgressHUD, WBRecommentPopFloatView, WBStyleButton, WBTableViewEmptyView;

@interface WBRecommendUsersViewController : WBTableViewController <UIScrollViewDelegate, WBLoginManagerProtocol, WBRecommendUserCardViewDelegate, WBRecommentPopFloatViewDelegate, WBRecommentMoreButtonCellDelegate>
{
    WBBatchFollowEngine *_batchFollowEngine;
    WBNewRecommendEngine *_recommendEngine;
    NSMutableArray *_selectedUsers;
    NSMutableArray *_recommendUsers;
    NSMutableArray *_recommendUsersTagArr;
    NSMutableDictionary *_recommendUsersGroupDic;
    NSMutableDictionary *_dataSourcerecommendUsersGroupDic;
    WBTableViewEmptyView *_errorView;
    WBProgressHUD *_hud;
    NSString *_startBtnTitle;
    NSString *_titleStr;
    NSString *_titlePic;
    NSString *_descStr;
    NSString *_scene;
    _Bool _isPushFromThirdRegister;
    _Bool _isPushFromThirdRegisterCloseProfile;
    _Bool _isPresentWhenVistorFirstOpen;
    _Bool _hasCheckedUser;
    _Bool _showSkipButton;
    _Bool _isShowLeftBackBtn;
    int _selectedUserCountLimit;
    int _selectedUserCountMaxLimit;
    long long _isNewUi;
    long long _isCancelSelect;
    _Bool isInLoginManager;
    _Bool _isShowedFloatView;
    _Bool _isShowedLoadMoreCell;
    _Bool _pressedHide;
    NSDictionary *_tagParams;
    UIView *_headerView;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    UIImageView *_titlePicImageView;
    WBStyleButton *_startButton;
    UIButton *_selectAllButton;
    UIBarButtonItem *_backButtonItem;
    NSString *_nextScheme;
    WBRecommentPopFloatView *_alertFloatView;
    NSString *_identifier;
    UIButton *_searchBarView;
    UIBarButtonItem *_leftBarButtonItem;
    NSMutableArray *_indexPaths;
    UIView *_backgroudContanerView;
    UIView *_backgroudContanerTopLineView;
    WBInterestFooterView *_grayFooterView;
    UIWindow *_baseWindow;
}

@property(retain, nonatomic) UIWindow *baseWindow; // @synthesize baseWindow=_baseWindow;
@property(retain, nonatomic) WBInterestFooterView *grayFooterView; // @synthesize grayFooterView=_grayFooterView;
@property(retain, nonatomic) UIView *backgroudContanerTopLineView; // @synthesize backgroudContanerTopLineView=_backgroudContanerTopLineView;
@property(retain, nonatomic) UIView *backgroudContanerView; // @synthesize backgroudContanerView=_backgroudContanerView;
@property(nonatomic) _Bool pressedHide; // @synthesize pressedHide=_pressedHide;
@property(retain, nonatomic) NSMutableArray *indexPaths; // @synthesize indexPaths=_indexPaths;
@property(retain, nonatomic) UIBarButtonItem *leftBarButtonItem; // @synthesize leftBarButtonItem=_leftBarButtonItem;
@property(retain, nonatomic) UIButton *searchBarView; // @synthesize searchBarView=_searchBarView;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) _Bool isShowedLoadMoreCell; // @synthesize isShowedLoadMoreCell=_isShowedLoadMoreCell;
@property(nonatomic) _Bool isShowedFloatView; // @synthesize isShowedFloatView=_isShowedFloatView;
@property(retain, nonatomic) WBRecommentPopFloatView *alertFloatView; // @synthesize alertFloatView=_alertFloatView;
@property(copy, nonatomic) NSString *nextScheme; // @synthesize nextScheme=_nextScheme;
@property(retain, nonatomic) UIBarButtonItem *backButtonItem; // @synthesize backButtonItem=_backButtonItem;
@property(retain, nonatomic) UIButton *selectAllButton; // @synthesize selectAllButton=_selectAllButton;
@property(retain, nonatomic) WBStyleButton *startButton; // @synthesize startButton=_startButton;
@property(retain, nonatomic) UIImageView *titlePicImageView; // @synthesize titlePicImageView=_titlePicImageView;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSDictionary *tagParams; // @synthesize tagParams=_tagParams;
@property(nonatomic) _Bool isInLoginManager; // @synthesize isInLoginManager;
- (void).cxx_destruct;
- (void)searchBarTouchInside;
- (void)clickSureButton:(id)arg1;
- (void)clickCancelButton:(id)arg1;
- (id)getLoadMoreFlagOfCurrentIndexPath:(id)arg1;
- (id)getUsersOfCurrentIndexPath:(id)arg1;
- (id)getRequestMoreParamsWithCurrentCell:(id)arg1;
- (void)updateRecommedUsersWithIsHasTagID:(_Bool)arg1 andTagID:(id)arg2 andNewRecommedUser:(id)arg3 withIndexPath:(id)arg4;
- (void)requestMoreRecommendUsers:(id)arg1;
- (void)showDefaultData:(id)arg1;
- (void)showMoreData:(id)arg1;
- (void)didClickedRecommendUserCard:(id)arg1 isSelected:(_Bool)arg2;
- (id)identifierOftabelViewCellWithIndexPath:(id)arg1;
- (id)getUserWithIndexPath:(id)arg1;
- (_Bool)isInterestSelectedAtIndexpath:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 newCellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)configViewsInfoWithContent:(id)arg1;
- (void)requestRecommendGroup;
- (id)getParamsWithSelectedUsers;
- (void)dismissAfterEvent;
- (void)updateStartButtonTitle:(_Bool)arg1;
- (void)dissmissPopFloatView;
- (void)showPopFloatAlertView;
- (void)updateSelectAllButton;
- (void)onTouchSelectAllButton:(id)arg1;
- (void)startButtonClicked:(id)arg1;
- (void)startButtonClickedInNewCategory:(id)arg1;
- (void)leftBarButtonItemPressed;
- (void)backButtonPressed:(id)arg1;
- (void)tableViewFrameDidChange:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)initErrorContentView;
- (void)configSubviewsFrame;
- (void)setupSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)updatePropertyWithPara:(id)arg1 context:(id)arg2 currentStep:(unsigned long long)arg3;
- (id)moduleID;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)generateWithOpenUrlLink:(id)arg1 inAppParas:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

