//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBViewController.h"

#import "PRLMTableViewWrapperDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "WBShopSearchSortViewDelegate-Protocol.h"

@class NSMutableArray, NSString, SNHTTPRequestOperationWrapper, UIButton, UITextField, UIView, WBPRLMTableViewWrapper, WBShopSearchSortView, WBTableView;

@interface WBShopSearchSquareViewController : WBViewController <UISearchBarDelegate, UITableViewDelegate, UITableViewDataSource, WBShopSearchSortViewDelegate, PRLMTableViewWrapperDelegate, UITextFieldDelegate>
{
    unsigned long long page;
    unsigned long long sortType;
    unsigned long long sortMode;
    NSString *_searchKey;
    UIView *_backView;
    UIView *_searchView;
    UITextField *_searchField;
    UIButton *_cancelBtn;
    WBShopSearchSortView *_sortView;
    WBPRLMTableViewWrapper *_prlmWrapper;
    WBTableView *_tableView;
    NSMutableArray *_dataArray;
    SNHTTPRequestOperationWrapper *_operationWrapper;
}

@property(retain, nonatomic) SNHTTPRequestOperationWrapper *operationWrapper; // @synthesize operationWrapper=_operationWrapper;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) WBTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) WBPRLMTableViewWrapper *prlmWrapper; // @synthesize prlmWrapper=_prlmWrapper;
@property(retain, nonatomic) WBShopSearchSortView *sortView; // @synthesize sortView=_sortView;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UITextField *searchField; // @synthesize searchField=_searchField;
@property(retain, nonatomic) UIView *searchView; // @synthesize searchView=_searchView;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) NSString *searchKey; // @synthesize searchKey=_searchKey;
- (void).cxx_destruct;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didTriggerLoadMoreInWrapper:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)sortBtnDidClick:(id)arg1;
- (void)fetchMore;
- (void)fetchData;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

