//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UILabel, WBContentImageView, WBShopProduct;

@interface WBShopWindowCollectionViewCell : UICollectionViewCell
{
    WBShopProduct *_product;
    WBContentImageView *_imgView;
    UILabel *_titleLabel;
    UILabel *_priceLabel;
}

@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) WBContentImageView *imgView; // @synthesize imgView=_imgView;
@property(retain, nonatomic) WBShopProduct *product; // @synthesize product=_product;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

