//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSMutableString, WBGPUImageEffectHandle, WBGPUImagePictureEffect;

@interface WBStoryImageExpoter : NSObject
{
    WBGPUImageEffectHandle *_stickerEffectHandle;
    WBGPUImageEffectHandle *_watermarkEffectHandle;
    WBGPUImageEffectHandle *_filterEffectHandle;
    WBGPUImageEffectHandle *_adaptionEffectHandle;
    WBGPUImagePictureEffect *_pictureEffect;
    NSMutableString *_traceString;
    NSMutableDictionary *_logDic;
}

@property(retain, nonatomic) NSMutableDictionary *logDic; // @synthesize logDic=_logDic;
@property(retain, nonatomic) NSMutableString *traceString; // @synthesize traceString=_traceString;
@property(retain, nonatomic) WBGPUImagePictureEffect *pictureEffect; // @synthesize pictureEffect=_pictureEffect;
@property(retain, nonatomic) WBGPUImageEffectHandle *adaptionEffectHandle; // @synthesize adaptionEffectHandle=_adaptionEffectHandle;
@property(retain, nonatomic) WBGPUImageEffectHandle *filterEffectHandle; // @synthesize filterEffectHandle=_filterEffectHandle;
@property(retain, nonatomic) WBGPUImageEffectHandle *watermarkEffectHandle; // @synthesize watermarkEffectHandle=_watermarkEffectHandle;
@property(retain, nonatomic) WBGPUImageEffectHandle *stickerEffectHandle; // @synthesize stickerEffectHandle=_stickerEffectHandle;
- (void).cxx_destruct;
- (void)exportImage:(id)arg1 size:(struct CGSize)arg2 filterID:(unsigned long long)arg3 sticker:(id)arg4 watermark:(id)arg5 isAspectRatioFixed9_16:(_Bool)arg6 callback:(CDUnknownBlockType)arg7;
- (void)exportImage:(id)arg1 filterID:(unsigned long long)arg2 callback:(CDUnknownBlockType)arg3;
- (id)init;

@end

