//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel, WBPlayCompletionButton;
@protocol WBSTOverlayReloadViewDelegate;

@interface WBSTOverlayReloadView : UIView
{
    id <WBSTOverlayReloadViewDelegate> _delegate;
    WBPlayCompletionButton *_reloadBtn;
    WBPlayCompletionButton *_feedbackBtn;
    UIView *_bgView;
    UILabel *_tipsLabel;
}

@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) WBPlayCompletionButton *feedbackBtn; // @synthesize feedbackBtn=_feedbackBtn;
@property(retain, nonatomic) WBPlayCompletionButton *reloadBtn; // @synthesize reloadBtn=_reloadBtn;
@property(nonatomic) __weak id <WBSTOverlayReloadViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)feedbackButtonPressed:(id)arg1;
- (void)reloadButtonPressed:(id)arg1;
- (void)layoutSubviews;
- (void)shouldShowFeedbackBtn:(_Bool)arg1;
- (id)init;

@end

