//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBStoryCaptureLogProcessInfo.h"

@class NSString;

@interface WBStoryCaptureLogSenseArProcessInfo : WBStoryCaptureLogProcessInfo
{
    _Bool _isFaceInCamera;
    NSString *_materialID;
    long long _beautifyDuration;
    long long _renderMaterialDuration;
}

@property(nonatomic) long long renderMaterialDuration; // @synthesize renderMaterialDuration=_renderMaterialDuration;
@property(nonatomic) long long beautifyDuration; // @synthesize beautifyDuration=_beautifyDuration;
@property(nonatomic) _Bool isFaceInCamera; // @synthesize isFaceInCamera=_isFaceInCamera;
@property(copy, nonatomic) NSString *materialID; // @synthesize materialID=_materialID;
- (void).cxx_destruct;

@end

