//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WBPageCardBubbleViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, WBPageCard, WBPageCardTrendViewModel;
@protocol WBTimelineTrendContentViewDelegate;

@interface WBTimelineTrendContentView : UIView <WBPageCardBubbleViewDelegate>
{
    _Bool _isNeedBubbleTop;
    _Bool _isNeedBackgroundImage;
    _Bool _isNeedSubEdgeInset;
    NSMutableArray *_bubbleViews;
    NSMutableArray *_cachedBubbleViews;
    NSMutableArray *_backgroundImageButton;
    id <WBTimelineTrendContentViewDelegate> _delegate;
    WBPageCard *_pageCard;
    WBPageCardTrendViewModel *_trendPageCardViewModel;
}

+ (Class)trendContentViewStyle;
+ (double)rowHeightOfDataObject:(id)arg1 tableView:(id)arg2 isListPage:(_Bool)arg3;
+ (long long)trendRowHeightOfTrendViewModel:(id)arg1 constraintWidth:(double)arg2 tableView:(id)arg3 isListPage:(_Bool)arg4;
@property(nonatomic) _Bool isNeedSubEdgeInset; // @synthesize isNeedSubEdgeInset=_isNeedSubEdgeInset;
@property(retain, nonatomic) WBPageCardTrendViewModel *trendPageCardViewModel; // @synthesize trendPageCardViewModel=_trendPageCardViewModel;
@property(nonatomic) _Bool isNeedBackgroundImage; // @synthesize isNeedBackgroundImage=_isNeedBackgroundImage;
@property(nonatomic) _Bool isNeedBubbleTop; // @synthesize isNeedBubbleTop=_isNeedBubbleTop;
@property(retain, nonatomic) WBPageCard *pageCard; // @synthesize pageCard=_pageCard;
@property(nonatomic) __weak id <WBTimelineTrendContentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableArray *backgroundImageButton; // @synthesize backgroundImageButton=_backgroundImageButton;
@property(retain, nonatomic) NSMutableArray *cachedBubbleViews; // @synthesize cachedBubbleViews=_cachedBubbleViews;
@property(retain, nonatomic) NSMutableArray *bubbleViews; // @synthesize bubbleViews=_bubbleViews;
- (void).cxx_destruct;
- (void)changeCard:(id)arg1;
- (unsigned long long)imageBackgroundBottomForCard:(id)arg1;
- (unsigned long long)imageBackgroundMiddleForCard:(id)arg1;
- (unsigned long long)imageBackgroundTopForCard:(id)arg1;
- (unsigned long long)imageBackgroundForCard:(id)arg1;
- (id)cardBackgroundColor:(_Bool)arg1 atIndex:(unsigned long long)arg2;
- (id)lineColorForTopLine:(_Bool)arg1 highlighted:(_Bool)arg2 atIndex:(unsigned long long)arg3;
- (id)_previousBackgroundButtonForCard:(id)arg1;
- (void)bubbleView:(id)arg1 mainView:(id)arg2 hasClick:(_Bool)arg3;
@property(readonly, nonatomic) NSArray *mediaAutoPlaySourceViews;
- (void)reloadUIElelments;
- (void)setBubbleViewsDelelgate:(id)arg1;
- (id)newBubbleViewFromCached;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)passEventToButtonDirectly;
- (id)newBubbleView;
- (_Bool)shouldForbiddenForGuest:(id)arg1;
- (void)pageCardSelected:(id)arg1;
- (void)layoutSubviews;
- (void)resetSubViewRect:(id)arg1;
- (void)refreshSubviewWithPageCard:(id)arg1;
- (void)resetPageCard:(id)arg1;
- (void)resetPageCard:(id)arg1 onlyRefresh:(_Bool)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

