//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBModelObject.h"

@class NSArray, NSDictionary, NSString, WBShortVideoAdInfo, WBShortVideoBottomBanner, WBShortVideoBottomButtonInfo, WBShortVideoCover, WBShortVideoMusicBanner, WBShortVideoShareInfo;

@interface WBVideoInfo : WBModelObject
{
    NSString *_text;
    unsigned long long _type;
    WBShortVideoAdInfo *_adInfo;
    WBShortVideoMusicBanner *_musicBanner;
    WBShortVideoBottomBanner *_bottomBanner;
    NSDictionary *_shareInfo;
    WBShortVideoBottomButtonInfo *_bottomButtonInfo;
    NSString *_sortTitle;
    NSString *_supportlandscapeMode;
    WBShortVideoShareInfo *_shareInfoMore;
    NSString *_videotopIcon;
    double _progressShowTime;
    WBShortVideoCover *_cover;
    NSArray *_buttons;
    NSArray *_triggerNames;
}

@property(copy, nonatomic) NSArray *triggerNames; // @synthesize triggerNames=_triggerNames;
@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(retain, nonatomic) WBShortVideoCover *cover; // @synthesize cover=_cover;
@property(nonatomic) double progressShowTime; // @synthesize progressShowTime=_progressShowTime;
@property(retain, nonatomic) NSString *videotopIcon; // @synthesize videotopIcon=_videotopIcon;
@property(retain, nonatomic) WBShortVideoShareInfo *shareInfoMore; // @synthesize shareInfoMore=_shareInfoMore;
@property(retain, nonatomic) NSString *supportlandscapeMode; // @synthesize supportlandscapeMode=_supportlandscapeMode;
@property(retain, nonatomic) NSString *sortTitle; // @synthesize sortTitle=_sortTitle;
@property(retain, nonatomic) WBShortVideoBottomButtonInfo *bottomButtonInfo; // @synthesize bottomButtonInfo=_bottomButtonInfo;
@property(retain, nonatomic) NSDictionary *shareInfo; // @synthesize shareInfo=_shareInfo;
@property(retain, nonatomic) WBShortVideoBottomBanner *bottomBanner; // @synthesize bottomBanner=_bottomBanner;
@property(retain, nonatomic) WBShortVideoMusicBanner *musicBanner; // @synthesize musicBanner=_musicBanner;
@property(retain, nonatomic) WBShortVideoAdInfo *adInfo; // @synthesize adInfo=_adInfo;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (_Bool)updateWithDictionary:(id)arg1;

@end

