//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBSegmentCardListViewController.h"

#import "WBHintBoardDelegate-Protocol.h"
#import "WBVideoPlaybackEventListener-Protocol.h"
#import "WBVideoPlayerControllerDelegate-Protocol.h"

@class NSDictionary, NSString, UIButton, WBGuideView, WBHomeNewStatusHintBoard, WBMediaAutoPlayManager, WBPageEngine, WBSearchEngine, WBVideoDiscoveryPlayerController;

@interface WBVideoDiscoveryCardListViewController : WBSegmentCardListViewController <WBVideoPlaybackEventListener, WBVideoPlayerControllerDelegate, WBHintBoardDelegate>
{
    _Bool _canShowPlaceholder;
    _Bool _autoplayVisibleRectAdjustmentDisabled;
    _Bool _showTopHintBoard;
    _Bool _needPreload;
    _Bool _userPullrefresh;
    _Bool _currentAccountChanged;
    _Bool _appearedOnce;
    WBPageEngine *_engine;
    NSDictionary *_requestParams;
    NSString *_fromType;
    WBVideoDiscoveryPlayerController *_playerController;
    id _sender;
    id _audioSessionHandler;
    WBHomeNewStatusHintBoard *_topHintBoard;
    WBMediaAutoPlayManager *_playbackManager;
    UIButton *_refreshTipsButton;
    WBSearchEngine *_searchEngine;
    WBGuideView *_historyGuide;
    double _refreshBeginTime;
    unsigned long long _refreshType;
}

@property(nonatomic) unsigned long long refreshType; // @synthesize refreshType=_refreshType;
@property(nonatomic) double refreshBeginTime; // @synthesize refreshBeginTime=_refreshBeginTime;
@property(retain, nonatomic) WBGuideView *historyGuide; // @synthesize historyGuide=_historyGuide;
@property(retain, nonatomic) WBSearchEngine *searchEngine; // @synthesize searchEngine=_searchEngine;
@property(retain, nonatomic) UIButton *refreshTipsButton; // @synthesize refreshTipsButton=_refreshTipsButton;
@property(retain, nonatomic) WBMediaAutoPlayManager *playbackManager; // @synthesize playbackManager=_playbackManager;
@property(nonatomic) _Bool appearedOnce; // @synthesize appearedOnce=_appearedOnce;
@property(nonatomic) _Bool currentAccountChanged; // @synthesize currentAccountChanged=_currentAccountChanged;
@property(nonatomic) _Bool userPullrefresh; // @synthesize userPullrefresh=_userPullrefresh;
@property(retain, nonatomic) WBHomeNewStatusHintBoard *topHintBoard; // @synthesize topHintBoard=_topHintBoard;
@property(retain, nonatomic) id audioSessionHandler; // @synthesize audioSessionHandler=_audioSessionHandler;
@property(retain, nonatomic) id sender; // @synthesize sender=_sender;
@property(retain, nonatomic) WBVideoDiscoveryPlayerController *playerController; // @synthesize playerController=_playerController;
@property(copy, nonatomic) NSString *fromType; // @synthesize fromType=_fromType;
@property(nonatomic) _Bool needPreload; // @synthesize needPreload=_needPreload;
@property(retain, nonatomic) NSDictionary *requestParams; // @synthesize requestParams=_requestParams;
@property(nonatomic) _Bool showTopHintBoard; // @synthesize showTopHintBoard=_showTopHintBoard;
@property(nonatomic) _Bool autoplayVisibleRectAdjustmentDisabled; // @synthesize autoplayVisibleRectAdjustmentDisabled=_autoplayVisibleRectAdjustmentDisabled;
@property(nonatomic) _Bool canShowPlaceholder; // @synthesize canShowPlaceholder=_canShowPlaceholder;
- (void).cxx_destruct;
- (_Bool)handleActionWithTableViewCell:(id)arg1 mainView:(id)arg2 actionType:(int)arg3 pageCard:(id)arg4 actionPara:(id)arg5 withButton:(id)arg6;
- (void)searchCardStateChanged:(id)arg1;
- (void)hideHistoryGuidIfNeed;
- (void)tapGuideView;
- (void)showHistoryGuidIfNeed;
- (_Bool)didPressLoadMoreFooterView:(id)arg1;
- (void)emptyViewStateDidChange:(id)arg1;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForCard:(id)arg2 atIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForCard:(id)arg2 atIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)bubbleTypeWithIndexPage:(id)arg1 tableView:(id)arg2;
- (_Bool)shouldShowPlaceholder;
- (void)videoPlayerController:(id)arg1 willExitFullscreenAnimated:(_Bool)arg2;
- (void)videoPlayerController:(id)arg1 willEnterFullscreenAnimated:(_Bool)arg2;
- (void)videoPlayerControllerDidPlayToEnd:(id)arg1;
- (void)videoPlayerController:(id)arg1 didTransitionFromPlaybackState:(long long)arg2 toPlaybackState:(long long)arg3;
- (_Bool)tagsView:(id)arg1 didSelectedAtIndex:(unsigned long long)arg2;
- (void)timelineItemDidDelete:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)accountDidChange;
- (void)removeStatus:(id)arg1;
- (void)volumeChanged:(id)arg1;
- (void)videoStatusCardViewResetCard:(id)arg1;
- (void)videoStatusCardVideoPressed:(id)arg1;
- (void)contactDidFollow:(id)arg1;
- (void)logLoadingFromCache:(id)arg1 result:(id)arg2;
- (id)_logParams;
- (id)analysisParameters;
- (void)refreshTipsButtonAction:(id)arg1;
- (void)hintboardWillDismiss:(id)arg1;
- (id)topHintBoardTipString;
- (void)didReceiveResult:(id)arg1 isLoadFromCache:(_Bool)arg2;
- (id)firstAvailableSearchCardWithCards:(id)arg1;
- (id)firstSearchCardCell;
- (id)firstAvailableVideoCardWithCards:(id)arg1;
- (void)didTriggerPullRefreshInWrapper:(id)arg1;
- (void)triggerPullRefresh;
- (_Bool)refresh:(unsigned long long)arg1;
- (_Bool)_validateSourceViewPosition:(id)arg1;
- (_Bool)validateSourceView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (struct CGRect)mediaAutoPlayVisibleRect;
- (id)playbackManagerWithPlayerController:(id)arg1;
- (id)mediaPlaybackService;
- (void)_finishSoundPlayback;
- (void)updateVideoAudioPlaybackState;
- (void)updateVideoPlayerControllerMuteState;
- (void)finishPlayback;
- (id)engine;
- (void)sendLog:(id)arg1 error:(id)arg2 isLoadFromCache:(_Bool)arg3;
- (void)configEngine:(id)arg1;
- (_Bool)isStoryList:(id)arg1;
- (_Bool)isPlayList;
- (_Bool)isFollowList;
- (void)viewWillLayoutSubviews;
- (void)reloadBeforAccountChange;
- (void)fetchDataIfNeeded;
- (void)logVideoDisappear;
- (void)logViewAppear;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (struct CGRect)workingAreaRect;
- (id)workingAreaHandlers;
- (_Bool)workingAreaDetectionEnabled;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

