//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBTableViewCell.h"

@class UILabel, UISwitch, WBVideoPlaylistItem;

@interface WBVideoSocialPlayerTrendHeaderCell : WBTableViewCell
{
    _Bool _autoplayEnabled;
    _Bool _enableAutoRefreshing;
    WBVideoPlaylistItem *_playlist;
    UILabel *_titleLabel;
    UILabel *_countLabel;
    UILabel *_tipLabel;
    UISwitch *_autoplaySwitch;
}

+ (double)rowHeightOfDataObject:(id)arg1 tableView:(id)arg2;
@property(retain, nonatomic) UISwitch *autoplaySwitch; // @synthesize autoplaySwitch=_autoplaySwitch;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) _Bool enableAutoRefreshing; // @synthesize enableAutoRefreshing=_enableAutoRefreshing;
@property(nonatomic) _Bool autoplayEnabled; // @synthesize autoplayEnabled=_autoplayEnabled;
@property(retain, nonatomic) WBVideoPlaylistItem *playlist; // @synthesize playlist=_playlist;
- (void).cxx_destruct;
- (void)autoplaySwitchAction:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 userInfo:(id)arg3;

@end

