//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBVideoPlaybackQualityItem-Protocol.h"

@class NSDictionary, NSString, NSURL, WBVideoManifest;

@protocol WBVideoPlaybackResource <WBVideoPlaybackQualityItem>
@property(readonly, nonatomic) WBVideoManifest *resourceManifest;
@property(readonly, nonatomic) long long resourceRecommendedReceiveBufferSize;
@property(readonly, nonatomic) long long resourceVideoDecoder;
@property(readonly, nonatomic) NSDictionary *resourceTranscodeInfo;
@property(readonly, nonatomic) NSString *resourceTranscodeLabel;
@property(readonly, nonatomic) long long resourceContentBytes;
@property(readonly, nonatomic) long long resourceCodecType;
@property(readonly, nonatomic) struct _NSRange resourcePrefetchRange;
@property(readonly, nonatomic) long long resourcePrefetchType;
@property(readonly, nonatomic) NSURL *resourcePlaybackURL;
@property(readonly, nonatomic) long long resourceBitrate;
@property(readonly, nonatomic) NSString *resourceIdentifier;
@property(readonly, nonatomic) NSString *resourceName;
@property(readonly, nonatomic) long long resourceType;
- (void)updateResourcePlaybackURL:(NSURL *)arg1;
@end

