//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBItemBasedObjectPreviewController.h"

@class NSDictionary;

@interface WBVideoELKDocumentViewController : WBItemBasedObjectPreviewController
{
    NSDictionary *_document;
}

@property(retain, nonatomic) NSDictionary *document; // @synthesize document=_document;
- (void).cxx_destruct;
- (void)validateDataChecksum;
- (void)showTools;
- (void)viewDidLoad;
- (id)initWithDocument:(id)arg1;

@end

