//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBCardListViewController.h"

@class NSDictionary;
@protocol WBVideoContributionAdvertViewControllerDelegate;

@interface WBVideoContributionAdvertViewController : WBCardListViewController
{
    id <WBVideoContributionAdvertViewControllerDelegate> _delegate;
    CDUnknownBlockType _viewDidLoadBock;
    CDUnknownBlockType _loadDateSucceedBlock;
    CDUnknownBlockType _dissmissBlock;
    double _offsetY;
    unsigned long long _expendType;
    NSDictionary *_extraParams;
    struct CGPoint _contentOffset;
    struct UIEdgeInsets _contentInset;
    struct UIEdgeInsets _scrollIndicatorInsets;
}

@property(retain, nonatomic) NSDictionary *extraParams; // @synthesize extraParams=_extraParams;
@property(nonatomic) unsigned long long expendType; // @synthesize expendType=_expendType;
@property(nonatomic) double offsetY; // @synthesize offsetY=_offsetY;
@property(copy, nonatomic) CDUnknownBlockType dissmissBlock; // @synthesize dissmissBlock=_dissmissBlock;
@property(copy, nonatomic) CDUnknownBlockType loadDateSucceedBlock; // @synthesize loadDateSucceedBlock=_loadDateSucceedBlock;
@property(copy, nonatomic) CDUnknownBlockType viewDidLoadBock; // @synthesize viewDidLoadBock=_viewDidLoadBock;
@property(nonatomic) __weak id <WBVideoContributionAdvertViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct UIEdgeInsets scrollIndicatorInsets; // @synthesize scrollIndicatorInsets=_scrollIndicatorInsets;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
@property(nonatomic) struct CGPoint contentOffset; // @synthesize contentOffset=_contentOffset;
- (void).cxx_destruct;
- (id)analysisParameters;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)finishLoadingData;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)configToolbarMenu;
- (void)configTableViewInsets;
- (_Bool)supportPullRefrash;
- (double)navigationHeight;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)updateTableviewContent;
- (void)contactEngineDidFollowContactNotification:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithOffsetY:(double)arg1 containerId:(id)arg2 params:(id)arg3 expendType:(unsigned long long)arg4;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;
- (struct CGRect)workingAreaRect;
- (id)workingAreaHandlers;
- (_Bool)workingAreaDetectionEnabled;

@end

