//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WBVideoDanmakuUserComposeCapabilityInfo : NSObject
{
    long long _capabilityType;
    NSString *_message;
    long long _cacheTime;
}

@property(nonatomic) long long cacheTime; // @synthesize cacheTime=_cacheTime;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic) long long capabilityType; // @synthesize capabilityType=_capabilityType;
- (void).cxx_destruct;
- (id)dictionaryWithValues;
- (id)initWithDictionary:(id)arg1;

@end

