//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class YXLiveVideoEncoder;

@protocol YXLiveVideoEncoderDelegate <NSObject>
- (void)videoEncoder:(YXLiveVideoEncoder *)arg1 sps:(char *)arg2 spsLength:(int)arg3 pps:(char *)arg4 ppsLength:(int)arg5;
- (void)videoEncoder:(YXLiveVideoEncoder *)arg1 data:(char *)arg2 dataLength:(int)arg3 isKey:(int)arg4;
@end

