//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAGradientLayer, NSTimer, UIButton, UIImageView, UILabel, YXLPKBufferProgressView, YXLiveTimerNew, YXLiveUserView, YXPKCountdownAnimtionView, YXPKUser;
@protocol YXLPKPandantCornerScoreViewDelegat;

@interface YXLPKPandantCornerScoreView : UIView
{
    _Bool isProphesyPK;
    _Bool isScoing;
    float currentRedScore;
    float currentBlueScore;
    id <YXLPKPandantCornerScoreViewDelegat> _delegate;
    unsigned long long _propCardStatus;
    UIImageView *_bgImgView;
    UIButton *_redPartBtn;
    UIButton *_bluePartBtn;
    YXLiveTimerNew *_scoringTimer;
    NSTimer *_hideCardTimer;
    YXPKUser *_redUser;
    YXPKUser *_blueUser;
    long long _countDown;
    long long _pktime;
    long long _totalTime;
    long long _prophesyTime;
    UIImageView *_scoreStatusImgView;
    UIImageView *_pktimeImgView;
    UILabel *_countDownLabel;
    CAGradientLayer *_redwinTimesGradientLayer;
    CAGradientLayer *_blueWinTimesGradientLayer;
    YXPKCountdownAnimtionView *_animationView;
    YXLiveUserView *_redUserHeadView;
    UIView *_redWinTimesView;
    UILabel *_redNameLabel;
    UILabel *_redWinTimesLabel;
    UILabel *_redScoreTitleLabel;
    UILabel *_redScoreNumLabel;
    UILabel *_redSpeedTitleLabel;
    UILabel *_redSpeedNumLabel;
    YXLPKBufferProgressView *_redSpeedBuffProgressView;
    YXLPKBufferProgressView *_redHideBuffProgressView;
    YXLiveUserView *_blueUserHeadView;
    UIView *_blueWinTimesView;
    UILabel *_blueNameLabel;
    UILabel *_blueWinTimesLabel;
    UILabel *_blueScoreTitleLabel;
    UILabel *_blueScoreNumLabel;
    UILabel *_blueSpeedTitleLabel;
    UILabel *_blueSpeedNumLabel;
    YXLPKBufferProgressView *_blueSpeedBuffProgressView;
    YXLPKBufferProgressView *_blueHideBuffProgressView;
    UIView *_prophesyView;
    UILabel *_prophesyTimeLabel;
    UIImageView *_prophesyTipImgView;
    UIButton *_clickProphesyBtn;
}

@property(retain, nonatomic) UIButton *clickProphesyBtn; // @synthesize clickProphesyBtn=_clickProphesyBtn;
@property(retain, nonatomic) UIImageView *prophesyTipImgView; // @synthesize prophesyTipImgView=_prophesyTipImgView;
@property(retain, nonatomic) UILabel *prophesyTimeLabel; // @synthesize prophesyTimeLabel=_prophesyTimeLabel;
@property(retain, nonatomic) UIView *prophesyView; // @synthesize prophesyView=_prophesyView;
@property(retain, nonatomic) YXLPKBufferProgressView *blueHideBuffProgressView; // @synthesize blueHideBuffProgressView=_blueHideBuffProgressView;
@property(retain, nonatomic) YXLPKBufferProgressView *blueSpeedBuffProgressView; // @synthesize blueSpeedBuffProgressView=_blueSpeedBuffProgressView;
@property(retain, nonatomic) UILabel *blueSpeedNumLabel; // @synthesize blueSpeedNumLabel=_blueSpeedNumLabel;
@property(retain, nonatomic) UILabel *blueSpeedTitleLabel; // @synthesize blueSpeedTitleLabel=_blueSpeedTitleLabel;
@property(retain, nonatomic) UILabel *blueScoreNumLabel; // @synthesize blueScoreNumLabel=_blueScoreNumLabel;
@property(retain, nonatomic) UILabel *blueScoreTitleLabel; // @synthesize blueScoreTitleLabel=_blueScoreTitleLabel;
@property(retain, nonatomic) UILabel *blueWinTimesLabel; // @synthesize blueWinTimesLabel=_blueWinTimesLabel;
@property(retain, nonatomic) UILabel *blueNameLabel; // @synthesize blueNameLabel=_blueNameLabel;
@property(retain, nonatomic) UIView *blueWinTimesView; // @synthesize blueWinTimesView=_blueWinTimesView;
@property(retain, nonatomic) YXLiveUserView *blueUserHeadView; // @synthesize blueUserHeadView=_blueUserHeadView;
@property(retain, nonatomic) YXLPKBufferProgressView *redHideBuffProgressView; // @synthesize redHideBuffProgressView=_redHideBuffProgressView;
@property(retain, nonatomic) YXLPKBufferProgressView *redSpeedBuffProgressView; // @synthesize redSpeedBuffProgressView=_redSpeedBuffProgressView;
@property(retain, nonatomic) UILabel *redSpeedNumLabel; // @synthesize redSpeedNumLabel=_redSpeedNumLabel;
@property(retain, nonatomic) UILabel *redSpeedTitleLabel; // @synthesize redSpeedTitleLabel=_redSpeedTitleLabel;
@property(retain, nonatomic) UILabel *redScoreNumLabel; // @synthesize redScoreNumLabel=_redScoreNumLabel;
@property(retain, nonatomic) UILabel *redScoreTitleLabel; // @synthesize redScoreTitleLabel=_redScoreTitleLabel;
@property(retain, nonatomic) UILabel *redWinTimesLabel; // @synthesize redWinTimesLabel=_redWinTimesLabel;
@property(retain, nonatomic) UILabel *redNameLabel; // @synthesize redNameLabel=_redNameLabel;
@property(retain, nonatomic) UIView *redWinTimesView; // @synthesize redWinTimesView=_redWinTimesView;
@property(retain, nonatomic) YXLiveUserView *redUserHeadView; // @synthesize redUserHeadView=_redUserHeadView;
@property(retain, nonatomic) YXPKCountdownAnimtionView *animationView; // @synthesize animationView=_animationView;
@property(retain, nonatomic) CAGradientLayer *blueWinTimesGradientLayer; // @synthesize blueWinTimesGradientLayer=_blueWinTimesGradientLayer;
@property(retain, nonatomic) CAGradientLayer *redwinTimesGradientLayer; // @synthesize redwinTimesGradientLayer=_redwinTimesGradientLayer;
@property(retain, nonatomic) UILabel *countDownLabel; // @synthesize countDownLabel=_countDownLabel;
@property(retain, nonatomic) UIImageView *pktimeImgView; // @synthesize pktimeImgView=_pktimeImgView;
@property(retain, nonatomic) UIImageView *scoreStatusImgView; // @synthesize scoreStatusImgView=_scoreStatusImgView;
@property(nonatomic) long long prophesyTime; // @synthesize prophesyTime=_prophesyTime;
@property(nonatomic) long long totalTime; // @synthesize totalTime=_totalTime;
@property(nonatomic) long long pktime; // @synthesize pktime=_pktime;
@property(nonatomic) long long countDown; // @synthesize countDown=_countDown;
@property(retain, nonatomic) YXPKUser *blueUser; // @synthesize blueUser=_blueUser;
@property(retain, nonatomic) YXPKUser *redUser; // @synthesize redUser=_redUser;
@property(retain, nonatomic) NSTimer *hideCardTimer; // @synthesize hideCardTimer=_hideCardTimer;
@property(retain, nonatomic) YXLiveTimerNew *scoringTimer; // @synthesize scoringTimer=_scoringTimer;
@property(retain, nonatomic) UIButton *bluePartBtn; // @synthesize bluePartBtn=_bluePartBtn;
@property(retain, nonatomic) UIButton *redPartBtn; // @synthesize redPartBtn=_redPartBtn;
@property(retain, nonatomic) UIImageView *bgImgView; // @synthesize bgImgView=_bgImgView;
@property(nonatomic) unsigned long long propCardStatus; // @synthesize propCardStatus=_propCardStatus;
@property(nonatomic) __weak id <YXLPKPandantCornerScoreViewDelegat> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)sizeWithText:(id)arg1 maxWidth:(double)arg2;
- (void)setAttributedTextLineSpacing:(float)arg1 label:(id)arg2;
- (void)updateWinTimesLabelValue;
- (void)ScoringcountDownFinish;
- (void)prophesyCountDownFinish;
- (void)prophesyPartTapClick:(id)arg1;
- (void)bluePartTapClick:(id)arg1;
- (void)redPartTapClick:(id)arg1;
- (void)removeHideBuffProgressView;
- (void)removeSpeedBuffProgressView:(_Bool)arg1;
- (void)updateScoreTitleStyle:(_Bool)arg1;
- (void)removePropHideCardStyle;
- (void)removePropSpeedUpCardAciton;
- (void)addPandantPKSpeedUpCardRed:(id)arg1 Blue:(id)arg2;
- (void)addPandantPKHidePropCardWithTime:(id)arg1;
- (void)updatePandantCornerScoreWithPKTime:(long long)arg1 prophesyTime:(long long)arg2 totalTime:(long long)arg3;
- (void)addScoreTextScaleAnimationWithRedScore:(double)arg1 BlueScore:(double)arg2;
- (void)updatePandantCornerScoreWithRedScore:(double)arg1 BlueScore:(double)arg2;
- (void)updatePandantCornerScoreProphesyWithTime:(long long)arg1;
- (void)updatePandantCornerScoringWithRedUser:(id)arg1 blueUser:(id)arg2;
- (void)updateScoringStatusWithRedUser:(id)arg1 blueUser:(id)arg2 pkTime:(long long)arg3 prophesyTime:(long long)arg4 totalTime:(long long)arg5;
- (void)timeHandler;
- (void)stopTime;
- (void)startTime;
- (void)updateProphesyCountDownLabel:(long long)arg1;
- (void)updatePKCountDownLabel:(long long)arg1;
- (void)showCountDown10sLOTiAnimation;
- (void)hiddenView;
- (void)viewUpdateConstraints;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)dealloc;

@end

