//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "YXCornerContainerPanelDelegate-Protocol.h"
#import "YXRedPacketCornerMarkDelegate-Protocol.h"
#import "YXRedPacketGrabBaseViewDelegate-Protocol.h"
#import "YXRedPacketGrabViewDelegate-Protocol.h"
#import "YXRedPacketPresenterDelegate-Protocol.h"
#import "YXRedPacketSendPresenterDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, UIView, YXCornerContainerPanel, YXLiveTimer, YXRedPacketConfigureModel, YXRedPacketCornerMark, YXRedPacketUserStatusModel;
@protocol OS_dispatch_queue, YXRedPacketManagerDelegate;

@interface YXRedPacketManager : NSObject <YXRedPacketPresenterDelegate, YXRedPacketCornerMarkDelegate, YXRedPacketSendPresenterDelegate, YXRedPacketGrabViewDelegate, YXCornerContainerPanelDelegate, YXRedPacketGrabBaseViewDelegate>
{
    NSObject<OS_dispatch_queue> *_syncQuene;
    _Bool isPking;
    _Bool isRequest;
    _Bool isShowAvatar;
    _Bool _isAnchor;
    _Bool _cornerisHidden;
    _Bool _isReRequest;
    _Bool _isVStarRPMarkShow;
    _Bool _isFromCorner;
    UIView *_redPacketSuperView;
    UIView *_rpMarkSuperView;
    NSString *_scid;
    NSString *_anchorId;
    NSString *_memberId;
    id <YXRedPacketManagerDelegate> _delegate;
    long long _grabViewFrom;
    NSString *_giftId;
    NSString *_giftName;
    YXRedPacketUserStatusModel *_userStatusModel;
    YXRedPacketConfigureModel *_configureModel;
    NSMutableArray *_redPacketArray;
    NSMutableDictionary *_redPacketDict;
    YXRedPacketCornerMark *_redPacketCornerMark;
    YXLiveTimer *_timer;
    YXLiveTimer *_getListTimer;
    NSMutableArray *_redPacketListArray;
    YXCornerContainerPanel *_cornerPanel;
}

@property(nonatomic) _Bool isFromCorner; // @synthesize isFromCorner=_isFromCorner;
@property(retain, nonatomic) YXCornerContainerPanel *cornerPanel; // @synthesize cornerPanel=_cornerPanel;
@property(retain, nonatomic) NSMutableArray *redPacketListArray; // @synthesize redPacketListArray=_redPacketListArray;
@property(retain, nonatomic) YXLiveTimer *getListTimer; // @synthesize getListTimer=_getListTimer;
@property(retain, nonatomic) YXLiveTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) YXRedPacketCornerMark *redPacketCornerMark; // @synthesize redPacketCornerMark=_redPacketCornerMark;
@property(retain, nonatomic) NSMutableDictionary *redPacketDict; // @synthesize redPacketDict=_redPacketDict;
@property(retain, nonatomic) NSMutableArray *redPacketArray; // @synthesize redPacketArray=_redPacketArray;
@property(nonatomic) _Bool isVStarRPMarkShow; // @synthesize isVStarRPMarkShow=_isVStarRPMarkShow;
@property(retain, nonatomic) YXRedPacketConfigureModel *configureModel; // @synthesize configureModel=_configureModel;
@property(nonatomic) _Bool isReRequest; // @synthesize isReRequest=_isReRequest;
@property(retain, nonatomic) YXRedPacketUserStatusModel *userStatusModel; // @synthesize userStatusModel=_userStatusModel;
@property(nonatomic) _Bool cornerisHidden; // @synthesize cornerisHidden=_cornerisHidden;
@property(copy, nonatomic) NSString *giftName; // @synthesize giftName=_giftName;
@property(copy, nonatomic) NSString *giftId; // @synthesize giftId=_giftId;
@property(nonatomic) long long grabViewFrom; // @synthesize grabViewFrom=_grabViewFrom;
@property(nonatomic) __weak id <YXRedPacketManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isAnchor; // @synthesize isAnchor=_isAnchor;
@property(copy, nonatomic) NSString *memberId; // @synthesize memberId=_memberId;
@property(copy, nonatomic) NSString *anchorId; // @synthesize anchorId=_anchorId;
@property(copy, nonatomic) NSString *scid; // @synthesize scid=_scid;
@property(nonatomic) __weak UIView *rpMarkSuperView; // @synthesize rpMarkSuperView=_rpMarkSuperView;
@property(nonatomic) __weak UIView *redPacketSuperView; // @synthesize redPacketSuperView=_redPacketSuperView;
- (void).cxx_destruct;
- (id)getCornerContainerPanel;
- (void)cornerContainerPanelDismiss:(id)arg1;
- (void)_disableRightSidePanel:(_Bool)arg1;
- (void)_requestRedPacketResource;
- (void)_requestRedPacketConfigure;
- (void)_showRedPasswordNotice:(id)arg1;
- (void)_handleWithSendErrorType:(long long)arg1;
- (void)redPacketSendPresenter:(id)arg1 sendError:(id)arg2;
- (void)redPacketSendPresenter:(id)arg1 sendFailure:(long long)arg2;
- (void)redPacketSendPresenter:(id)arg1 sendSuccess:(id)arg2;
- (void)getRedPacketConfigFailure;
- (void)getRedPacketConfigSuccess;
- (void)redPacketPresenter:(id)arg1 didConditionFailure:(id)arg2;
- (void)redPacketPresenter:(id)arg1 didOpenFailure:(id)arg2 isupdate:(_Bool)arg3;
- (void)redPacketPresenterDidOpenSuccess:(id)arg1;
- (void)redPacketPresenterDidTimeFinish:(id)arg1;
- (_Bool)redPacketPresenterGetUserFollowStatus:(id)arg1;
- (void)redPacketGrabViewJumpSchemes:(id)arg1;
- (void)redPacketGrabViewShopCashConditionClick:(id)arg1;
- (void)redPacketGrabViewPanelDismissed:(id)arg1;
- (void)closeGrabViewAndRemovePresenter:(id)arg1;
- (void)redPacketGrabViewPanelDismissed;
- (void)closePacketAndRemovePresenter:(id)arg1;
- (_Bool)redPacketCornerMarkCurrentRoomIsPK:(id)arg1;
- (void)redPacketCornerMark:(id)arg1 didEnterClick:(id)arg2;
- (void)removeAllRedPacketPresenter;
- (void)removeListnener:(id)arg1;
- (void)addListnener:(id)arg1;
- (_Bool)isAlreadyGrabRedPacket:(id)arg1;
- (_Bool)isHaveRedPacket:(id)arg1;
- (void)removeRedPacketPresenter:(id)arg1;
- (long long)redPacketArrayCount;
- (id)redPacketPressenterWithId:(id)arg1;
- (id)redPacketPressenterAtIndex:(long long)arg1;
- (id)firstRedPacketPressenter;
- (long long)formatPriorityKey:(id)arg1;
- (long long)formatCountDownTime:(id)arg1;
- (void)sortAudienceArray;
- (void)notificationListPanelReload;
- (void)addRedPacketPresenter:(id)arg1;
- (id)redPacketListPressenterAtSection:(long long)arg1 row:(long long)arg2;
- (long long)redPackListCountWithSection:(long long)arg1;
- (long long)redPackListSection;
- (void)formatRedPacketListArray;
- (void)liveRoomOrientationDidChange;
- (void)bindingWEiBoSuccessToOpenRedPacket:(id)arg1;
- (void)bindingWEiBoFaileBTn;
- (void)liveRoomOrientationDidChange:(_Bool)arg1;
- (void)redPacketChangeCornerMark:(id)arg1;
- (void)redPacketDismiss:(id)arg1;
- (void)addObservers;
- (void)stopGetListTime;
- (void)startGetListTimer;
- (void)timeFinish;
- (void)stopTime;
- (void)startTime;
- (void)willTransToFullScreen:(_Bool)arg1;
- (void)removeRedPacketMark;
- (void)refreshRedPacketMarkRedPoint;
- (void)refreshRedPacketMark:(id)arg1;
- (void)markShakeAnimation;
- (void)refreshCornerContainerFrame;
- (void)createRedPacketMark:(id)arg1;
- (void)autoRefreshRedPacketMark;
- (void)requestDeductPropCard:(id)arg1;
- (void)jumpWorldRedPacketrRoom:(id)arg1;
- (void)sendWorldRedPacket:(id)arg1 CardID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)receiverWorldRedPacketMessage:(id)arg1;
- (void)isAutoOpenWorldRedPacket:(id)arg1;
- (void)requestUserIsSendGift;
- (void)updateUserConditionStatus:(_Bool)arg1;
- (void)showCommandRedPacketCommentInputView;
- (void)showCommentInputView:(id)arg1 danMuOpen:(_Bool)arg2;
- (void)shopCashDoTaskWithType:(long long)arg1;
- (void)didConditionType:(long long)arg1;
- (double)getAfterDelayNumber;
- (void)showCommentCell:(id)arg1;
- (id)createRedPacketPresenter:(id)arg1;
- (void)displayRedPacket;
- (void)initData;
- (void)dowb_anaglsis_shopcashClick:(id)arg1 location:(id)arg2;
- (void)dowb_anaglsis_RedPacketMarkClick:(id)arg1;
- (void)dowb_anaglsis_shopcashShow:(id)arg1 location:(id)arg2;
- (void)dowb_anaglsis_RedPacketMarkShow:(id)arg1;
- (void)cleanManager;
- (void)requestCheckShopCashCondition:(id)arg1 isAutoGrab:(_Bool)arg2;
- (void)requestCurrentTrueLoveWithAnchorID:(id)arg1 scid:(id)arg2 success:(CDUnknownBlockType)arg3;
- (void)getUserIsSendGiftWithScid:(id)arg1 memberId:(id)arg2 response:(CDUnknownBlockType)arg3;
- (void)getLiveRoomRedPacketListWithAfter:(_Bool)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (void)openRedPacketGrabView:(id)arg1 isAutoGrab:(_Bool)arg2;
- (void)openRedPacketListView;
- (void)requestCurrentTrueLoveAndShowListView;
- (long long)redPacketCount:(id)arg1;
- (void)showRedPacketListView:(id)arg1;
- (void)showSendRedPacketViewWithFrom:(long long)arg1;
- (void)requestRedPacketList:(_Bool)arg1;
- (void)getRedPacketList:(_Bool)arg1;
- (_Bool)isShowRedPacketView;
- (_Bool)isShowTaskRedPacketView;
- (void)showRedPacketView:(id)arg1 isAutoGrab:(_Bool)arg2;
- (void)addRedPacketModel:(id)arg1;
- (void)refreshCacheRedPacketPresent:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

