INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = tweak_evplayer

tweak_evplayer_FILES = Tweak.x
tweak_evplayer_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
