//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FreshNewsEditBaseViewController.h"

#import "WBALAssetPickerContextManagerDelegate-Protocol.h"
#import "WBListPickerViewDelegate-Protocol.h"
#import "WBTopicPickerControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, UIControl, UILabel, UIView, WBALAssetPickerContextManager, WBEmotionListPickerView;

@interface FreshNewsEditInfoViewController : FreshNewsEditBaseViewController <WBALAssetPickerContextManagerDelegate, WBTopicPickerControllerDelegate, WBListPickerViewDelegate>
{
    _Bool _isChanged;
    WBALAssetPickerContextManager *_imageManager;
    WBEmotionListPickerView *_filedPicker;
    UIView *_footView;
    UIControl *_overlayView;
    UILabel *_sectionTitle;
    NSMutableArray *_filedArr;
}

@property(nonatomic) _Bool isChanged; // @synthesize isChanged=_isChanged;
@property(retain, nonatomic) NSMutableArray *filedArr; // @synthesize filedArr=_filedArr;
@property(retain, nonatomic) UILabel *sectionTitle; // @synthesize sectionTitle=_sectionTitle;
@property(retain, nonatomic) UIControl *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) UIView *footView; // @synthesize footView=_footView;
@property(retain, nonatomic) WBEmotionListPickerView *filedPicker; // @synthesize filedPicker=_filedPicker;
@property(retain, nonatomic) WBALAssetPickerContextManager *imageManager; // @synthesize imageManager=_imageManager;
- (void).cxx_destruct;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)saveInfoData;
- (void)listPickFinished:(id)arg1 withItemsDic:(id)arg2;
- (void)topicPickerControllerDidCancel:(id)arg1;
- (void)topicPickerController:(id)arg1 didFinishPickingTopic:(id)arg2;
- (void)WBALAssetPickerContextManagerCanceled:(id)arg1;
- (void)WBALAssetPickerContextManager:(id)arg1 finishedPickImageAttachments:(id)arg2;
- (void)showEditTextViewController;
- (void)showPickerView;
- (void)showTopicController;
- (void)titleAction:(id)arg1;
- (id)sectionTitleWithSection:(long long)arg1;
- (void)layoutFootView;
- (id)getSectionFooterViewInSection:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

