//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MessageQueueBySqlite, NSDateFormatter, NSDictionary, NSMutableDictionary, NSPredicate, NSString, NSTimer, SASDKRemoteConfig, SensorsAnalyticsPeople;
@protocol OS_dispatch_queue;

@interface SensorsAnalyticsSDK : NSObject
{
    long long _debugMode;
    unsigned long long _flushBulkSize;
    unsigned long long _flushInterval;
    unsigned long long _maxCacheSize;
    NSDateFormatter *_dateFormatter;
    _Bool _autoTrack;
    _Bool _appRelaunched;
    _Bool _showDebugAlertView;
    unsigned char _debugAlertViewHasShownNumber;
    NSDictionary *_launchOptions;
    long long _applicationState;
    _Bool _applicationWillResignActive;
    long long _autoTrackEventType;
    long long _networkTypePolicy;
    NSString *_deviceModel;
    NSString *_osVersion;
    NSString *_originServerUrl;
    _Bool _flushBeforeEnterBackground;
    long long _trackMode;
    SensorsAnalyticsPeople *_people;
    NSString *_distinctId;
    NSString *_loginId;
    NSString *_serverURL;
    NSString *_originalId;
    NSString *_firstDay;
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSDictionary *_automaticProperties;
    NSDictionary *_superProperties;
    NSMutableDictionary *_trackTimer;
    NSPredicate *_regexTestName;
    MessageQueueBySqlite *_messageQueue;
    NSTimer *_timer;
    SASDKRemoteConfig *_remoteConfig;
    CDUnknownBlockType _reqConfigBlock;
    unsigned long long _pullSDKConfigurationRetryMaxCount;
}

+ (id)getNetWorkStates;
+ (id)getUniqueHardwareId:(_Bool *)arg1;
+ (unsigned long long)getSystemUpTime;
+ (unsigned long long)getCurrentTime;
+ (id)sharedInstance;
+ (id)sharedInstanceWithServerURL:(id)arg1 andLaunchOptions:(id)arg2 andDebugMode:(long long)arg3;
+ (id)sharedInstanceWithServerURL:(id)arg1 andDebugMode:(long long)arg2;
@property(nonatomic) unsigned long long pullSDKConfigurationRetryMaxCount; // @synthesize pullSDKConfigurationRetryMaxCount=_pullSDKConfigurationRetryMaxCount;
@property(copy, nonatomic) CDUnknownBlockType reqConfigBlock; // @synthesize reqConfigBlock=_reqConfigBlock;
@property(retain, nonatomic) SASDKRemoteConfig *remoteConfig; // @synthesize remoteConfig=_remoteConfig;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain) MessageQueueBySqlite *messageQueue; // @synthesize messageQueue=_messageQueue;
@property(retain, nonatomic) NSPredicate *regexTestName; // @synthesize regexTestName=_regexTestName;
@property(retain, nonatomic) NSMutableDictionary *trackTimer; // @synthesize trackTimer=_trackTimer;
@property(retain) NSDictionary *superProperties; // @synthesize superProperties=_superProperties;
@property(retain) NSDictionary *automaticProperties; // @synthesize automaticProperties=_automaticProperties;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(copy) NSString *firstDay; // @synthesize firstDay=_firstDay;
@property(copy) NSString *originalId; // @synthesize originalId=_originalId;
@property(copy) NSString *serverURL; // @synthesize serverURL=_serverURL;
@property _Bool flushBeforeEnterBackground; // @synthesize flushBeforeEnterBackground=_flushBeforeEnterBackground;
@property(copy) NSString *loginId; // @synthesize loginId=_loginId;
@property(copy) NSString *distinctId; // @synthesize distinctId=_distinctId;
@property(retain) SensorsAnalyticsPeople *people; // @synthesize people=_people;
@property(nonatomic) long long trackMode; // @synthesize trackMode=_trackMode;
- (void).cxx_destruct;
- (void)clearKeychainData;
- (void)requestFunctionalManagermentConfigWithCompletion:(CDUnknownBlockType)arg1;
- (void)requestFunctionalManagermentConfigDelay:(double)arg1 index:(unsigned long long)arg2;
- (void)requestFunctionalManagermentConfig;
- (void)setSDKWithRemoteConfigDict:(id)arg1;
- (id)getSDKContollerUrl:(id)arg1;
- (void)enableLog;
- (void)enableLog:(_Bool)arg1;
- (void)deleteUser;
- (void)append:(id)arg1 by:(id)arg2;
- (void)increment:(id)arg1;
- (void)increment:(id)arg1 by:(id)arg2;
- (void)unset:(id)arg1;
- (void)setOnce:(id)arg1 to:(id)arg2;
- (void)set:(id)arg1 to:(id)arg2;
- (void)setOnce:(id)arg1;
- (void)set:(id)arg1;
- (void)applicationWillTerminateNotification:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)_enableAutoTrack;
- (void)setUpListeners;
- (long long)debugMode;
@property unsigned long long flushBulkSize;
- (void)stopFlushTimer;
- (void)startFlushTimer;
@property unsigned long long flushInterval;
- (void)archiveSuperProperties;
- (void)archiveFirstDay;
- (void)archiveLoginId;
- (void)archiveDistinctId;
- (void)unarchiveSuperProperties;
- (void)unarchiveFirstDay;
- (void)unarchiveLoginId;
- (void)unarchiveDistinctId;
- (id)unarchiveFromFile:(id)arg1;
- (void)unarchive;
- (id)currentSuperProperties;
- (void)clearSuperProperties;
- (void)unregisterSuperProperty:(id)arg1;
- (void)registerSuperProperties:(id)arg1;
- (id)collectAutomaticProperties;
- (_Bool)assertPropertyTypes:(id)arg1 withEventType:(id)arg2;
- (id)libVersion;
- (id)deviceModel;
- (void)identify:(id)arg1;
- (void)trackSignUp:(id)arg1;
- (void)trackSignUp:(id)arg1 withProperties:(id)arg2;
- (void)clearTrackTimer;
- (void)trackTimerEnd:(id)arg1 withProperties:(id)arg2;
- (void)trackTimerEnd:(id)arg1;
- (void)trackTimer:(id)arg1 withTimeUnit:(long long)arg2;
- (void)trackTimerBegin:(id)arg1 withTimeUnit:(long long)arg2;
- (void)trackTimerBegin:(id)arg1;
- (void)trackTimerStart:(id)arg1;
- (void)trackTimer:(id)arg1;
- (void)track:(id)arg1;
- (void)track:(id)arg1 withProperties:(id)arg2;
- (void)track:(id)arg1 withProperties:(id)arg2 withType:(id)arg3;
- (void)enqueueWithType:(id)arg1 andEvent:(id)arg2;
- (id)filePathForData:(id)arg1;
- (_Bool)isValidName:(id)arg1;
- (void)flush;
- (void)_flush:(_Bool)arg1;
- (void)flushByType:(id)arg1 withSize:(int)arg2 andFlushMethod:(CDUnknownBlockType)arg3;
- (void)showDebugInfoView:(_Bool)arg1;
- (void)ignoreAutoTrackEventType:(long long)arg1;
- (_Bool)isAutoTrackEventTypeIgnored:(long long)arg1;
- (_Bool)isAutoTrackEnabled;
- (void)enableAutoTrack:(long long)arg1;
- (void)enableAutoTrack;
- (void)resetAnonymousId;
- (id)anonymousId;
- (void)logout;
- (void)login:(id)arg1;
- (unsigned long long)getMaxCacheSize;
- (void)setMaxCacheSize:(unsigned long long)arg1;
- (long long)toNetworkType:(id)arg1;
- (void)setFlushNetworkPolicy:(long long)arg1;
- (_Bool)isFirstDay;
- (void)showDebugModeWarning:(id)arg1 withNoMoreButton:(_Bool)arg2;
- (id)debugModeToString:(long long)arg1;
- (void)disableDebugMode;
- (void)setServerUrl:(id)arg1;
- (id)getPresetProperties;
- (_Bool)isLaunchedPassively;
- (id)initWithServerURL:(id)arg1 andLaunchOptions:(id)arg2 andDebugMode:(long long)arg3;

@end

