//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WBAdSuspensionBaseViewDelegate-Protocol.h"

@class NSString, UIView, WBAdSuspensionBaseView;
@protocol WBAdSuspensionEngineDelegate;

@interface WBAdSuspensionViewEngine : NSObject <WBAdSuspensionBaseViewDelegate>
{
    UIView *_bottomView;
    id <WBAdSuspensionEngineDelegate> _adSuspensionDelegate;
    WBAdSuspensionBaseView *_baseView;
    unsigned long long _displayStyle;
    struct CGRect _frame;
}

@property(nonatomic) unsigned long long displayStyle; // @synthesize displayStyle=_displayStyle;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(retain, nonatomic) WBAdSuspensionBaseView *baseView; // @synthesize baseView=_baseView;
@property(nonatomic) __weak id <WBAdSuspensionEngineDelegate> adSuspensionDelegate; // @synthesize adSuspensionDelegate=_adSuspensionDelegate;
@property(readonly, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
- (void).cxx_destruct;
- (void)adSuspensionViewShouldMinimized:(id)arg1;
- (void)adSuspensionViewShouldExpand:(id)arg1;
- (void)didChangeToDisplayStyle:(unsigned long long)arg1;
- (void)refreshUIAnimationWithDisplayStyle:(unsigned long long)arg1 Animation:(_Bool)arg2;
- (void)reloadUIElementsByDic:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

