//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBContactContactsTableViewCell.h"

@class NSString;

@interface WBGroupChooseOwnerCell : WBContactContactsTableViewCell
{
    NSString *_searchText;
}

@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
- (void).cxx_destruct;
- (struct _NSRange)_rangeOfHighlightString:(id)arg1 targetString:(id)arg2;
- (void)_setupSearchHighlight;
- (void)setContact:(id)arg1;

@end

