//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBViewController.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WBSearchEngineDelegate-Protocol.h"

@class MMSearchBar, NSArray, NSString, WBDirectionalGroup, WBSearchEngine, WBSearchType, WBTableView;

@interface WBGroupChooseOwnerViewController : WBViewController <UISearchBarDelegate, UITableViewDelegate, UITableViewDataSource, WBSearchEngineDelegate>
{
    WBDirectionalGroup *_group;
    MMSearchBar *_searchBar;
    WBTableView *_tableView;
    WBSearchEngine *_searchEngine;
    WBSearchType *_searchType;
    NSArray *_searchResults;
}

@property(copy, nonatomic) NSArray *searchResults; // @synthesize searchResults=_searchResults;
@property(retain, nonatomic) WBSearchType *searchType; // @synthesize searchType=_searchType;
@property(retain, nonatomic) WBSearchEngine *searchEngine; // @synthesize searchEngine=_searchEngine;
@property(retain, nonatomic) WBTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) MMSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) WBDirectionalGroup *group; // @synthesize group=_group;
- (void).cxx_destruct;
- (id)searchTypeIndentifierForSearchEngine:(id)arg1;
- (id)apiPathForSearchSuggestOfSearchEngine:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)cancelButtonAction;
- (_Bool)_hasOwnerQualification;
- (_Bool)_hasSearchBarInput;
- (void)_loadSearchResultsWithText:(id)arg1;
- (void)_setupSearchEngine;
- (void)_setupTableView;
- (void)_setupSearchBar;
- (void)_setupNavigationItem;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

