//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBOpenUrlContextBase.h"

@class WBUGUserTaskView;

@interface WBOpenUrlUGAlertViewContext : WBOpenUrlContextBase
{
    WBUGUserTaskView *_taskView;
}

- (void).cxx_destruct;
- (void)getImageWithUrl:(id)arg1 closeIconUrl:(id)arg2 complete:(CDUnknownBlockType)arg3;
- (void)getImageWithUrl:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)_origin_startContext;
- (_Bool)isPresentInCardListVC;
- (id)backgroundUicode;
- (void)alertViewAction:(long long)arg1;
- (void)_startContext;
- (void)startContext;

@end

