//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBViewController.h"

#import "PRLMTableViewWrapperDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSString, SNHTTPRequestOperationWrapper, WBPRLMTableViewWrapper, WBTableView;

@interface WBShopHistoryViewController : WBViewController <UITableViewDelegate, UITableViewDataSource, PRLMTableViewWrapperDelegate>
{
    NSString *_fromPic;
    NSMutableArray *_selectedProductFromPic;
    WBTableView *_tableView;
    WBPRLMTableViewWrapper *_prlmWrapper;
    SNHTTPRequestOperationWrapper *_operationWrapper;
    NSMutableDictionary *_products;
    NSArray *_keyArray;
    long long _page;
}

@property(nonatomic) long long page; // @synthesize page=_page;
@property(retain, nonatomic) NSArray *keyArray; // @synthesize keyArray=_keyArray;
@property(retain, nonatomic) NSMutableDictionary *products; // @synthesize products=_products;
@property(retain, nonatomic) SNHTTPRequestOperationWrapper *operationWrapper; // @synthesize operationWrapper=_operationWrapper;
@property(retain, nonatomic) WBPRLMTableViewWrapper *prlmWrapper; // @synthesize prlmWrapper=_prlmWrapper;
@property(retain, nonatomic) WBTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *selectedProductFromPic; // @synthesize selectedProductFromPic=_selectedProductFromPic;
@property(copy, nonatomic) NSString *fromPic; // @synthesize fromPic=_fromPic;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didTriggerLoadMoreInWrapper:(id)arg1;
- (void)didTriggerPullRefreshInWrapper:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)fetchMore;
- (void)fetchData;
- (void)addShopCartView;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

