//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "WBShortVideoSharedContextEventListener-Protocol.h"

@class NSString, WBLittleVideoStoryVideoProgressView, WBShortVideoBaseCellModel, WBShortVideoSharedContext;

@interface WBShortVideoBaseCollectionCell : UICollectionViewCell <WBShortVideoSharedContextEventListener>
{
    _Bool _primaryCell;
    WBShortVideoBaseCellModel *_cellModel;
    WBShortVideoSharedContext *_sharedContext;
    WBLittleVideoStoryVideoProgressView *_progressView;
}

@property(nonatomic, getter=isPrimaryCell) _Bool primaryCell; // @synthesize primaryCell=_primaryCell;
@property(retain, nonatomic) WBLittleVideoStoryVideoProgressView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) __weak WBShortVideoSharedContext *sharedContext; // @synthesize sharedContext=_sharedContext;
@property(retain, nonatomic) WBShortVideoBaseCellModel *cellModel; // @synthesize cellModel=_cellModel;
- (void).cxx_destruct;
- (void)sharedContext:(id)arg1 didChangePlaybackInstruction:(unsigned long long)arg2;
- (id)dismissTransitionImage;
- (void)updateUIElements;
- (void)didUpdateStatusDetail;
- (void)configWithCellModel:(id)arg1 sharedContext:(id)arg2;
- (void)performPlay;
- (void)performPause;
- (void)didResignPrimaryCell;
- (void)didBecomePrimaryCell;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

