//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBSTVideoBaseViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WBSTSmallVideoCollectionDataProviderDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSMutableSet, NSString, WBCustomActionSheet, WBSTCardListNewHeaderView, WBSTCardListNewNavBar, WBSTCardListNewStore, WBSTCardListTableView, WBSTCollectionModel, WBSTSmallVideoCollectionDataProvider;

@interface WBSTVideoCollectionsViewController : WBSTVideoBaseViewController <UITableViewDelegate, UITableViewDataSource, UIScrollViewDelegate, WBSTSmallVideoCollectionDataProviderDelegate>
{
    _Bool _isNeedScrollMiddle;
    _Bool _isCanLoadMore;
    WBSTCardListTableView *_tableView;
    WBSTSmallVideoCollectionDataProvider *_dataProvider;
    WBSTCardListNewHeaderView *_tableHeaderView;
    WBSTCardListNewNavBar *_customNavigationBar;
    WBSTCardListNewStore *_store;
    NSArray *_collections;
    WBSTCollectionModel *_collectionModel;
    WBCustomActionSheet *_moreButtonActionSheet;
    NSMutableArray *_cardListData;
    NSString *_next_cursor;
    NSString *_pre_cursor;
    NSString *_mid;
    WBSTCardListTableView *_myTableView;
    NSMutableSet *_animationDatas;
    NSMutableSet *_willDisplayCellIndex;
    long long _preDataCount;
}

@property(nonatomic) long long preDataCount; // @synthesize preDataCount=_preDataCount;
@property(retain, nonatomic) NSMutableSet *willDisplayCellIndex; // @synthesize willDisplayCellIndex=_willDisplayCellIndex;
@property(nonatomic) _Bool isCanLoadMore; // @synthesize isCanLoadMore=_isCanLoadMore;
@property(retain, nonatomic) NSMutableSet *animationDatas; // @synthesize animationDatas=_animationDatas;
@property(nonatomic) _Bool isNeedScrollMiddle; // @synthesize isNeedScrollMiddle=_isNeedScrollMiddle;
@property(retain, nonatomic) WBSTCardListTableView *myTableView; // @synthesize myTableView=_myTableView;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
@property(copy, nonatomic) NSString *pre_cursor; // @synthesize pre_cursor=_pre_cursor;
@property(copy, nonatomic) NSString *next_cursor; // @synthesize next_cursor=_next_cursor;
@property(retain, nonatomic) NSMutableArray *cardListData; // @synthesize cardListData=_cardListData;
@property(retain, nonatomic) WBCustomActionSheet *moreButtonActionSheet; // @synthesize moreButtonActionSheet=_moreButtonActionSheet;
@property(retain, nonatomic) WBSTCollectionModel *collectionModel; // @synthesize collectionModel=_collectionModel;
@property(retain, nonatomic) NSArray *collections; // @synthesize collections=_collections;
@property(retain, nonatomic) WBSTCardListNewStore *store; // @synthesize store=_store;
@property(retain, nonatomic) WBSTCardListNewNavBar *customNavigationBar; // @synthesize customNavigationBar=_customNavigationBar;
@property(retain, nonatomic) WBSTCardListNewHeaderView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) WBSTSmallVideoCollectionDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
@property(retain, nonatomic) WBSTCardListTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (id)uiCode;
- (void)showEmptyView;
- (void)showNetError:(id)arg1;
- (void)filterData:(id)arg1 preData:(_Bool)arg2;
- (void)selectedCell;
- (void)dataProviderLoadFavoriteStoreDataFinished:(id)arg1;
- (void)dataProviderLoadHeaderDataFinished:(id)arg1 error:(id)arg2;
- (void)dataProviderLoadListDataFinished:(id)arg1 error:(id)arg2;
- (void)dataProviderLoadPreListDataFinished:(id)arg1 error:(id)arg2;
- (void)retryRequest;
- (void)requestFavoriteAction;
- (void)actionCopylink;
- (void)jumpToProfile:(id)arg1;
- (void)shareButtonPressed:(id)arg1;
- (void)favoriteButtonAction:(id)arg1;
- (void)backButtonPressed:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)canPreLoadData:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithOpenUrlLink:(id)arg1 inAppParas:(struct NSMutableDictionary *)arg2;
- (void)dealloc;
- (struct CGRect)workingAreaRect;
- (id)workingAreaHandlers;
- (_Bool)workingAreaDetectionEnabled;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

