//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, WBStatus, WBTimelineAttributedTextView, WBVideoDanmakuLikeButtonLottie;

@interface WBVideoDanmakuActionView : UIView
{
    WBStatus *_status;
    CDUnknownBlockType _tapActionBlock;
    CDUnknownBlockType _reportButtonActionBlock;
    CDUnknownBlockType _likeButtonActionBlock;
    CDUnknownBlockType _lockRotationBlock;
    WBTimelineAttributedTextView *_textView;
    WBVideoDanmakuLikeButtonLottie *_likeButton;
    UIButton *_reportButton;
    UIView *_displayBaackView;
}

@property(retain, nonatomic) UIView *displayBaackView; // @synthesize displayBaackView=_displayBaackView;
@property(retain, nonatomic) UIButton *reportButton; // @synthesize reportButton=_reportButton;
@property(retain, nonatomic) WBVideoDanmakuLikeButtonLottie *likeButton; // @synthesize likeButton=_likeButton;
@property(retain, nonatomic) WBTimelineAttributedTextView *textView; // @synthesize textView=_textView;
@property(copy, nonatomic) CDUnknownBlockType lockRotationBlock; // @synthesize lockRotationBlock=_lockRotationBlock;
@property(copy, nonatomic) CDUnknownBlockType likeButtonActionBlock; // @synthesize likeButtonActionBlock=_likeButtonActionBlock;
@property(copy, nonatomic) CDUnknownBlockType reportButtonActionBlock; // @synthesize reportButtonActionBlock=_reportButtonActionBlock;
@property(copy, nonatomic) CDUnknownBlockType tapActionBlock; // @synthesize tapActionBlock=_tapActionBlock;
@property(retain, nonatomic) WBStatus *status; // @synthesize status=_status;
- (void).cxx_destruct;
- (void)unlockRotation;
- (void)lockRotation;
- (double)getMaxTextViewWidthWithDynamicWidth:(double)arg1;
- (void)dismissWithMoveDuration:(double)arg1 delay:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dismissWithDuration:(double)arg1 delay:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showWithDuration:(double)arg1 danmakuId:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (double)getAllViewSpace;
- (void)likeButtonPressed:(id)arg1;
- (void)reportButtonAction:(id)arg1;
- (void)uptateVideoDanmakuActionViewDisplay:(id)arg1 contenText:(id)arg2 centerY:(double)arg3;
- (void)layoutSubviews;
- (void)htapAction:(id)arg1;
- (void)tapAction:(id)arg1;
- (void)addTapGesture;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

