//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBVideoProgressBarBaseSubPlugin.h"

@class UIButton, UILabel, UIView;
@protocol WBVideoProgressBarDanmakuComposePluginDelegate;

@interface WBVideoProgressBarDanmakuComposePlugin : WBVideoProgressBarBaseSubPlugin
{
    _Bool _isAnimating;
    id <WBVideoProgressBarDanmakuComposePluginDelegate> _delegate;
    UIButton *_danmakuButton;
    UIButton *_composeButton;
    UIView *_bgView;
    UILabel *_placeholderLabel;
}

@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(retain, nonatomic) UILabel *placeholderLabel; // @synthesize placeholderLabel=_placeholderLabel;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UIButton *composeButton; // @synthesize composeButton=_composeButton;
@property(retain, nonatomic) UIButton *danmakuButton; // @synthesize danmakuButton=_danmakuButton;
@property(nonatomic) __weak id <WBVideoProgressBarDanmakuComposePluginDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)composeButtonPressed:(id)arg1;
- (void)resetSpeedButtonText;
- (void)userComposeCapabilityInfoChangedNotification:(id)arg1;
- (void)videoPlayerController:(id)arg1 willEnterFullscreenAnimated:(_Bool)arg2;
- (void)danmakuAction:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)updateDanmakuButtonDisplayWithState:(_Bool)arg1;
- (void)showCommentViewWithIsOpen:(_Bool)arg1 withIsAnimal:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

