//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBTableViewCell.h"

#import "WBVideoVideoInfoViewDelegate-Protocol.h"

@class NSString, WBVideoVideoInfoView, WBVideoVideoInfoViewModel;
@protocol WBVideoVideoListTableViewCellDelegate;

@interface WBVideoVideoListTableViewCell : WBTableViewCell <WBVideoVideoInfoViewDelegate>
{
    id <WBVideoVideoListTableViewCellDelegate> _delegate;
    WBVideoVideoInfoViewModel *_cellModel;
    WBVideoVideoInfoView *_videoView;
}

@property(retain, nonatomic) WBVideoVideoInfoView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) WBVideoVideoInfoViewModel *cellModel; // @synthesize cellModel=_cellModel;
@property(nonatomic) __weak id <WBVideoVideoListTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)videoInfoView:(id)arg1 didPressMoreButton:(id)arg2;
- (void)reloadUIElements:(id)arg1;
- (void)updateEditStaus;
- (_Bool)usesCustomSelectedBackgroundView;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

