//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBModelObject.h"

@class NSDictionary, NSString;

@interface WBVideoAlbumBannerItem : WBModelObject
{
    NSString *_imageURL;
    NSString *_scheme;
    NSString *_link;
    NSString *_app_scheme;
    NSDictionary *_actionLog;
}

+ (_Bool)isValidForDictionary:(id)arg1;
@property(copy, nonatomic) NSDictionary *actionLog; // @synthesize actionLog=_actionLog;
@property(copy, nonatomic) NSString *app_scheme; // @synthesize app_scheme=_app_scheme;
@property(copy, nonatomic) NSString *link; // @synthesize link=_link;
@property(copy, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(copy, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (_Bool)updateWithJSONDictionary:(id)arg1;
- (_Bool)updateWithDictionary:(id)arg1;
- (void)_updateWithDict:(id)arg1;

@end

