//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBVideoPlayerItemLoadingOptions.h"

@class NSString;
@protocol WBVideoPlaybackResource;

@interface WBVideoCachedPlayerItemLoadingOptions : WBVideoPlayerItemLoadingOptions
{
    long long _cachedPlaybackResourceType;
    id <WBVideoPlaybackResource> _preferredPlaybackResource;
    NSString *_preferredPlaybackResourceCacheKey;
}

@property(copy, nonatomic) NSString *preferredPlaybackResourceCacheKey; // @synthesize preferredPlaybackResourceCacheKey=_preferredPlaybackResourceCacheKey;
@property(retain, nonatomic) id <WBVideoPlaybackResource> preferredPlaybackResource; // @synthesize preferredPlaybackResource=_preferredPlaybackResource;
@property(nonatomic) long long cachedPlaybackResourceType; // @synthesize cachedPlaybackResourceType=_cachedPlaybackResourceType;
- (void).cxx_destruct;
- (id)selectPlaybackResourceFromResources:(id)arg1 videoItem:(id)arg2;
- (id)playbackResourcesByAddingResource:(id)arg1 toResources:(id)arg2 videoItem:(id)arg3;
- (id)customResourcesFromResources:(id)arg1 videoItem:(id)arg2;
- (unsigned long long)supportManifestProtocols;

@end

