//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBXAbstractModule.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIAlertAction, WBAlertController;

@interface WBXMultiChooseDialogMoudule : WBXAbstractModule <UITextFieldDelegate>
{
    WBAlertController *_alertController;
    NSString *_alert;
    NSString *_regex;
    UIAlertAction *_actionConfirm;
}

+ (id)wx_export_method_192;
+ (id)wx_export_method_191;
+ (id)wx_export_method_190;
@property(retain, nonatomic) UIAlertAction *actionConfirm; // @synthesize actionConfirm=_actionConfirm;
@property(retain, nonatomic) NSString *regex; // @synthesize regex=_regex;
@property(retain, nonatomic) NSString *alert; // @synthesize alert=_alert;
@property(retain, nonatomic) WBAlertController *alertController; // @synthesize alertController=_alertController;
- (void).cxx_destruct;
- (_Bool)validString:(id)arg1 withRegex:(id)arg2;
- (id)allSubview:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (void)showInputDialog:(id)arg1;
- (void)showTextDescDialog:(id)arg1;
- (void)showMultiChoiceDialog:(id)arg1 callback:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

