//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBXAbstractModule.h"

@interface WBXTabbarModule : WBXAbstractModule
{
}

+ (id)wx_export_method_17;
+ (id)wx_export_method_16;
+ (id)wx_export_method_15;
+ (id)wx_export_method_14;
+ (id)wx_export_method_13;
+ (id)wx_export_method_12;
- (void)setTabBarStyle:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)hideTabBarRedDot:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)showTabBarRedDot:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)setTabBar:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)removeTabBarBadge:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)setTabBarBadge:(id)arg1 callback:(CDUnknownBlockType)arg2;

@end

