//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "YXSDKLivePlayerDelegate-Protocol.h"

@class NSString, UIView, YXSDKLivePlayer;

@interface YXTBLivePlayerController : NSObject <YXSDKLivePlayerDelegate>
{
    YXSDKLivePlayer *_yzbPlayer;
    int _mediaPlayerStatusID;
    unsigned long long _mediaPlayerEventID;
    unsigned long long _mediaPlayerDataID;
    _Bool _isPlaying;
    CDUnknownBlockType _MediaPlayerEvent;
    CDUnknownBlockType _MediaPlayerStatus;
    CDUnknownBlockType _MediaPlayerData;
    UIView *_playerView;
    NSString *_urlString;
}

+ (id)dictionaryWithJsonString:(id)arg1;
@property(retain, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(retain, nonatomic) UIView *playerView; // @synthesize playerView=_playerView;
@property(copy, nonatomic) CDUnknownBlockType MediaPlayerData; // @synthesize MediaPlayerData=_MediaPlayerData;
@property(copy, nonatomic) CDUnknownBlockType MediaPlayerStatus; // @synthesize MediaPlayerStatus=_MediaPlayerStatus;
@property(copy, nonatomic) CDUnknownBlockType MediaPlayerEvent; // @synthesize MediaPlayerEvent=_MediaPlayerEvent;
- (void).cxx_destruct;
- (int)getPlayerStatus;
- (id)playUrl;
- (void)setMediaPlayerDataCallback:(CDUnknownBlockType)arg1;
- (void)setMediaPlayerStatusCallback:(CDUnknownBlockType)arg1;
- (void)setMediaPlayerEventCallback:(CDUnknownBlockType)arg1;
- (void)onPlayerSeiDataCallback:(char *)arg1 seiSize:(int)arg2;
- (void)onPlayerCustomVideoDataCallback:(int)arg1 extraData:(char *)arg2 extraSize:(int)arg3;
- (void)onPlayerVideoDataCallback:(struct opaqueCMSampleBuffer *)arg1;
- (void)onPlayerAudioDataCallback:(struct opaqueCMSampleBuffer *)arg1;
- (void)onPlayerLogCallback:(int)arg1 msg:(id)arg2;
- (void)onPlayerEventCallback:(int)arg1 msg:(id)arg2;
- (void)onPlayerWorkingStateCallback:(int)arg1 msg:(id)arg2;
- (void)shutdown;
- (void)stop;
- (void)play;
- (void)setPlayUrl:(id)arg1;
- (id)initWithPlayerView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

