//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSString, YXWBStarRedPacketCornerMarkPresenter;

@protocol YXWBStarRedPacketCornerMarkPresenterDelegate <NSObject>
- (void)presenterResponseEmptyRedPacket:(YXWBStarRedPacketCornerMarkPresenter *)arg1;
- (void)presenter:(YXWBStarRedPacketCornerMarkPresenter *)arg1 followUserList:(NSArray *)arg2;
- (void)presenter:(YXWBStarRedPacketCornerMarkPresenter *)arg1 refreshCornerMark:(_Bool)arg2 redPacketInfo:(NSDictionary *)arg3;
- (void)presenterDidFinishCountDown:(YXWBStarRedPacketCornerMarkPresenter *)arg1;
- (void)presenter:(YXWBStarRedPacketCornerMarkPresenter *)arg1 timeUpdated:(NSString *)arg2;
@end

