//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@class ZKScrollViewObject;

@interface ZKScrollView : UIScrollView
{
    struct CGPoint _changedOffset;
    ZKScrollViewObject *_object;
    long long _viewId;
    struct _ZKIsolate *_isolate;
}

@property(nonatomic) struct _ZKIsolate *isolate; // @synthesize isolate=_isolate;
@property(nonatomic) long long viewId; // @synthesize viewId=_viewId;
- (void).cxx_destruct;
- (void)ZKViewSetViewId:(long long)arg1 isolate:(void *)arg2;
- (void)setContentOffset:(struct CGPoint)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

