//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "BUNativeExpressRewardedVideoAdViewDelegate-Protocol.h"
#import "BURewardedVideoWebViewDelegate-Protocol.h"

@class BUNativeExpressRewardedVideoAdDisplayViewController, BUNativeExpressRewardedVideoAdView, BURewardedVideoWebViewController, NSString;
@protocol BUNativeExpressVideoAdDelegate;

@interface BUNativeExpressRewardedVideoAdViewController : UIViewController <BURewardedVideoWebViewDelegate, BUNativeExpressRewardedVideoAdViewDelegate>
{
    _Bool _isRewardedVideo;
    id <BUNativeExpressVideoAdDelegate> _rewardedVideoAd;
    BUNativeExpressRewardedVideoAdView *_expressAdView;
    UIViewController *_currentViewController;
    BUNativeExpressRewardedVideoAdDisplayViewController *_rewardedVideoDisplayViewController;
    BURewardedVideoWebViewController *_rewardedVideoWebViewController;
    unsigned long long _systemOrientation;
    unsigned long long _videoOrientation;
    unsigned long long _childTransform;
}

@property(nonatomic) unsigned long long childTransform; // @synthesize childTransform=_childTransform;
@property(nonatomic) unsigned long long videoOrientation; // @synthesize videoOrientation=_videoOrientation;
@property(nonatomic) unsigned long long systemOrientation; // @synthesize systemOrientation=_systemOrientation;
@property(retain, nonatomic) BURewardedVideoWebViewController *rewardedVideoWebViewController; // @synthesize rewardedVideoWebViewController=_rewardedVideoWebViewController;
@property(retain, nonatomic) BUNativeExpressRewardedVideoAdDisplayViewController *rewardedVideoDisplayViewController; // @synthesize rewardedVideoDisplayViewController=_rewardedVideoDisplayViewController;
@property(retain, nonatomic) UIViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(retain, nonatomic) BUNativeExpressRewardedVideoAdView *expressAdView; // @synthesize expressAdView=_expressAdView;
@property(nonatomic) _Bool isRewardedVideo; // @synthesize isRewardedVideo=_isRewardedVideo;
@property(nonatomic) __weak id <BUNativeExpressVideoAdDelegate> rewardedVideoAd; // @synthesize rewardedVideoAd=_rewardedVideoAd;
- (void).cxx_destruct;
- (void)startVerifyServerRewardWithPlayer:(id)arg1 sucess:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;
- (void)judgeDirection;
- (void)rewardedVideoH5AdDidClickNeedJump:(_Bool)arg1;
- (void)rewardedVideoAdClose;
- (void)dismissCurrentViewControllerIsSkip:(_Bool)arg1;
- (void)switchToEndcardViewControllerIsSkip:(_Bool)arg1;
- (void)nativeExpressRewardedVideoAdViewDidPlayFinish:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeExpressRewardedVideoAdViewVerifyReward:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLoad;
- (id)initWithNativeExpressAdView:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

