//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class EBAppLogConfig, EBAppLogRegisterEngine, NSString;

@interface EBAppLogInstallManager : NSObject
{
    EBAppLogConfig *_config;
    CDUnknownBlockType _customHeaderBlock;
    long long _serviceVendor;
    NSString *_userUniqueID;
    NSString *_userAgent;
    NSString *_appLauguage;
    NSString *_appRegion;
    EBAppLogRegisterEngine *_registerDeviceEngine;
    CDUnknownBlockType _logger;
}

+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType logger; // @synthesize logger=_logger;
@property(retain, nonatomic) EBAppLogRegisterEngine *registerDeviceEngine; // @synthesize registerDeviceEngine=_registerDeviceEngine;
@property(copy) NSString *appRegion; // @synthesize appRegion=_appRegion;
@property(copy) NSString *appLauguage; // @synthesize appLauguage=_appLauguage;
@property(copy) NSString *userAgent; // @synthesize userAgent=_userAgent;
@property(copy) NSString *userUniqueID; // @synthesize userUniqueID=_userUniqueID;
@property long long serviceVendor; // @synthesize serviceVendor=_serviceVendor;
@property(copy) CDUnknownBlockType customHeaderBlock; // @synthesize customHeaderBlock=_customHeaderBlock;
@property(retain, nonatomic) EBAppLogConfig *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)debugLog:(id)arg1;
- (id)eventParameters;
- (id)appRequestParameters:(_Bool)arg1;
- (void)startWithConfig:(id)arg1;
- (void)saveUserAgent:(id)arg1;
- (void)saveUserUniqueID:(id)arg1;
- (void)saveAppLauguage:(id)arg1;
- (void)saveAppRegion:(id)arg1;
- (void)saveServiceVendor:(long long)arg1;
- (id)init;

@end

