//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IMCSystemPushMessage : NSObject
{
    int _type;
    int _subType;
    long long _uniqueId;
    NSString *_attachment;
}

@property(retain, nonatomic) NSString *attachment; // @synthesize attachment=_attachment;
@property(nonatomic) long long uniqueId; // @synthesize uniqueId=_uniqueId;
@property(nonatomic) int subType; // @synthesize subType=_subType;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

