//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AlarmDelegate-Protocol.h"
#import "AuxDelegate-Protocol.h"
#import "ConnectDelegate-Protocol.h"
#import "GlobalDelegate-Protocol.h"
#import "MusicDelegate-Protocol.h"
#import "RadioDelegate-Protocol.h"

@protocol LMBluetoothDelegate <ConnectDelegate, GlobalDelegate, MusicDelegate, RadioDelegate, AlarmDelegate, AuxDelegate>
@end

