//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface UMFileUtility : NSObject
{
}

+ (id)statelessEnvelopeFile;
+ (id)itemsInDir:(id)arg1 validSuffix:(id)arg2;
+ (id)generateEnvelopeNamePrefix:(id)arg1 withTS:(id)arg2 pathURL:(id)arg3;
+ (id)statelessDirWithEncodeURL:(id)arg1;
+ (id)umengStatelessDirectory;
+ (id)generateEnvelopeNamePrefix:(id)arg1 withTS:(id)arg2 subFolder:(id)arg3;
+ (id)generateEnvelopeNamePrefix:(id)arg1 withTS:(id)arg2;
+ (id)envelopeFilesWithSubFolder:(id)arg1;
+ (id)envelopeFiles;
+ (void)sortFileWithCreatedTime:(id)arg1;
+ (id)itemsInAbsDir:(id)arg1;
+ (id)umengDirectory;
+ (id)cacheParentDir;
+ (id)envelopeFilePath;
+ (id)agManifestPath;
+ (id)uaDBFilePath;
+ (id)sqliteDBFilePath;
+ (id)bgCacheFilePath;
+ (_Bool)removeFile:(id)arg1;
+ (_Bool)saveData:(id)arg1 inPath:(id)arg2;
+ (_Bool)makeAbsDir:(id)arg1;
+ (_Bool)isExistAtPath:(id)arg1;

@end

