//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AEAudioFilePlayer.h"

@interface XMAEExtAudioFilePlayer : AEAudioFilePlayer
{
}

+ (void)audioFilePlayerWithURL:(id)arg1 audioDescription:(struct AudioStreamBasicDescription)arg2 Complete:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;

@end

