//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel, XMAnchorActionItem, XMWebImageView;

@interface XMAnchorCenterNewActionCell : UIView
{
    UIView *_roundedCornersView;
    UILabel *_titleLbl;
    UILabel *_subtitleLbl;
    UILabel *_openSoonLbl;
    XMWebImageView *_icon;
    XMAnchorActionItem *_action;
    CDUnknownBlockType _touch;
}

@property(copy, nonatomic) CDUnknownBlockType touch; // @synthesize touch=_touch;
@property(retain, nonatomic) XMAnchorActionItem *action; // @synthesize action=_action;
@property(retain, nonatomic) XMWebImageView *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) UILabel *openSoonLbl; // @synthesize openSoonLbl=_openSoonLbl;
@property(retain, nonatomic) UILabel *subtitleLbl; // @synthesize subtitleLbl=_subtitleLbl;
@property(retain, nonatomic) UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;
- (void).cxx_destruct;
- (void)addRoundedCorners:(unsigned long long)arg1 withRadii:(struct CGSize)arg2 forView:(id)arg3;
- (void)didTap:(id)arg1;
- (void)customInit;
- (id)initWithAction:(id)arg1;

@end

