//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XMBase/XMModel.h>

@class NSString;

@interface XMBBSShareModel : XMModel
{
    long long _type;
    long long _itemId;
    NSString *_icon;
    NSString *_title;
    NSString *_subtitle;
}

@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(nonatomic) long long itemId; // @synthesize itemId=_itemId;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

