//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUNativeAdDelegate-Protocol.h"
#import "BUNativeAdsManagerDelegate-Protocol.h"
#import "BUSplashAdDelegate-Protocol.h"

@class BUNativeAd, BUNativeAdRelatedView, BUNativeAdsManager, BUSplashAdView, NSHashTable, NSString, NSTimer, UIView;

@interface XMBUAdRequest : NSObject <BUSplashAdDelegate, BUNativeAdsManagerDelegate, BUNativeAdDelegate>
{
    long long _key;
    _Bool _windowKitOnShow;
    _Bool _requestFinished;
    BUNativeAdRelatedView *_nativeAdRelatedView;
    BUNativeAd *_nativeAd;
    NSHashTable *_adItems;
    BUSplashAdView *_splashAd;
    UIView *_adView;
    BUNativeAdsManager *_adManager;
    CDUnknownBlockType _buSplashRequestComplete;
    CDUnknownBlockType _buAdRequestComplete;
    id _strongSelf;
    NSTimer *_timer;
}

+ (void)fillBUAdWithAdItem:(id)arg1 andComplete:(CDUnknownBlockType)arg2;
+ (void)getPlacementIdWithAdItem:(id)arg1 andPlacementId:(id *)arg2;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) id strongSelf; // @synthesize strongSelf=_strongSelf;
@property(copy, nonatomic) CDUnknownBlockType buAdRequestComplete; // @synthesize buAdRequestComplete=_buAdRequestComplete;
@property(copy, nonatomic) CDUnknownBlockType buSplashRequestComplete; // @synthesize buSplashRequestComplete=_buSplashRequestComplete;
@property(retain, nonatomic) BUNativeAdsManager *adManager; // @synthesize adManager=_adManager;
@property(readonly, nonatomic) UIView *adView; // @synthesize adView=_adView;
@property(readonly, nonatomic) BUSplashAdView *splashAd; // @synthesize splashAd=_splashAd;
@property(retain, nonatomic) NSHashTable *adItems; // @synthesize adItems=_adItems;
@property(retain, nonatomic) BUNativeAd *nativeAd; // @synthesize nativeAd=_nativeAd;
@property(retain, nonatomic) BUNativeAdRelatedView *nativeAdRelatedView; // @synthesize nativeAdRelatedView=_nativeAdRelatedView;
- (void).cxx_destruct;
- (void)nativeAdDidClick:(id)arg1 withView:(id)arg2;
- (void)nativeAdDidCloseOtherController:(id)arg1 interactionType:(long long)arg2;
- (_Bool)buNativeAdDataMapDataToItem:(id)arg1;
- (void)nativeAdsManager:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeAdsManagerSuccessToLoad:(id)arg1 nativeAds:(id)arg2;
- (id)sizeOfAudioItem:(id)arg1;
- (void)requestThirdPartAdDataWithAdItem:(id)arg1 andComplete:(CDUnknownBlockType)arg2;
- (void)notifyAdWithGDTStatus:(long long)arg1 andUserInfo:(id)arg2;
- (void)splashAdDidCloseOtherController:(id)arg1 interactionType:(long long)arg2;
- (void)splashAdDidClick:(id)arg1;
- (void)splashAdDidClose:(id)arg1;
- (void)splashAdDidLoad:(id)arg1;
- (void)splashAd:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeAdFailToLoad;
- (void)windowKitHide:(id)arg1;
- (void)requestThirdPartSplashAdDataWithAdItem:(id)arg1 andComplete:(CDUnknownBlockType)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

