//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMTableViewCell.h"

@class NSArray, UIButton, UIImageView, UILabel, XMWebImageView;
@protocol XMCategoryRankEnterDoubleCellDelegate;

@interface XMCategoryRankEnterDoubleCell : XMTableViewCell
{
    XMWebImageView *_rank1ImageView;
    XMWebImageView *_rank2ImageView;
    UILabel *_rank1titleLab;
    UILabel *_rank2titleLab;
    UIImageView *_moreIndicator;
    UIButton *_rank1Btn;
    UIButton *_rank2Btn;
    NSArray *_rankArray;
    id <XMCategoryRankEnterDoubleCellDelegate> _delegate;
}

+ (double)height;
@property(nonatomic) __weak id <XMCategoryRankEnterDoubleCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *rankArray; // @synthesize rankArray=_rankArray;
- (void).cxx_destruct;
- (void)onClickRankBtn:(id)arg1;
- (void)layoutSubviews;
- (void)customInit;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

