//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface XMChatMPictureNode : NSObject
{
    NSMutableArray *_pictureArray;
    CDUnknownBlockType _complete;
}

@property(copy, nonatomic) CDUnknownBlockType complete; // @synthesize complete=_complete;
@property(retain, nonatomic) NSMutableArray *pictureArray; // @synthesize pictureArray=_pictureArray;
- (void).cxx_destruct;
- (void)uploadImageAtIndex:(long long)arg1;
- (void)uploadWithCompletion:(CDUnknownBlockType)arg1;
- (id)BBSRequestString;
- (id)BBSRequestDictionaryArray;

@end

