//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSTimer, XMServerRequest, XMSoundItem;

@interface XMDanmuDataSource : NSObject
{
    long long _failCount;
    _Bool _enterBackground;
    long long _nextPartNum;
    NSMutableArray *_danmuArray;
    XMSoundItem *_soundItem;
    NSMutableArray *_danmuRanges;
    NSTimer *_danmuTimer;
    XMServerRequest *_danmurequest;
}

@property(retain, nonatomic) XMServerRequest *danmurequest; // @synthesize danmurequest=_danmurequest;
@property(retain, nonatomic) NSTimer *danmuTimer; // @synthesize danmuTimer=_danmuTimer;
@property(retain, nonatomic) NSMutableArray *danmuRanges; // @synthesize danmuRanges=_danmuRanges;
@property(retain, nonatomic) XMSoundItem *soundItem; // @synthesize soundItem=_soundItem;
@property(retain, nonatomic) NSMutableArray *danmuArray; // @synthesize danmuArray=_danmuArray;
@property(nonatomic) long long nextPartNum; // @synthesize nextPartNum=_nextPartNum;
- (void).cxx_destruct;
- (unsigned long long)BinarySearch:(id)arg1;
- (void)insertDanmuArray:(id)arg1;
- (_Bool)shouldRequestDanmuWithSecond:(unsigned long long)arg1;
- (_Bool)updateDanmuRanges:(struct _XMRange)arg1;
- (void)bulletFail:(id)arg1;
- (void)bulletSuccess:(id)arg1;
- (void)requestDanmuData;
- (void)requestDanmuDataWithSecond:(unsigned long long)arg1;
- (void)requestDanmuWithSecond:(unsigned long long)arg1;
- (void)_startDanmuRequestImmediately:(_Bool)arg1;
- (void)endDanmuRequest;
- (void)startDanmuRequest;
- (void)onWillEnterForeground;
- (void)onDidEnterBackground;
- (id)init;
- (void)dealloc;

@end

