//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class XMDubShowMSSearchedView;

@interface XMDubShowMSHistorySearchCell : UICollectionViewCell
{
    XMDubShowMSSearchedView *_searchedView;
}

@property(retain, nonatomic) XMDubShowMSSearchedView *searchedView; // @synthesize searchedView=_searchedView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)customInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

