//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, XMFeedBackCategorySubTypeModel;

@interface XMFeedbackSubmitCategoryCell : UITableViewCell
{
    UIImageView *_selectView;
    XMFeedBackCategorySubTypeModel *_model;
}

@property(retain, nonatomic) XMFeedBackCategorySubTypeModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIImageView *selectView; // @synthesize selectView=_selectView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setContentWithModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

