//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMHModel.h"

@class NSString;

@interface XMHCapToastModel : XMHModel
{
    NSString *_content;
    long long _duration;
    long long _delay;
}

+ (id)xmm_modelCustomPropertyMapper;
@property(nonatomic) long long delay; // @synthesize delay=_delay;
@property(nonatomic) long long duration; // @synthesize duration=_duration;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;

@end

