//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray;

@interface XMInfoAgeView : UIView
{
    unsigned long long _ageType;
    CDUnknownBlockType _optionChanged;
    NSArray *_ageData;
    NSMutableArray *_ageMArr;
}

@property(retain, nonatomic) NSMutableArray *ageMArr; // @synthesize ageMArr=_ageMArr;
@property(retain, nonatomic) NSArray *ageData; // @synthesize ageData=_ageData;
@property(copy, nonatomic) CDUnknownBlockType optionChanged; // @synthesize optionChanged=_optionChanged;
@property(nonatomic) unsigned long long ageType; // @synthesize ageType=_ageType;
- (void).cxx_destruct;
- (void)resetAgeLBStatus:(unsigned long long)arg1;
- (void)_ageLBTap:(long long)arg1;
- (void)ageLBTap:(id)arg1;
- (void)resetAgeLocalData;
- (id)initWithFrame:(struct CGRect)arg1;

@end

