//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIImageView, UILabel;

@interface XMLiveEntPKInfoView : UIView
{
    NSArray *_pkInfoArray;
    long long _countDownTime;
    UILabel *_leftScoreLabel;
    UIImageView *_leftScoreBackView;
    UILabel *_rightScoreLabel;
    UIImageView *_rightScoreBackView;
    UILabel *_countDownLabel;
    UIImageView *_countDownBackView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *countDownBackView; // @synthesize countDownBackView=_countDownBackView;
@property(retain, nonatomic) UILabel *countDownLabel; // @synthesize countDownLabel=_countDownLabel;
@property(retain, nonatomic) UIImageView *rightScoreBackView; // @synthesize rightScoreBackView=_rightScoreBackView;
@property(retain, nonatomic) UILabel *rightScoreLabel; // @synthesize rightScoreLabel=_rightScoreLabel;
@property(retain, nonatomic) UIImageView *leftScoreBackView; // @synthesize leftScoreBackView=_leftScoreBackView;
@property(retain, nonatomic) UILabel *leftScoreLabel; // @synthesize leftScoreLabel=_leftScoreLabel;
@property(nonatomic) long long countDownTime; // @synthesize countDownTime=_countDownTime;
@property(retain, nonatomic) NSArray *pkInfoArray; // @synthesize pkInfoArray=_pkInfoArray;
- (void)initBase;
- (id)init;

@end

