//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class XMLiveEntBaseRspMapItem;

@protocol XMLiveEntMicManagerRecvAbility <NSObject>
- (void)recvDirectGiftComboOver:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvDirectGiftMsg:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvLockPositionRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvOnlineUserRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvMuteSelfRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvMuteRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvUserStatusSynRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvHangUpRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvConnectRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvWaitUserUpdate:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvWaitUserRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvLeaveRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvJoinRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvPresideTtlRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvUnPresideRsp:(XMLiveEntBaseRspMapItem *)arg1;
- (void)recvPresideRsp:(XMLiveEntBaseRspMapItem *)arg1;
@end

