//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, UIColor, UILabel;

@interface XMLiveNobleFooterView : UIView
{
    UIColor *_noticeColor;
    UIColor *_textColor;
    UILabel *_titleLabel;
    NSMutableArray *_nobleGroupArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *nobleGroupArray; // @synthesize nobleGroupArray=_nobleGroupArray;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIColor *noticeColor; // @synthesize noticeColor=_noticeColor;
- (void)updateContentWithNobles:(id)arg1;
- (void)addSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

