//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMLiveBaseCustomAlert.h"

@class UIButton, UILabel, XMLiveHotCardView;

@interface XMLiveBackRecomendAlertView : XMLiveBaseCustomAlert
{
    XMLiveHotCardView *_liveRecommendCard;
    UIButton *_closeBtn;
    UILabel *_titleLabel;
    UIButton *_exitBtn;
    UIButton *_exitMinizeBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *exitMinizeBtn; // @synthesize exitMinizeBtn=_exitMinizeBtn;
@property(retain, nonatomic) UIButton *exitBtn; // @synthesize exitBtn=_exitBtn;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) XMLiveHotCardView *liveRecommendCard; // @synthesize liveRecommendCard=_liveRecommendCard;
- (void)onExitMinizeClick;
- (void)onExitClick;
- (void)onCloseDidClick;
- (void)updateRecommendSection:(id)arg1 withHotcardDelegate:(id)arg2;
- (void)addViewConstrants;
- (void)setupCustomViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

