//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CDZModalView.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIView, UIViewController, XMMCommentView;

@interface XMMCommentModalView : CDZModalView <UIGestureRecognizerDelegate>
{
    UIView *_tapHideView;
    CDUnknownBlockType _sendBlock;
    XMMCommentView *_commentView;
}

@property(retain, nonatomic) XMMCommentView *commentView; // @synthesize commentView=_commentView;
@property(copy, nonatomic) CDUnknownBlockType sendBlock; // @synthesize sendBlock=_sendBlock;
- (void).cxx_destruct;
@property(nonatomic) __weak UIViewController *viewController;
- (void)layoutContentView;
- (void)hide;
- (double)paneHeight;
- (void)clearComment;
- (void)willShowInView:(id)arg1;
- (_Bool)becomeFirstResponder;
- (void)didInitialize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

