//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMSubLevelViewController.h"

#import "XMAdFeaturesProtocol-Protocol.h"
#import "XMFindOptionScrollViewDelegate-Protocol.h"
#import "XMScrollImageViewDelegate-Protocol.h"
#import "XMSectionViewDelegate-Protocol.h"
#import "XMTableViewDelegateProtocol-Protocol.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSString, UIView, XMFindOptionScrollView, XMNRequest, XMScrollImageView, XMTableViewDataSource;

@interface XMPaidCategoryRecViewController : XMSubLevelViewController <XMSectionViewDelegate, XMScrollImageViewDelegate, XMFindOptionScrollViewDelegate, XMAdFeaturesProtocol, XMTableViewDelegateProtocol>
{
    UIView *_headerContainer;
    XMNRequest *_request;
    XMScrollImageView *_focusImageView;
    UIView *_topThirdAdView;
    UIView *_adView;
    UIView *_bottomView;
    XMFindOptionScrollView *_optionView;
    NSArray *_optionArray;
    XMTableViewDataSource *_tableDataSource;
    long long _categoryId;
    NSString *_categoryTitle;
    NSMutableArray *_brandAdSection;
    NSMutableDictionary *_albumAdInfoDic;
}

@property(retain, nonatomic) NSMutableDictionary *albumAdInfoDic; // @synthesize albumAdInfoDic=_albumAdInfoDic;
@property(retain, nonatomic) NSMutableArray *brandAdSection; // @synthesize brandAdSection=_brandAdSection;
@property(copy, nonatomic) NSString *categoryTitle; // @synthesize categoryTitle=_categoryTitle;
@property(nonatomic) long long categoryId; // @synthesize categoryId=_categoryId;
@property(retain, nonatomic) XMTableViewDataSource *tableDataSource; // @synthesize tableDataSource=_tableDataSource;
@property(retain, nonatomic) NSArray *optionArray; // @synthesize optionArray=_optionArray;
@property(retain, nonatomic) XMFindOptionScrollView *optionView; // @synthesize optionView=_optionView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIView *adView; // @synthesize adView=_adView;
@property(retain, nonatomic) UIView *topThirdAdView; // @synthesize topThirdAdView=_topThirdAdView;
@property(retain, nonatomic) XMScrollImageView *focusImageView; // @synthesize focusImageView=_focusImageView;
@property(retain, nonatomic) XMNRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (void)postMoreClickedDataTrackWithSectionItem:(id)arg1;
- (void)postOpenAlbumDataTrackWithActionTitle:(id)arg1 SectionItem:(id)arg2 postion:(long long)arg3 Album:(id)arg4;
- (void)postOpenAlbumDataTrackWithSectionItem:(id)arg1 postion:(long long)arg2 Album:(id)arg3;
- (void)postOpenRankWithSectionItem:(id)arg1 SpecialItem:(id)arg2;
- (void)requestBanner;
- (void)requestAd;
- (void)sectionCellMoreDidCilck:(id)arg1;
- (void)categoryRecRankCellDidSelectItem:(id)arg1 atIndex:(long long)arg2 recModel:(id)arg3;
- (void)categoryRecRankCellMoreDidClick:(id)arg1;
- (void)findRecCardCellObject:(id)arg1 didClickCardItem:(id)arg2 atPosition:(long long)arg3;
- (void)categoryRecActivityCellObject:(id)arg1 didClickItem:(id)arg2 atPosition:(long long)arg3;
- (void)findRecLiveCellObject:(id)arg1 didClickCardItem:(id)arg2 atPosition:(long long)arg3;
- (void)categoryRecSoundsCellCellObject:(id)arg1 clickPlaySound:(id)arg2 soundList:(id)arg3 atIndex:(long long)arg4;
- (void)categoryRecSoundsCellCellObject:(id)arg1 clickPlayAll:(id)arg2;
- (void)categoryRecSoundsCellObject:(id)arg1 ClickMoreWithSubjectId:(id)arg2;
- (void)categoryRecSpecialCellObject:(id)arg1 didClickMore:(id)arg2;
- (void)categoryRecSpecialCellObject:(id)arg1 didClickItem:(id)arg2 atPosition:(long long)arg3;
- (void)categoryRecAnchorCellDidSelectItem:(id)arg1 atIndex:(long long)arg2 recModel:(id)arg3;
- (void)categoryRecGridCellDidSelectItem:(id)arg1 atIndex:(long long)arg2;
- (void)pushAlbumWithAlbumItem:(id)arg1;
- (void)pushTingWithItem:(id)arg1;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableViewDidSelectCellWithCellObject:(id)arg1 tableViewCell:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollImageView:(id)arg1 clickFocusItem:(id)arg2 atIndex:(long long)arg3;
- (void)addFocusImages:(id)arg1;
- (void)parseRecommendJSON:(id)arg1;
- (void)requestAllRecommendsData;
- (void)triggerPullToRefresh;
- (void)genderChanged:(id)arg1;
- (void)reloadScrollView;
- (void)reloadTableViewHeader;
- (void)reloadData;
- (void)startDataLoad;
- (void)postActionForSelectDiscoverColumnItemDataTrack:(id)arg1 position:(long long)arg2;
- (void)actionForSelectDiscoverColumnItem:(id)arg1;
- (void)findOptionScrollView:(id)arg1 didClick:(id)arg2;
- (void)addFindOptionScrollViewWithType:(long long)arg1;
- (void)adViewDidUpdateWithAdModels:(id)arg1 andPositionName:(id)arg2;
- (id)adViewWillRequestWithParamsForPositionName:(id)arg1;
- (void)adViewControllerWillAppear;
- (void)adViewWillAddAds;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCategoryId:(long long)arg1 categoryTitle:(id)arg2;
- (void)dealloc;
- (id)sectionCellObjectsWithRecModel:(id)arg1 ablumAdContainer:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

