//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMUBTEventBinding.h"

@interface XMUBTControlBinding : XMUBTEventBinding
{
}

- (id)trackView:(id)arg1 withAdditionalParameters:(id)arg2 isDialog:(_Bool)arg3;
- (void)startTrackingView:(id)arg1 withAdditionalParameters:(id)arg2 isDialog:(_Bool)arg3;
- (void)startTrackingView:(id)arg1 isDialog:(_Bool)arg2;
- (void)removeBinding;
- (void)makeBinding;
- (id)additionalValueWithView:(id)arg1;

@end

