//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface XMVCRectTransformPanel : UIView
{
    NSMutableArray *_array;
}

@property(retain, nonatomic) NSMutableArray *array; // @synthesize array=_array;
- (void).cxx_destruct;
- (void)cleanAllElements;
- (struct UIView *)topElement;
- (void)enumerateUsingBlock:(CDUnknownBlockType)arg1;
- (void)addElement:(struct UIView *)arg1;
- (void)removeElement:(struct UIView *)arg1;
- (void)focusElement:(struct UIView *)arg1;
- (struct UIView *)elementAtPoint:(struct CGPoint)arg1 margin:(double)arg2;

@end

