//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMJSBaseHandler.h"

#import "NSURLSessionDelegate-Protocol.h"
#import "XMXMLHttpRequestDelegate-Protocol.h"

@class NSLock, NSMutableDictionary, NSOperationQueue, NSString, NSURLSession, NSURLSessionConfiguration, WKWebView;

@interface XMXMLHttpRequestHandler : XMJSBaseHandler <NSURLSessionDelegate, XMXMLHttpRequestDelegate>
{
    WKWebView *_webView;
    NSURLSession *_session;
    NSMutableDictionary *_xhrAndObjectIdMap;
    NSMutableDictionary *_xhrAndTaskIdMap;
    NSOperationQueue *_queue;
    NSLock *_lock;
    NSURLSessionConfiguration *_sessionConfiguration;
}

@property(retain, nonatomic) NSURLSessionConfiguration *sessionConfiguration; // @synthesize sessionConfiguration=_sessionConfiguration;
@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) NSMutableDictionary *xhrAndTaskIdMap; // @synthesize xhrAndTaskIdMap=_xhrAndTaskIdMap;
@property(copy, nonatomic) NSMutableDictionary *xhrAndObjectIdMap; // @synthesize xhrAndObjectIdMap=_xhrAndObjectIdMap;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
@property(nonatomic) __weak WKWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;
- (id)uniqueIdWithWebView:(id)arg1 objectId:(id)arg2;
- (void)freeXMLHttpRequestObject:(id)arg1 objectId:(id)arg2;
- (id)getXHR:(id)arg1 objectId:(id)arg2;
- (id)generateXHR:(id)arg1 responseCallback:(CDUnknownBlockType)arg2;
- (void)notifyDispatcherFetchFailed:(id)arg1;
- (void)notifyDispatcherFetchComplete:(id)arg1;
- (void)removeRequest:(id)arg1;
- (void)setSessionTaskRequest:(id)arg1;
- (void)setRequest:(id)arg1 key:(id)arg2;
- (id)requestInSession:(id)arg1;
- (id)requestInAjaxHook:(id)arg1;
- (void)addmultipart:(id)arg1 callBackId:(id)arg2 responseCallback:(CDUnknownBlockType)arg3;
- (void)clear:(id)arg1 responseCallback:(CDUnknownBlockType)arg2;
- (void)abort:(id)arg1 responseCallback:(CDUnknownBlockType)arg2;
- (void)overrideMimeType:(id)arg1 responseCallback:(CDUnknownBlockType)arg2;
- (void)setRequestHeader:(id)arg1 responseCallback:(CDUnknownBlockType)arg2;
- (id)convertToDataFromBase64:(id)arg1;
- (id)convertToDataFromUInt8Array:(id)arg1;
- (void)send:(id)arg1 responseCallback:(CDUnknownBlockType)arg2;
- (void)open:(id)arg1 responseCallback:(CDUnknownBlockType)arg2;
- (void)formStop:(id)arg1 responseCallback:(CDUnknownBlockType)arg2;
- (void)dealCallbackWithMessage:(id)arg1;
- (id)jsExportMethods;
- (void)dealScriptMessage:(id)arg1;
- (id)init;
- (id)spaceName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

