//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBPageCard.h"

@class NSDictionary;

@interface WBDynamicCard : WBPageCard
{
    long long _type;
    NSDictionary *_data;
    NSDictionary *_style;
}

+ (Class)viewClass;
@property(retain, nonatomic) NSDictionary *style; // @synthesize style=_style;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (_Bool)updateWithDictionary:(id)arg1;
- (id)cardCellIdentifier;

@end

