//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBMLBaseModel.h"

@class NSArray;

@interface WBMLCommonLiveQuickCommentInfoModel : WBMLBaseModel
{
    _Bool _show_once;
    NSArray *_text;
}

@property(retain, nonatomic) NSArray *text; // @synthesize text=_text;
@property(nonatomic) _Bool show_once; // @synthesize show_once=_show_once;
- (void).cxx_destruct;

@end

