//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBMLBaseModel.h"

@class NSMutableArray, NSString;

@interface WBMLQAActivePageBannerItemButtonCalendarInfoModel : WBMLBaseModel
{
    NSString *_title;
    long long _dt_start;
    NSString *_desc;
    NSMutableArray *_alarm_list;
    NSString *_url;
}

@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSMutableArray *alarm_list; // @synthesize alarm_list=_alarm_list;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(nonatomic) long long dt_start; // @synthesize dt_start=_dt_start;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

