//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIView, WBContentImageView, WBTopic;

@interface WBNewTopicCell : UITableViewCell
{
    WBTopic *_topic;
    WBContentImageView *_topicImageView;
    WBContentImageView *_categoryIconView;
    WBContentImageView *_tagIconView;
    UIView *_seperatorView;
}

@property(retain, nonatomic) UIView *seperatorView; // @synthesize seperatorView=_seperatorView;
@property(retain, nonatomic) WBContentImageView *tagIconView; // @synthesize tagIconView=_tagIconView;
@property(retain, nonatomic) WBContentImageView *categoryIconView; // @synthesize categoryIconView=_categoryIconView;
@property(retain, nonatomic) WBContentImageView *topicImageView; // @synthesize topicImageView=_topicImageView;
@property(retain, nonatomic) WBTopic *topic; // @synthesize topic=_topic;
- (void).cxx_destruct;
@property(nonatomic) _Bool hidesSeparator;
- (_Bool)useDefaultBackgroundColor;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

