//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSArray, NSMutableArray, UIView;
@protocol WBPhotoEditorStickerCellDelegate;

@interface WBPhotoEditorStickerCell : UICollectionViewCell
{
    NSMutableArray *_contentSubViews;
    UIView *_emptyView;
    id <WBPhotoEditorStickerCellDelegate> _delegate;
    NSArray *_stickerModels;
}

+ (id)wbt_imageWithColor:(id)arg1 size:(struct CGSize)arg2;
@property(readonly, nonatomic) NSArray *stickerModels; // @synthesize stickerModels=_stickerModels;
@property(nonatomic) __weak id <WBPhotoEditorStickerCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)hideEmptyView;
- (void)showEmptyView;
- (void)rendCell:(id)arg1;
- (void)didSelectSticker:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

