//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBShortVideoBaseListController.h"

@interface WBShortVideoAggregationListController : WBShortVideoBaseListController
{
}

- (void)sharedContext:(id)arg1 didChangeDraggingState:(_Bool)arg2;
- (void)initializeCollectionView:(id)arg1;

@end

