//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class WBStoryAutoScrollLabel, WBStoryItemSegmentDiversion, WBStoryMusicDiversionControl;

@interface WBStoryAnimationMusicControl : UIControl
{
    WBStoryMusicDiversionControl *_musicControl;
    WBStoryAutoScrollLabel *_titleLabel;
    WBStoryItemSegmentDiversion *_diversion;
}

@property(retain, nonatomic) WBStoryItemSegmentDiversion *diversion; // @synthesize diversion=_diversion;
@property(retain, nonatomic) WBStoryAutoScrollLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) WBStoryMusicDiversionControl *musicControl; // @synthesize musicControl=_musicControl;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)stopAnimation;
- (void)startAnimation;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

