//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBTimelineExtendPageView.h"

#import "WBTimeLineTrendScrollViewDelegate-Protocol.h"

@class NSString;

@interface WBTimelineExtendPageViewDetail : WBTimelineExtendPageView <WBTimeLineTrendScrollViewDelegate>
{
}

+ (double)heightWithProducts:(id)arg1 withViewWidth:(double)arg2;
+ (double)heightWithProducts:(id)arg1;
+ (_Bool)isNewProduct:(id)arg1;
- (long long)numberOfItemToLoadWhenFirstShowInScrollView:(id)arg1;
- (void)configureItemView:(id)arg1 atIndex:(unsigned long long)arg2;
- (_Bool)willPrepareItemView:(id)arg1 forReuseInScrollView:(id)arg2;
- (struct CGSize)scrollView:(id)arg1 sizeOfItemAtIndex:(unsigned long long)arg2;
- (id)scrollView:(id)arg1 classPairOfItemViewAndContentAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfItemsInScrollView:(id)arg1;
- (void)didPressBackground:(id)arg1;
- (void)updateWithProducts:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

