//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBVideoItem.h"

@class NSDictionary, NSString, WBPromotion, WBTimelinePageInfo;

@interface WBVideoInstreamAdItem : WBVideoItem
{
    WBVideoItem *_parentVideoItem;
    long long _adPosition;
    double _adPlaybackStartPosition;
    unsigned long long _playTimes;
    long long _skipTime;
    long long _playbackType;
    double _imagePlayDuration;
    NSDictionary *_attachmentInfo;
}

+ (id)mockAdItems;
@property(readonly, copy, nonatomic) NSDictionary *attachmentInfo; // @synthesize attachmentInfo=_attachmentInfo;
@property(readonly, nonatomic) double imagePlayDuration; // @synthesize imagePlayDuration=_imagePlayDuration;
@property(readonly, nonatomic) long long playbackType; // @synthesize playbackType=_playbackType;
@property(readonly, nonatomic) long long skipTime; // @synthesize skipTime=_skipTime;
@property(readonly, nonatomic) unsigned long long playTimes; // @synthesize playTimes=_playTimes;
@property(readonly, nonatomic) double adPlaybackStartPosition; // @synthesize adPlaybackStartPosition=_adPlaybackStartPosition;
@property(readonly, nonatomic) long long adPosition; // @synthesize adPosition=_adPosition;
@property(nonatomic) __weak WBVideoItem *parentVideoItem; // @synthesize parentVideoItem=_parentVideoItem;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *imageUrl;
- (_Bool)shouldParsePromotionDict;
- (id)dictionaryWithValues;
- (_Bool)updateWithDictionary:(id)arg1;
- (_Bool)monitorsStatusPromotion;
@property(readonly, nonatomic) WBPromotion *promotionItem;
@property(readonly, nonatomic) WBTimelinePageInfo *adCardPageInfo;
- (long long)preloadSize;
- (CDStruct_1b6d18a9)vp_pausedTime;
- (void)vp_setPausedTime:(CDStruct_1b6d18a9)arg1 duration:(CDStruct_1b6d18a9)arg2;

@end

