//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSDictionary, UIImageView, WBTimelinePageInfo, WBVideoPlayCompleteActionModel;

@interface WBVideoTimelineAdButtonCardView : UIButton
{
    UIButton *_schemeButton;
    UIImageView *_imgView;
    WBTimelinePageInfo *_pageInfo;
    WBVideoPlayCompleteActionModel *_actionModel;
    NSDictionary *_promotionDic;
    unsigned long long _viewtype;
}

+ (double)cardViewHeightForPageInfo:(id)arg1;
@property(nonatomic) unsigned long long viewtype; // @synthesize viewtype=_viewtype;
@property(copy, nonatomic) NSDictionary *promotionDic; // @synthesize promotionDic=_promotionDic;
@property(retain, nonatomic) WBVideoPlayCompleteActionModel *actionModel; // @synthesize actionModel=_actionModel;
@property(retain, nonatomic) WBTimelinePageInfo *pageInfo; // @synthesize pageInfo=_pageInfo;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
@property(retain, nonatomic) UIButton *schemeButton; // @synthesize schemeButton=_schemeButton;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateViews;
- (void)updateWithPageInfo:(id)arg1;
- (void)schemeBtnStateTouchCancelled;
- (void)schemeBtnStateTouchdown;
- (void)schemeBtnAction;
- (void)setHighlighted:(_Bool)arg1;
- (id)initWithViewType:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

