//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBTableViewController.h"

@class WBMediaAutoPlayManager, WBVideoBlackContainerViewController, WBVideoTimelinePlayerController;

@interface WBVideoBlackBaseViewController : WBTableViewController
{
    _Bool _statusBarHideFlag;
    WBVideoBlackContainerViewController *_containerViewController;
    WBVideoTimelinePlayerController *_playerController;
    WBMediaAutoPlayManager *_playbackManager;
    long long _statusBarHideAnimation;
}

@property(nonatomic) long long statusBarHideAnimation; // @synthesize statusBarHideAnimation=_statusBarHideAnimation;
@property(nonatomic) _Bool statusBarHideFlag; // @synthesize statusBarHideFlag=_statusBarHideFlag;
@property(readonly, nonatomic) WBMediaAutoPlayManager *playbackManager; // @synthesize playbackManager=_playbackManager;
@property(readonly, nonatomic) WBVideoTimelinePlayerController *playerController; // @synthesize playerController=_playerController;
@property(nonatomic) __weak WBVideoBlackContainerViewController *containerViewController; // @synthesize containerViewController=_containerViewController;
- (void).cxx_destruct;
- (long long)preferredStatusBarUpdateAnimation;
- (_Bool)prefersStatusBarHidden;
- (void)setStatusBarHidden:(_Bool)arg1 withAnimation:(long long)arg2;
- (void)playVideoIfNeed;
- (void)playVideoWithPlay:(_Bool)arg1 reason:(id)arg2;
- (void)viewDidLoad;
- (struct CGRect)workingAreaRect;
- (id)workingAreaHandlers;
- (_Bool)workingAreaDetectionEnabled;

@end

