//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WBVideoPlayStrategyCondition, WBVideoPlayStrategyItem;

@interface WBVideoPlayStrategySettings : NSObject
{
    WBVideoPlayStrategyCondition *_strategyCondition;
    WBVideoPlayStrategyItem *_currentStrategy;
    unsigned long long _strategyUpdateTimes;
}

+ (id)globalSettings;
@property(readonly, nonatomic) unsigned long long strategyUpdateTimes; // @synthesize strategyUpdateTimes=_strategyUpdateTimes;
@property(readonly, nonatomic) WBVideoPlayStrategyItem *currentStrategy; // @synthesize currentStrategy=_currentStrategy;
@property(readonly, nonatomic) WBVideoPlayStrategyCondition *strategyCondition; // @synthesize strategyCondition=_strategyCondition;
- (void).cxx_destruct;
- (_Bool)updateWithServerDictionary:(id)arg1;
- (_Bool)LEGACY_updateGlobalStrategyWithDict:(id)arg1;
- (void)LEGACY_updateGlobalPlayStrategyConditionWithDict:(id)arg1;

@end

