//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol YXLivePKSelectViewDelegate;

@interface YXLivePKSelectView : UIView
{
    id <YXLivePKSelectViewDelegate> _delegate;
}

@property(nonatomic) __weak id <YXLivePKSelectViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tapClick:(id)arg1;
- (id)init;

@end

