//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SGWiFiView;

@interface SGWiFiViewController : UIViewController
{
    CDUnknownBlockType _dismissBlock;
    SGWiFiView *_wifiView;
}

@property(nonatomic) __weak SGWiFiView *wifiView; // @synthesize wifiView=_wifiView;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
- (void).cxx_destruct;
- (void)dismiss;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;

@end

