//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AFHTTPSessionManager.h"

@interface HttpManager : AFHTTPSessionManager
{
}

+ (id)shared;
- (void)requestWithURLString:(id)arg1 parameters:(id)arg2 method:(id)arg3 callBack:(CDUnknownBlockType)arg4;
- (void)postUrlString:(id)arg1 parameters:(id)arg2 callBack:(CDUnknownBlockType)arg3;
- (void)getUrlString:(id)arg1 parameters:(id)arg2 callBack:(CDUnknownBlockType)arg3;

@end

