//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface EBAppLogAppHelper : NSObject
{
}

+ (_Bool)isResponseValidate:(id)arg1;
+ (void)updateServerTime:(id)arg1;
+ (id)timeSync;
+ (id)headerFiled:(_Bool)arg1;
+ (id)eventParameters;
+ (id)appRequestParameters:(_Bool)arg1;

@end

