//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTMediaViewAdapterProtocol-Protocol.h"
#import "GDTUnifiedNativeAdDataObjectAdapterProtocol-Protocol.h"
#import "GDTUnifiedNativeAdViewDelegate-Protocol.h"

@class GDTUnifiedNativeAdDataObject, GDTUnifiedNativeAdViewImp, GDTVideoConfig, NSArray, NSNumber, NSString;
@protocol GDTUnifiedNativeAdDataObjectConnectorProtocol;

@interface GDTUnifiedNativeAdDataObjectAdapter : NSObject <GDTUnifiedNativeAdDataObjectAdapterProtocol, GDTMediaViewAdapterProtocol, GDTUnifiedNativeAdViewDelegate>
{
    GDTUnifiedNativeAdViewImp *_unifiedNativeAdViewImp;
    GDTUnifiedNativeAdDataObject *_dataObject;
    id <GDTUnifiedNativeAdDataObjectConnectorProtocol> _connector;
}

@property(nonatomic) __weak id <GDTUnifiedNativeAdDataObjectConnectorProtocol> connector; // @synthesize connector=_connector;
@property(retain, nonatomic) GDTUnifiedNativeAdDataObject *dataObject; // @synthesize dataObject=_dataObject;
@property(retain, nonatomic) GDTUnifiedNativeAdViewImp *unifiedNativeAdViewImp; // @synthesize unifiedNativeAdViewImp=_unifiedNativeAdViewImp;
- (void).cxx_destruct;
- (void)gdt_unifiedNativeAdView:(id)arg1 playerStatusChanged:(unsigned long long)arg2 userInfo:(id)arg3;
- (void)gdt_unifiedNativeAdDetailViewWillPresentScreen:(id)arg1;
- (void)gdt_unifiedNativeAdViewApplicationWillEnterBackground:(id)arg1;
- (void)gdt_unifiedNativeAdDetailViewClosed:(id)arg1;
- (void)gdt_unifiedNativeAdViewDidClick:(id)arg1;
- (void)gdt_unifiedNativeAdViewWillExpose:(id)arg1;
- (void)setRootViewController:(id)arg1;
- (void)unregisterView;
- (void)registerClickableCallToActionView:(id)arg1;
- (void)registerConnector:(id)arg1 clickableViews:(id)arg2;
@property(retain, nonatomic) GDTVideoConfig *videoConfig;
- (_Bool)equalsAdData:(id)arg1;
@property(readonly, nonatomic) long long eCPM;
@property(readonly, nonatomic) long long imageHeight;
@property(readonly, nonatomic) long long imageWidth;
@property(readonly, nonatomic) _Bool isThreeImgsAd;
@property(readonly, nonatomic) _Bool isAppAd;
@property(readonly, nonatomic) NSNumber *appPrice;
@property(readonly, nonatomic) double appRating;
@property(readonly, copy, nonatomic) NSArray *mediaUrlList;
@property(readonly, nonatomic) _Bool isVideoAd;
@property(readonly, copy, nonatomic) NSString *iconUrl;
@property(readonly, copy, nonatomic) NSString *imageUrl;
@property(readonly, copy, nonatomic) NSString *desc;
@property(readonly, copy, nonatomic) NSString *title;
- (id)initWithUnifiedNativeAdDataObject:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

