//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@interface NSFileManager (Utils)
+ (void)asyncFileChecksum:(id)arg1 digestAlgorithm:(id)arg2 completed:(CDUnknownBlockType)arg3 callbackOnMainThread:(_Bool)arg4;
+ (void)asyncFileChecksum:(id)arg1 digestAlgorithm:(id)arg2 completed:(CDUnknownBlockType)arg3;
+ (id)fileChecksum:(id)arg1 digestAlgorithm:(id)arg2 bufferSize:(unsigned long long)arg3;
+ (id)fileChecksum:(id)arg1 digestAlgorithm:(id)arg2;
+ (_Bool)saveTempFile:(id)arg1 toPath:(id)arg2;
+ (_Bool)isFilePath:(id)arg1;
+ (id)filesAtDirectory:(id)arg1;
+ (id)savedFileDirectory;
+ (id)tempDirectoty;
@end

