//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDLRPCRequest.h"

@class NSMutableArray, NSNumber, NSString, SDLInteractionMode, SDLLayoutMode;

@interface SDLPerformInteraction : SDLRPCRequest
{
}

@property(retain) SDLLayoutMode *interactionLayout;
@property(retain) NSMutableArray *vrHelp;
@property(retain) NSNumber *timeout;
@property(retain) NSMutableArray *timeoutPrompt;
@property(retain) NSMutableArray *helpPrompt;
@property(retain) NSMutableArray *interactionChoiceSetIDList;
@property(retain) SDLInteractionMode *interactionMode;
@property(retain) NSMutableArray *initialPrompt;
@property(retain) NSString *initialText;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

