//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface SessionInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasMaxMsgId; // @dynamic hasMaxMsgId;
@property(nonatomic) _Bool hasReadMsgId; // @dynamic hasReadMsgId;
@property(nonatomic) _Bool hasToUserId; // @dynamic hasToUserId;
@property(nonatomic) _Bool hasUnReadNum; // @dynamic hasUnReadNum;
@property(nonatomic) unsigned long long maxMsgId; // @dynamic maxMsgId;
@property(nonatomic) unsigned long long readMsgId; // @dynamic readMsgId;
@property(nonatomic) unsigned long long toUserId; // @dynamic toUserId;
@property(nonatomic) unsigned int unReadNum; // @dynamic unReadNum;

@end

