//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDateFormatter;

@interface WBDNSTools : NSObject
{
    NSDateFormatter *_dateFormat;
}

+ (void)logc:(id)arg1 file:(id)arg2 line:(int)arg3;
+ (_Bool)isIPv6Check:(id)arg1;
+ (_Bool)findString:(id)arg1 inStringArray:(id)arg2;
+ (_Bool)isStringArray:(id)arg1 equalToStringArray2:(id)arg2;
+ (_Bool)isIpV4Address:(id)arg1;
+ (_Bool)isPureInt:(id)arg1;
+ (_Bool)isTestTimeExpired:(id)arg1 expiredTime:(int)arg2;
+ (_Bool)isIpRecordExpired:(id)arg1 expireDuration:(long long)arg2;
+ (_Bool)isDomainModelExpired:(id)arg1 expireDuration:(long long)arg2;
+ (id)serviceProviderTypeToString:(int)arg1;
+ (id)networkTypeToString:(int)arg1;
+ (id)getHostNameOfUrl:(id)arg1;
+ (id)md5:(id)arg1;
+ (id)getIpUrlFromDomainUrl:(id)arg1 host:(id)arg2 ip:(id)arg3;
+ (id)dateFormatter;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)stringFromDate:(id)arg1;
- (id)dateFromString:(id)arg1;
- (id)init;

@end

