//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel;

@interface XMAccompanySelectedView : UIView
{
    UIView *_separatorLine;
    UIButton *_confirmButton;
    UILabel *_stautsLabel;
}

@property(retain, nonatomic) UILabel *stautsLabel; // @synthesize stautsLabel=_stautsLabel;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateViewWithCount:(long long)arg1 totalCount:(long long)arg2;
- (void)didInitialize;
- (id)initWithFrame:(struct CGRect)arg1;

@end

