//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UINavigationController;

@interface XMAlibcObject : NSObject
{
    UINavigationController *_navController;
}

+ (_Bool)jumpMallPageWithUrl:(id)arg1 webtitle:(id)arg2 show:(id)arg3;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedAlibc;
@property(nonatomic) __weak UINavigationController *navController; // @synthesize navController=_navController;
- (void).cxx_destruct;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

