//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSDictionary, NSMutableArray, NSString, UITableView, XMAlarmClockModel, XMAlarmClockSoundViewController;

@interface XMAlarmClockSoundPresenter : NSObject <UITableViewDelegate, UITableViewDataSource>
{
    XMAlarmClockSoundViewController *_controller;
    XMAlarmClockModel *_model;
    NSDictionary *_ringInfo;
    unsigned long long _ringSoundType;
    UITableView *_tableView;
    NSMutableArray *_datas;
}

@property(retain, nonatomic) NSMutableArray *datas; // @synthesize datas=_datas;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) unsigned long long ringSoundType; // @synthesize ringSoundType=_ringSoundType;
@property(copy, nonatomic) NSDictionary *ringInfo; // @synthesize ringInfo=_ringInfo;
@property(retain, nonatomic) XMAlarmClockModel *model; // @synthesize model=_model;
@property(nonatomic) __weak XMAlarmClockSoundViewController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)updateDatas;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

