//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface XMAudioPlayerUtil : NSObject
{
}

+ (void)checkNowPlayingAtPresentingViewControllerFrom:(id)arg1;
+ (id)showNowPlayingPresentingViewControllerFrom:(id)arg1;
+ (void)showNowPlayingViewController:(id)arg1 fromViewController:(id)arg2;

@end

