//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UILabel, UIView, XMMCommunityCategory;

@interface XMBBSCategoryCell : UITableViewCell
{
    XMMCommunityCategory *_category;
    UILabel *_titleLabel;
    UIButton *_deleteButton;
    UIButton *_editButton;
    UIView *_underlayView;
}

@property(retain, nonatomic) UIView *underlayView; // @synthesize underlayView=_underlayView;
@property(retain, nonatomic) UIButton *editButton; // @synthesize editButton=_editButton;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) XMMCommunityCategory *category; // @synthesize category=_category;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

