//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMChatBaseScrollVC.h"

#import "CDZTableViewCellDelegate-Protocol.h"

@class CDZEmitter, NSString;

@interface XMBBSMyCommunityCtrl : XMChatBaseScrollVC <CDZTableViewCellDelegate>
{
    CDZEmitter *_myCommunityChangedEmitter;
}

@property(retain, nonatomic) CDZEmitter *myCommunityChangedEmitter; // @synthesize myCommunityChangedEmitter=_myCommunityChangedEmitter;
- (void).cxx_destruct;
- (void)loadMoreData:(_Bool)arg1;
- (void)tableViewCellClickMore:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)didEnterCommunity:(id)arg1;
- (void)dealloc;
- (void)didInitialize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

