//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "XMSleepSettingCustomViewDelegate-Protocol.h"

@class NSString, UIButton, UIImageView, UILabel, UIScrollView, XMSleepSettingCustomView;
@protocol XMCoaxSleepMenuDelegate;

@interface XMCoaxSleepMenu : UIView <XMSleepSettingCustomViewDelegate>
{
    _Bool _isChangeEtaSec;
    id <XMCoaxSleepMenuDelegate> _delegate;
    UIImageView *_titleBgView;
    UIImageView *_titleBackView;
    UILabel *_titleLabel;
    UIScrollView *_scrollView;
    UIButton *_closeButton;
    UIView *_line;
    UIButton *_bgButton;
    double _menuHeight;
    double _etaSec;
    XMSleepSettingCustomView *_customView;
}

+ (long long)lineCount;
@property(retain, nonatomic) XMSleepSettingCustomView *customView; // @synthesize customView=_customView;
@property(nonatomic) _Bool isChangeEtaSec; // @synthesize isChangeEtaSec=_isChangeEtaSec;
@property(nonatomic) double etaSec; // @synthesize etaSec=_etaSec;
@property(nonatomic) double menuHeight; // @synthesize menuHeight=_menuHeight;
@property(retain, nonatomic) UIButton *bgButton; // @synthesize bgButton=_bgButton;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *titleBackView; // @synthesize titleBackView=_titleBackView;
@property(retain, nonatomic) UIImageView *titleBgView; // @synthesize titleBgView=_titleBgView;
@property(nonatomic) __weak id <XMCoaxSleepMenuDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didDismissWithEtaSec:(double)arg1 isChangeEtaSec:(_Bool)arg2;
- (void)showInView:(id)arg1;
- (void)hiddenFromSuperViewForCustomView;
- (void)close;
- (void)selectTime:(id)arg1;
- (void)setContentWithArray:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

