//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface XMDataSource : NSObject
{
    NSString *_cachePath;
    NSURL *_url;
    NSString *_reqHost;
    NSString *_reqUserAgent;
}

@property(retain, nonatomic) NSString *reqUserAgent; // @synthesize reqUserAgent=_reqUserAgent;
@property(retain, nonatomic) NSString *reqHost; // @synthesize reqHost=_reqHost;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *cachePath; // @synthesize cachePath=_cachePath;
- (id)readPacket:(long long **)arg1 withOffset:(long long)arg2 withBufferLen:(long long)arg3 withIsEnd:(long long *)arg4;
- (void)notifcationBufferEnd;
- (void)notifcationBufferStart;
- (_Bool)isPause;
- (void)resume;
- (void)stop;
- (void)startWithFileURL:(id)arg1;
- (void)startWithURL:(id)arg1;
- (id)initWithURL:(id)arg1 withCachePath:(id)arg2;
- (void)dealloc;

@end

