//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView, XMDubShowMSCartoonDetailCellModel;

@interface XMDubShowMSCartoonDetailCell : UITableViewCell
{
    XMDubShowMSCartoonDetailCellModel *_model;
    UIView *_convView;
    UILabel *_titleLabel;
    UIImageView *_markedImageView;
}

@property(retain, nonatomic) UIImageView *markedImageView; // @synthesize markedImageView=_markedImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *convView; // @synthesize convView=_convView;
@property(retain, nonatomic) XMDubShowMSCartoonDetailCellModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)customInit;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

