//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface XMDubShowPipMatchClauseModel : NSObject
{
    _Bool _isCurrent;
    NSString *_content;
    long long _currentIndex;
    long long _allIndex;
    NSURL *_surfaceUrl;
    NSString *_roleName;
    double _beginPos;
    double _endPos;
    long long _status;
    long long _recordingStatus;
    long long _listenPlayStatus;
    NSString *_recFileName;
}

@property(copy, nonatomic) NSString *recFileName; // @synthesize recFileName=_recFileName;
@property(nonatomic) long long listenPlayStatus; // @synthesize listenPlayStatus=_listenPlayStatus;
@property(nonatomic) long long recordingStatus; // @synthesize recordingStatus=_recordingStatus;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) double endPos; // @synthesize endPos=_endPos;
@property(nonatomic) double beginPos; // @synthesize beginPos=_beginPos;
@property(retain, nonatomic) NSString *roleName; // @synthesize roleName=_roleName;
@property(retain, nonatomic) NSURL *surfaceUrl; // @synthesize surfaceUrl=_surfaceUrl;
@property(nonatomic) _Bool isCurrent; // @synthesize isCurrent=_isCurrent;
@property(nonatomic) long long allIndex; // @synthesize allIndex=_allIndex;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;

@end

