//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMCommentBaseCtrl.h"

@class UILabel, XMCommentInputBar;

@interface XMDubShowCommentViewController : XMCommentBaseCtrl
{
    unsigned long long _trackId;
    CDUnknownBlockType _commentCountDidChangeBlock;
    XMCommentInputBar *_inputBar;
    UILabel *_emptyFooterView;
    long long _totalCount;
}

@property(nonatomic) long long totalCount; // @synthesize totalCount=_totalCount;
@property(retain, nonatomic) UILabel *emptyFooterView; // @synthesize emptyFooterView=_emptyFooterView;
@property(retain, nonatomic) XMCommentInputBar *inputBar; // @synthesize inputBar=_inputBar;
@property(copy, nonatomic) CDUnknownBlockType commentCountDidChangeBlock; // @synthesize commentCountDidChangeBlock=_commentCountDidChangeBlock;
@property(nonatomic) unsigned long long trackId; // @synthesize trackId=_trackId;
- (void).cxx_destruct;
- (void)pushCommentDetial:(id)arg1 andReplyTo:(id)arg2;
- (void)pushCommentDetial:(id)arg1;
- (void)commentWithInputController:(id)arg1 toComment:(id)arg2;
- (void)didRequestMoreData:(_Bool)arg1;
- (void)requestMoreData:(_Bool)arg1 showLoadingHud:(_Bool)arg2;
- (void)commentCellDidTapDeleteButon:(id)arg1;
- (void)commentCellDidTapReplyButon:(id)arg1;
- (void)commentCell:(id)arg1 didTapReply:(id)arg2;
- (void)commentCellDidTapReplyView:(id)arg1;
- (void)commentCellDidTapMoreReplyButton:(id)arg1;
- (void)commentCellDidTapPraiseButton:(id)arg1;
- (void)commentCellDidBeLongPressed:(id)arg1;
- (void)commentCell:(id)arg1 didTapUser:(id)arg2 inReply:(id)arg3;
- (void)commentCellDidTapAvatarImageView:(id)arg1;
- (void)commentInputBarDidBeTapped:(id)arg1;
- (void)didSelecteCellWithLayout:(id)arg1 atIndexPath:(id)arg2;
- (void)initializeCell:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)didInitialize;

@end

