//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel;

@interface XMFeedsTrackShareView : UIView
{
    UILabel *_descLabel;
    UIButton *_wechatSessionButton;
    UIButton *_wechatTimelineButton;
}

@property(retain, nonatomic) UIButton *wechatTimelineButton; // @synthesize wechatTimelineButton=_wechatTimelineButton;
@property(retain, nonatomic) UIButton *wechatSessionButton; // @synthesize wechatSessionButton=_wechatSessionButton;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)showAnimation;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;

@end

