//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, XMGroupAWApplyModel, XMWebImageView;

@interface XMGroupAWApplyListCell : UITableViewCell
{
    XMWebImageView *_faceView;
    UILabel *_nicknameLabel;
    UILabel *_timeLabel;
    UILabel *_stateLabel;
    UIImageView *_vipLogo;
    XMGroupAWApplyModel *_data;
}

@property(retain, nonatomic) XMGroupAWApplyModel *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)p_setupUnits;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

