//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMBaseTabelVC.h"

@class NSMutableArray, XMGroupTalkingItem;

@interface XMGroupAdminSettingViewController : XMBaseTabelVC
{
    XMGroupTalkingItem *_groupItem;
    unsigned long long _type;
    NSMutableArray *_groupAdmins;
}

@property(retain, nonatomic) NSMutableArray *groupAdmins; // @synthesize groupAdmins=_groupAdmins;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) XMGroupTalkingItem *groupItem; // @synthesize groupItem=_groupItem;
- (void).cxx_destruct;
- (void)reloadData;
- (void)requestGroupAdmins;
- (void)removeAdminMember:(id)arg1;
- (void)pullToRefresh;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)editAdminMembers;
- (void)showMemberList;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)shouldTriggerBackPan:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)onRightButton:(id)arg1;
- (void)viewDidLoad;

@end

