//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMHModel.h"

@class NSString;

@interface XMHCapOpenMiniProgram : XMHModel
{
    NSString *_programId;
    NSString *_path;
    unsigned long long _type;
}

+ (id)xmm_modelCustomPropertyMapper;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *programId; // @synthesize programId=_programId;
- (void).cxx_destruct;

@end

