//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class XMNRequest, YYThreadSafeArray;

@interface XMLiveHotwordsUtil : NSObject
{
    double _lastLoadTimeStamp;
    long long _code;
    YYThreadSafeArray *_hotwords;
    XMNRequest *_loadReq;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)util;
- (void).cxx_destruct;
@property(retain, nonatomic) XMNRequest *loadReq; // @synthesize loadReq=_loadReq;
@property(retain, nonatomic) YYThreadSafeArray *hotwords; // @synthesize hotwords=_hotwords;
@property(nonatomic) long long code; // @synthesize code=_code;
- (void)fetchHotwords:(CDUnknownBlockType)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

