//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class XMGiftEffectAnim;
@protocol XMLiveVideoAnimatedViewDelegate;

@interface XMLiveVideoBaseAnimatedView : UIView
{
    id _audioInterruptObserver;
    _Bool _shouldAutoPlay;
    XMGiftEffectAnim *_appendAnimatedMsg;
    id <XMLiveVideoAnimatedViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool shouldAutoPlay; // @synthesize shouldAutoPlay=_shouldAutoPlay;
@property(nonatomic) __weak id <XMLiveVideoAnimatedViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) XMGiftEffectAnim *appendAnimatedMsg; // @synthesize appendAnimatedMsg=_appendAnimatedMsg;
- (void)dismiss;
- (void)startAnimated;
- (void)handleInterruption:(id)arg1;
- (void)initBase:(id)arg1;
- (id)initWithAnimatedMsg:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

