//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol XMMeInfoBirthViewControllerDelegate <NSObject>
- (void)publicBirthChanged:(_Bool)arg1;
- (void)birthChangedWithYear:(NSString *)arg1 month:(NSString *)arg2 day:(NSString *)arg3 star:(NSString *)arg4;
@end

