//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CDZModalView.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, UITableView, UIView;

@interface XMMenuListPopView : CDZModalView <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableView;
    struct CGRect _contentViewFinalFrame;
    _Bool _autoHideWhenClickMenu;
    NSArray *_titleArray;
    NSArray *_iconArray;
    CDUnknownBlockType _clickMenuBlock;
    CDUnknownBlockType _clickBackgroundBlock;
    double _menuListWidth;
    double _maxMenuListHeight;
    double _rowHeight;
    UIView *_arrowView;
    long long _arrowDirection;
    double _arrowHeight;
    double _arrowOffset;
    struct CGPoint _menuListOffset;
}

@property(nonatomic) double arrowOffset; // @synthesize arrowOffset=_arrowOffset;
@property(nonatomic) double arrowHeight; // @synthesize arrowHeight=_arrowHeight;
@property(nonatomic) long long arrowDirection; // @synthesize arrowDirection=_arrowDirection;
@property(retain, nonatomic) UIView *arrowView; // @synthesize arrowView=_arrowView;
@property(nonatomic) _Bool autoHideWhenClickMenu; // @synthesize autoHideWhenClickMenu=_autoHideWhenClickMenu;
@property(nonatomic) double rowHeight; // @synthesize rowHeight=_rowHeight;
@property(nonatomic) double maxMenuListHeight; // @synthesize maxMenuListHeight=_maxMenuListHeight;
@property(nonatomic) double menuListWidth; // @synthesize menuListWidth=_menuListWidth;
@property(nonatomic) struct CGPoint menuListOffset; // @synthesize menuListOffset=_menuListOffset;
@property(copy, nonatomic) CDUnknownBlockType clickBackgroundBlock; // @synthesize clickBackgroundBlock=_clickBackgroundBlock;
@property(copy, nonatomic) CDUnknownBlockType clickMenuBlock; // @synthesize clickMenuBlock=_clickMenuBlock;
@property(readonly, copy, nonatomic) NSArray *iconArray; // @synthesize iconArray=_iconArray;
@property(readonly, copy, nonatomic) NSArray *titleArray; // @synthesize titleArray=_titleArray;
- (void).cxx_destruct;
@property(readonly, nonatomic) UITableView *tableView;
- (struct CGRect)arrowFrameWithContentView:(id)arg1 direaction:(long long)arg2;
- (void)addArrowMaskToView:(id)arg1 direction:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)performHideAnimation;
- (void)prepareHideAnimation;
- (void)performShowAnimation;
- (void)prepareShowAnimatoin;
- (void)didMoveToWindow;
- (void)didHide;
- (void)clickBackgroud;
- (void)setTitleArray:(id)arg1 iconArray:(id)arg2;
- (void)willShowInView:(id)arg1;
- (void)didInitialize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

