//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface XMOOMUploadStack : NSObject
{
    _Bool _isVM;
    unsigned int _malloc_size;
    unsigned int _malloc_count;
    NSString *_stackSymbols;
}

@property(copy, nonatomic) NSString *stackSymbols; // @synthesize stackSymbols=_stackSymbols;
@property(nonatomic) unsigned int malloc_count; // @synthesize malloc_count=_malloc_count;
@property(nonatomic) unsigned int malloc_size; // @synthesize malloc_size=_malloc_size;
@property(nonatomic) _Bool isVM; // @synthesize isVM=_isVM;
- (void).cxx_destruct;

@end

