//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAGradientLayer, LOTAnimationView, UIButton, UIImageView, UILabel, XMOVoiceSignatureInfoModel, XMOthersSoundSignatureUserPresenter;

@interface XMOthersSoundSignatureUserView : UIView
{
    _Bool _shouldRecord;
    XMOthersSoundSignatureUserPresenter *_presenter;
    UIImageView *_backImageView;
    UIView *_shouldRecordBackView;
    CAGradientLayer *_shouldRecordLayer;
    UIButton *_shouldRecordButton;
    UIButton *_reRecordButton;
    UIImageView *_shouldRecordImageView;
    UIView *_recordBackView;
    LOTAnimationView *_animationView;
    UIImageView *_lottieBackImageView;
    UILabel *_durationLabel;
    CAGradientLayer *_middleLine;
    UIButton *_playButton;
    UIButton *_praiseButton;
    UILabel *_praiseCountLabel;
    XMOVoiceSignatureInfoModel *_model;
    LOTAnimationView *_shouldRecordBackViewNew;
}

+ (struct CGSize)maxSize;
+ (struct CGSize)defaultSize;
+ (struct CGSize)shouldRecordSize;
@property(retain, nonatomic) LOTAnimationView *shouldRecordBackViewNew; // @synthesize shouldRecordBackViewNew=_shouldRecordBackViewNew;
@property(retain, nonatomic) XMOVoiceSignatureInfoModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UILabel *praiseCountLabel; // @synthesize praiseCountLabel=_praiseCountLabel;
@property(retain, nonatomic) UIButton *praiseButton; // @synthesize praiseButton=_praiseButton;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) CAGradientLayer *middleLine; // @synthesize middleLine=_middleLine;
@property(retain, nonatomic) UILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(retain, nonatomic) UIImageView *lottieBackImageView; // @synthesize lottieBackImageView=_lottieBackImageView;
@property(retain, nonatomic) LOTAnimationView *animationView; // @synthesize animationView=_animationView;
@property(retain, nonatomic) UIView *recordBackView; // @synthesize recordBackView=_recordBackView;
@property(retain, nonatomic) UIImageView *shouldRecordImageView; // @synthesize shouldRecordImageView=_shouldRecordImageView;
@property(retain, nonatomic) UIButton *reRecordButton; // @synthesize reRecordButton=_reRecordButton;
@property(retain, nonatomic) UIButton *shouldRecordButton; // @synthesize shouldRecordButton=_shouldRecordButton;
@property(retain, nonatomic) CAGradientLayer *shouldRecordLayer; // @synthesize shouldRecordLayer=_shouldRecordLayer;
@property(retain, nonatomic) UIView *shouldRecordBackView; // @synthesize shouldRecordBackView=_shouldRecordBackView;
@property(retain, nonatomic) UIImageView *backImageView; // @synthesize backImageView=_backImageView;
@property(retain, nonatomic) XMOthersSoundSignatureUserPresenter *presenter; // @synthesize presenter=_presenter;
@property(nonatomic) _Bool shouldRecord; // @synthesize shouldRecord=_shouldRecord;
- (void).cxx_destruct;
- (void)updateWithModel:(id)arg1;
- (void)p_startShouldRecordBackViewNewAnimation;
- (void)updateView;
- (void)p_setPresenter;
- (void)p_setUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

