//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class LOTAnimationView, NSString, UIImageView, UILabel, XMWebImageView;

@interface XMPCHeaderCoinView : UIControl
{
    _Bool _isCoinType;
    NSString *_iconPath;
    NSString *_text0;
    NSString *_text1;
    long long _status;
    UIImageView *_containView;
    XMWebImageView *_coinImageView;
    LOTAnimationView *_animationView;
    UILabel *_label0;
}

@property(retain, nonatomic) UILabel *label0; // @synthesize label0=_label0;
@property(retain, nonatomic) LOTAnimationView *animationView; // @synthesize animationView=_animationView;
@property(retain, nonatomic) XMWebImageView *coinImageView; // @synthesize coinImageView=_coinImageView;
@property(retain, nonatomic) UIImageView *containView; // @synthesize containView=_containView;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *text1; // @synthesize text1=_text1;
@property(copy, nonatomic) NSString *text0; // @synthesize text0=_text0;
@property(copy, nonatomic) NSString *iconPath; // @synthesize iconPath=_iconPath;
@property(nonatomic) _Bool isCoinType; // @synthesize isCoinType=_isCoinType;
- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (void)p_setupViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

