//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSStreamDelegate-Protocol.h"
#import "ProxyHttpClientDeleagete-Protocol.h"

@class NSHTTPURLResponse, NSInputStream, NSMutableData, NSMutableDictionary, NSString, NSURLRequest, XMProxyHttpConfig;

@interface XMProxyHttpClient : NSObject <ProxyHttpClientDeleagete, NSStreamDelegate>
{
    struct __CFHTTPMessage *_HTTPMessage;
    NSURLRequest *_request;
    XMProxyHttpConfig *_proxyHttpCfg;
    NSInputStream *_httpStream;
    NSHTTPURLResponse *_urlResponse;
    NSMutableData *_buffer;
    NSMutableDictionary *_headerDictForChinaComm;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *headerDictForChinaComm; // @synthesize headerDictForChinaComm=_headerDictForChinaComm;
@property(retain, nonatomic) NSMutableData *buffer; // @synthesize buffer=_buffer;
@property(retain, nonatomic) NSHTTPURLResponse *urlResponse; // @synthesize urlResponse=_urlResponse;
@property(retain, nonatomic) NSInputStream *httpStream; // @synthesize httpStream=_httpStream;
@property(retain, nonatomic) XMProxyHttpConfig *proxyHttpCfg; // @synthesize proxyHttpCfg=_proxyHttpCfg;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (_Bool)isFromXMLYDomain:(id)arg1;
- (void)needAuthenRequest:(id)arg1 withProxyHTTPHeaderParam:(id *)arg2;
- (void)needAuthenRequstWithUserName:(id *)arg1 withPassword:(id *)arg2;
- (void)needProxyHost:(id *)arg1 withPort:(long long *)arg2 withProxyType:(id *)arg3;
- (void)setProxyEffectURL;
- (void)unregisterClient;
- (void)disableHttpProxy;
- (void)enableHttpProxy;
- (void)checkAndSetProxyType;
- (void)registerClient;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

