//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class XMRecommendUserCell, XMTableCellObject;

@protocol XMRecommendUserCellDelegate <NSObject>
- (void)userCellDidLongPress:(XMTableCellObject *)arg1;
- (void)hotUserCellChangeFav:(XMRecommendUserCell *)arg1;
@end

