//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMSubLevelViewController.h"

@class NSMutableArray, UIView, XMPresentRecordModel, XMReceiveRecordData;

@interface XMReceiveRecordViewController : XMSubLevelViewController
{
    int _page;
    NSMutableArray *_dataArray;
    UIView *_headView;
    XMPresentRecordModel *_model;
    XMReceiveRecordData *_data;
}

@property(nonatomic) int page; // @synthesize page=_page;
@property(retain, nonatomic) XMReceiveRecordData *data; // @synthesize data=_data;
@property(retain, nonatomic) XMPresentRecordModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (void)requestWithPage:(int)arg1;
- (void)triggerLoadMore;
- (void)triggerPullToRefresh;
- (_Bool)isLoadMoreViewNeeded;
- (void)viewDidLoad;
- (id)initWithPresentRecordModel:(id)arg1;

@end

