//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSAttributedString, NSString, UIColor, UIFont, UILabel;
@protocol XMScrollLabelDelegate;

@interface XMScrollLabel : UIView
{
    UILabel *_label;
    struct CGSize _origSize;
    _Bool _isMoveBackward;
    double _lengthOfScroll;
    double _duration;
    double _delay;
    double _fadeLength;
    struct CGRect _homeLabelFrame;
    struct CGRect _alwaysLabelFrame;
    struct CGSize _labelSize;
    unsigned long long _animationOptions;
    UIView *_tailView;
    struct CGSize _tailViewSize;
    _Bool _isUseForYijianting;
    _Bool _scrollUnable;
    id <XMScrollLabelDelegate> delegate;
    NSAttributedString *_attributedText;
    long long _textAlignment;
}

@property(nonatomic) _Bool scrollUnable; // @synthesize scrollUnable=_scrollUnable;
@property(nonatomic) _Bool isUseForYijianting; // @synthesize isUseForYijianting=_isUseForYijianting;
@property(nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
@property(retain, nonatomic) NSAttributedString *attributedText; // @synthesize attributedText=_attributedText;
@property(nonatomic) __weak id <XMScrollLabelDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)stopAnimation;
- (void)startAnimation;
@property(retain, nonatomic) UIFont *font;
@property(retain, nonatomic) UIColor *backgroundColor;
@property(nonatomic) struct CGSize textShadowOffset;
@property(retain, nonatomic) UIColor *textShadowColor;
@property(retain, nonatomic) UIColor *textColor;
@property(retain, nonatomic) NSString *text;
- (_Bool)labelShouldScroll;
- (void)returnLabelToOriginImmediately;
- (void)beginScroll;
- (id)tailAnimationGroup:(double)arg1;
- (id)labelAnimationGroup:(double)arg1;
- (void)startScrollAnimation:(double)arg1;
- (void)scrollAlwaysWithInterval:(double)arg1;
- (void)scrollHomeWithInterval:(double)arg1;
- (void)resetFade;
- (void)setupFade;
- (void)shutdownLabel;
- (void)restartLabel;
- (void)observedViewControllerChange:(id)arg1;
- (void)setupNotify;
- (id)initWithFrame:(struct CGRect)arg1 duration:(double)arg2 andFadeLength:(double)arg3;
- (void)dealloc;

@end

