//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSIndexPath, NSString, UITableViewCell, XMNewPaidRecModuleItem, XMVipChannelHeaderItem;
@protocol XMTableCellModelProtocol;

@interface XMTableCellObject : NSObject
{
    UITableViewCell *_customCell;
    id <XMTableCellModelProtocol> _cellModel;
    id _userInfo;
    NSIndexPath *_indexPath;
    Class _cellClass;
    NSString *_cellName;
    NSString *_reuseIdentifier;
    id _cellCustomDelegate;
    NSString *_cacheKey;
}

@property(copy, nonatomic) NSString *cacheKey; // @synthesize cacheKey=_cacheKey;
@property(nonatomic) __weak id cellCustomDelegate; // @synthesize cellCustomDelegate=_cellCustomDelegate;
@property(copy, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;
@property(readonly, copy, nonatomic) NSString *cellName; // @synthesize cellName=_cellName;
@property(readonly, nonatomic) Class cellClass; // @synthesize cellClass=_cellClass;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) id <XMTableCellModelProtocol> cellModel; // @synthesize cellModel=_cellModel;
- (void).cxx_destruct;
- (void)setCellReuseIdentifier:(id)arg1;
@property(readonly, nonatomic) UITableViewCell *customCell;
- (id)initWithCell:(id)arg1;
- (id)initWithCellClass:(Class)arg1 withCellDelegate:(id)arg2;
- (id)initWithCellClass:(Class)arg1;
@property(nonatomic) _Bool isVip;
@property(nonatomic) long long positionInModule;
@property(nonatomic) long long modulePosition;
@property(retain, nonatomic) XMVipChannelHeaderItem *moduleHeader;
@property(retain, nonatomic) NSDictionary *xmubt_tabInfo;
@property(retain, nonatomic) XMNewPaidRecModuleItem *paidRec_moduleHeader;

@end

