//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, UIButton, UIImageView, UILabel;
@protocol XMToastViewDelegate;

@interface XMToastView : UIView
{
    UIButton *_bgBtn;
    UIImageView *_arrowView;
    UILabel *_toastLabel;
    UILabel *_countDownLabel;
    int secondsAlreadyShow;
    _Bool _showCountdown;
    int type;
    id <XMToastViewDelegate> delegate;
    NSTimer *toastTimer;
    double showDuration;
    long long _shakeLottoryTimeRemain;
}

@property(nonatomic) long long shakeLottoryTimeRemain; // @synthesize shakeLottoryTimeRemain=_shakeLottoryTimeRemain;
@property(nonatomic) _Bool showCountdown; // @synthesize showCountdown=_showCountdown;
@property(nonatomic) int type; // @synthesize type;
@property(nonatomic) double showDuration; // @synthesize showDuration;
@property(retain, nonatomic) NSTimer *toastTimer; // @synthesize toastTimer;
@property(nonatomic) __weak id <XMToastViewDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)stopToastTimer;
- (void)toastTimerFired;
- (void)startToastTimer;
- (void)hiddenToastAnimated:(_Bool)arg1;
- (void)showToastInView:(id)arg1 animated:(_Bool)arg2;
- (void)onClick:(id)arg1;
- (void)layoutSubviews;
- (void)customInit:(id)arg1;
- (id)initWithTitle:(id)arg1 arrowType:(int)arg2;
- (id)initWithTitle:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

