//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMBaseViewController.h"

#import "XMTrackBuyViewDelegate-Protocol.h"

@class NSString, XMBatchSelectDetaiView, XMTrackBuyBgView, XMTrackBuyItem, XMTrackBuyView;

@interface XMTrackBuyConfirmViewController : XMBaseViewController <XMTrackBuyViewDelegate>
{
    _Bool _derectlyBuy;
    _Bool _justForTrackBuyRequest;
    _Bool _buyRemaining;
    XMTrackBuyItem *_trackBuy;
    XMTrackBuyBgView *_bgView;
    XMTrackBuyView *_buyView;
    XMBatchSelectDetaiView *_detailView;
    CDUnknownBlockType _trackBuyComplete;
}

+ (id)trackbuyContextFromParams:(id)arg1;
+ (void)buyTracks:(id)arg1 withAlbumId:(long long)arg2 andBuyRemaining:(_Bool)arg3 autoBuy:(_Bool)arg4 andParams:(id)arg5 andComplete:(CDUnknownBlockType)arg6;
@property(copy, nonatomic) CDUnknownBlockType trackBuyComplete; // @synthesize trackBuyComplete=_trackBuyComplete;
@property(retain, nonatomic) XMBatchSelectDetaiView *detailView; // @synthesize detailView=_detailView;
@property(retain, nonatomic) XMTrackBuyView *buyView; // @synthesize buyView=_buyView;
@property(retain, nonatomic) XMTrackBuyBgView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) _Bool buyRemaining; // @synthesize buyRemaining=_buyRemaining;
@property(nonatomic) _Bool justForTrackBuyRequest; // @synthesize justForTrackBuyRequest=_justForTrackBuyRequest;
@property(nonatomic) _Bool derectlyBuy; // @synthesize derectlyBuy=_derectlyBuy;
@property(retain, nonatomic) XMTrackBuyItem *trackBuy; // @synthesize trackBuy=_trackBuy;
- (void).cxx_destruct;
- (void)postBuyVIPTracksDataTrack;
- (void)postFinishedTrackBuy;
- (void)postStartPayDataTrack;
- (void)addStateView:(_Bool)arg1;
- (void)onFailedConfirmTrackBuy:(id)arg1;
- (void)onFinishedConfirmTrackBuy:(id)arg1;
- (void)requestConfirmTrackBuy:(id)arg1;
- (void)showConfirmViewWithTrackBuy:(id)arg1;
- (void)showInsufficientViewWithTrackBuy:(id)arg1;
- (void)checkViewToShow:(id)arg1;
- (void)requestTrackBuyAlbum:(id)arg1;
- (void)requestTrackBuyOneTrack:(id)arg1;
- (_Bool)isMoneyEnough;
- (void)vipButtonDidClick:(id)arg1 andTrackBuy:(id)arg2;
- (void)startRecharge:(id)arg1 withBuyItem:(id)arg2;
- (void)startDownloadLater:(id)arg1;
- (void)startBuyMore:(id)arg1;
- (void)startBuy:(id)arg1;
- (void)closeTrackBuyView:(id)arg1;
- (void)dismissTrackBuyView;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

