//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface XMVCPropGroupModel : NSObject
{
    float _contentOffsetY;
    NSMutableArray *_items;
}

@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(nonatomic) float contentOffsetY; // @synthesize contentOffsetY=_contentOffsetY;
- (void).cxx_destruct;
- (unsigned long long)currentIndex;
- (unsigned long long)indexOfProp:(id)arg1;
- (void)cleanSelectedProp;
- (void)selectedPropWithIndex:(unsigned long long)arg1;
- (void)selectedProp:(id)arg1;

@end

