//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class XMNRequest, XMNewYiJianTingHomePageModel, XMTimer;

@interface XMYiJianTingChannelProvider : NSObject
{
    _Bool _fromSleepMode;
    long long _sceneId;
    XMNewYiJianTingHomePageModel *_homePageModel;
    CDUnknownBlockType _sceneIdHasConfig;
    XMNRequest *_sceneRequest;
    XMNRequest *_channelListRequest;
    XMNRequest *_newsGroupRequest;
    XMTimer *_timer;
}

@property(retain, nonatomic) XMTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) XMNRequest *newsGroupRequest; // @synthesize newsGroupRequest=_newsGroupRequest;
@property(retain, nonatomic) XMNRequest *channelListRequest; // @synthesize channelListRequest=_channelListRequest;
@property(retain, nonatomic) XMNRequest *sceneRequest; // @synthesize sceneRequest=_sceneRequest;
@property(copy, nonatomic) CDUnknownBlockType sceneIdHasConfig; // @synthesize sceneIdHasConfig=_sceneIdHasConfig;
@property(retain, nonatomic) XMNewYiJianTingHomePageModel *homePageModel; // @synthesize homePageModel=_homePageModel;
@property(nonatomic) long long sceneId; // @synthesize sceneId=_sceneId;
@property(nonatomic) _Bool fromSleepMode; // @synthesize fromSleepMode=_fromSleepMode;
- (void).cxx_destruct;
- (void)startObserverSceneId;
- (void)saveGroupIds:(id)arg1 channelId:(long long)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)getNewsGroupWithCompletion:(CDUnknownBlockType)arg1;
- (void)getChannelList:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)getSceneIdWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithSceneId:(long long)arg1;
- (void)p_requestSceneIdWhenTimeFly;
- (void)p_requestChannelListWithCompletion:(CDUnknownBlockType)arg1;
- (void)p_requestSceneIdWithCompletion:(CDUnknownBlockType)arg1;

@end

