//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface YBIBPhotoAlbumManager : NSObject
{
}

+ (void)video:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
+ (void)saveVideoToAlbumWithPath:(id)arg1;
+ (void)completedWithImage:(id)arg1 error:(id)arg2 context:(void *)arg3;
+ (void)saveImageToAlbum:(id)arg1;
+ (void)saveDataToAlbum:(id)arg1;
+ (void)getPhotoAlbumAuthorizationSuccess:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
+ (void)getImageDataWithPHAsset:(id)arg1 success:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
+ (void)getAVAssetWithPHAsset:(id)arg1 success:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;

@end

