//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDelegate-Protocol.h"
#import "YBImageBrowserCellDataProtocol-Protocol.h"

@class AVAsset, NSString, NSURL, NSURLSessionDownloadTask, PHAsset, UIImage;

@interface YBVideoBrowseCellData : NSObject <NSURLSessionDelegate, YBImageBrowserCellDataProtocol>
{
    NSURLSessionDownloadTask *_downloadTask;
    _Bool _allowSaveToPhotoAlbum;
    _Bool _allowShowSheetView;
    _Bool _loading;
    NSURL *_url;
    PHAsset *_phAsset;
    AVAsset *_avAsset;
    id _sourceObject;
    UIImage *_firstFrame;
    unsigned long long _autoPlayCount;
    unsigned long long _repeatPlayCount;
    id _extraData;
    long long _dataState;
    long long _dataDownloadState;
    double _downloadingVideoProgress;
}

+ (struct CGSize)getSizeOfCurrentLayoutDirection;
+ (struct CGSize)getPixelSizeOfCurrentLayoutDirection;
+ (struct CGRect)getImageViewFrameWithImageSize:(struct CGSize)arg1;
@property(nonatomic) double downloadingVideoProgress; // @synthesize downloadingVideoProgress=_downloadingVideoProgress;
@property(nonatomic) long long dataDownloadState; // @synthesize dataDownloadState=_dataDownloadState;
@property(nonatomic) long long dataState; // @synthesize dataState=_dataState;
@property(nonatomic) _Bool loading; // @synthesize loading=_loading;
@property(retain, nonatomic) id extraData; // @synthesize extraData=_extraData;
@property(nonatomic) _Bool allowShowSheetView; // @synthesize allowShowSheetView=_allowShowSheetView;
@property(nonatomic) _Bool allowSaveToPhotoAlbum; // @synthesize allowSaveToPhotoAlbum=_allowSaveToPhotoAlbum;
@property(nonatomic) unsigned long long repeatPlayCount; // @synthesize repeatPlayCount=_repeatPlayCount;
@property(nonatomic) unsigned long long autoPlayCount; // @synthesize autoPlayCount=_autoPlayCount;
@property(retain, nonatomic) UIImage *firstFrame; // @synthesize firstFrame=_firstFrame;
@property(nonatomic) __weak id sourceObject; // @synthesize sourceObject=_sourceObject;
@property(retain, nonatomic) AVAsset *avAsset; // @synthesize avAsset=_avAsset;
@property(retain, nonatomic) PHAsset *phAsset; // @synthesize phAsset=_phAsset;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (void)video:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (void)downloadWithUrl:(id)arg1;
- (void)loadFirstFrameOfVideo;
- (_Bool)loadLocalFirstFrameOfVideo;
- (void)loadAVAssetFromPHAsset;
- (void)loadData;
- (void)yb_preload;
- (void)yb_browserSaveToPhotoAlbum;
- (_Bool)yb_browserAllowSaveToPhotoAlbum;
- (_Bool)yb_browserAllowShowSheetView;
- (struct CGRect)yb_browserCurrentImageFrameWithImageSize:(struct CGSize)arg1;
- (id)yb_browserCellSourceObject;
- (Class)yb_classOfBrowserCell;
- (void)initVars;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

